Cargo.lock, Cargo.toml
Hi this is just bumping some versions to compile with current nightly.
It generates a bunch of warnings about deprecated functionality in diesel, but that doesn't affect functionality for now, so I might look into it in a separate PR.
Thanks for your work on this, this is truly amazing bitwarden API implementation.
=> Bump the rocket version to compile with current nightly

Dockerfile, README.md, web-vault/settings.Production.json
Hi, this extends the Dockerfile and builds the Vault files straight from upstream, so you can switch it easily. Should make it easier to follow the upstream.
=> Fetch Vault from upstream when building Docker image

src/api/core/ciphers.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/db/models/cipher.rs
This extends the API to post cipher for an Organization. Also `Cipher::to_json()` now also returns organization uuid if present.
=> Add support for adding and viewing of org ciphers

src/api/core/accounts.rs, src/api/core/ciphers.rs, src/db/models/cipher.rs
This splits the `find_by_user` into two separate functions: `find_owned_by_user` which retains previous functionality and lists only ciphers directly owned by user and `find_by_user` which now also lists all ciphers shared with user.
As a result shared ciphers are now visible in user's vault.
There's also small change in the `/api/ciphers/purge` handler to use the `find_owned_by_user` instead to only purge user's content and not the shared stuff.
=> Also list shared ciphers in find_by_user

src/db/models/organization.rs
This should enable adding attachments to shared ciphers and resolve #15.
=> set max storage to non-null value

src/api/core/ciphers.rs, src/api/core/mod.rs, src/db/models/organization.rs
This implements sharing an user-owned Cipher to Organization.
For now this only implements functionality for user that has at least `access_all` rights to the organization. I *think* that it should be possible to share Cipher to a specific collection only if the user has write access, however this will require some update to `update_cipher_from_data`, which would probably be better handled in separate PR.
=> Implement cipher sharing

src/api/core/ciphers.rs
This fixes a but for sharing Ciphers where `user_uuid` was left in the cipher record which prevented other users from accessing the cipher even if they should be able to.
=> Remove user_uuid when sharing to organization

src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/folders.rs, src/db/models/folder.rs
This moves the `FolderCipher` deletion into `Folder.delete()` so we do also remove the `FolderCipher` mapping no matter where we call the `delete()`. Also improvements were added to handle failures better as per #6.
=> Improve Folder::delete() to handle FolderCipher

Cargo.lock, Cargo.toml
Update rocket to 0.3.11 to successfully compile on latest nightly.
=> Update rocket to 0.3.11

migrations/2018-05-25-232323_update_attachments_reference/up.sql
We broke the attachment functionality in 514a372 when we didn't update the table reference for attachment and it still points to old, deleted cipher table. This migrates the attachment records into new table with proper reference.
=> Fix reference in attachments table

src/db/models/cipher.rs
This checks out two TODOs: 
1. Extends `Cipher::is_write_accessible_to_user` with a check for any collection that might give R/W access to cipher.
2. Implements `Cipher::is_accessible_to_user` with a proper check for any RO access. 
The current solution works quite well, but I don't like the code repetition. Any input would be greatly appreciated how to solve this in some reasonable manner. I was thinking about using `into_boxed()` at some stage to promote some code reuse, but I just don't know enough about diesel to pull this off successfully.
Other approach would be to split it into multiple sub-checks and aggregate those but that would lead to 5x the amount of queries, which I'd like to avoid.
Any ideas?
=> Better check for cipher access

Dockerfile
This copies the rust-toolchain file into the build container to make sure we use the proper toolchain from the beginning. I've also switched the build image to official `rust` as we're going to pull requested toolchain anyways.
=> Use proper toolchain in Dockerfile

README.md
Now that we know it works this way, we should probably document it. :writing_hand:
=> Add limits configuration to the readme

README.md
This just adds some documentation for users wanting to run the image with unprivileged user inside container.
=> Document running container with lower privileges (fixes #66)

BUILD.md, README.md
Hi!
I made two packages for Archlinux, one for the purists (without web interface) and one with the web interface and wanted to link to them here.
I'm not sure if that is the best position to advertise this, let me know if you think the links are better put elsewhere.
Apart from that: If you have any other suggestions/remarks for repackaging, please tell me. 
Currently I'm linking to the latest master commit, but I would really welcome it if you could make a release every now and then.
Thanks for your great work!
=> Add a link to Archlinux AUR packages

BUILD.md, README.md
Couple changes here:
* TOC added as the Readme is already quite big and cumbersome to navigate
* Moved the Arch package info from build instructions to new Packages section here as it was kinda lost and inappropriate in the build doc. Also credited @mqus on this one.
* Added Matrix chat room information (resolves #76)
* Fixed couple typos
=> Readme updates (chat, arch, TOC)

README.md, src/db/models/collection.rs, src/db/models/organization.rs
This should hide collections and organizations from user that has not been yet accepted. 
(and I've sneaked in some readme update to avoid issue with visible comment on docker hub)
=> Do not show organization stuff to not accepted user

README.md
I changed the way bitwarden_rs is packaged (the web interface is now an addon-package instead of bundled) and added a 'stable' package which follows recent releases.
I assume that following releases instead of the master branch is encouraged so I removed the link to the (still existing) bitwarden_rs-git package which does the latter.
OT-Comment on the diff: huh? I edited the file in the github-editor but somehow that last line got a change I didn't intent to make and I can't seem to find a difference... strange
=> Reflect changes in Archlinux packaging

src/auth.rs
This updates the OrgHeaders request guard to check whether user is confirmed. This should disallow all Organization actions if user isn't yet confirmed. I think this should resolve last problem in #80.
=> Add confirmed check to the OrgHeaders request guard

Dockerfile, README.md
This is setting the number of workers to 10. The issue with the default behavior was that on some systems with low number of cores this leads to very low number of workers (`2 * $cpu_cores_number`) and poor performance. Especially on cloud instances, that often have just one core.
The default is set somewhat conservatively to 10 as most browsers won't create more than ~8 simultaneous connections to the same domain anyway. The documentation was added to let users know, they can increase this number in case they have large number of users where 10 workers might not be enough.
=> Change number of workers in image, document the setting (fixes #90)

Cargo.toml, src/api/web.rs
Currently we return 404 if `WEB_VAULT_ENABLED` is set to `false` and 500 if Vault is enabled. Upstream API responds with 404 for non-existent endpoints, so we should do the same.
=> Return 404 in case the path doesn't match instead of 500

README.md
Using the room ID instead of an alias isn't supposed to be working for joining rooms, and doesn't work when joining over federation. It only works when your server is already participating in the room.
=> Update matrix.to link in the README

src/api/core/ciphers.rs, src/api/core/mod.rs
Have made changes to support `PUT` call for `/api/ciphers/move` instead of `POST` as  new vault version (2.0) makes a `PUT` call.
=> Implementing PUT for 'api/ciphers/move' (#99)

src/api/core/ciphers.rs, src/api/core/mod.rs
Implemented PUT for "api//ciphers/<uuid>/share" as the new Vault version (2.0) is no longer using POST.
=> Implemented PUT for single cipher sharing (#97)

src/api/core/ciphers.rs, src/api/core/mod.rs, src/db/models/attachment.rs
Implemented bulk cipher share "api/ciphers/share", as the new Vault version (2.0) supports bulk share.
=> Implemented bulk cipher share (share selected) #100

src/api/core/ciphers.rs, src/db/models/user.rs
This adds `update_revision` for `user`. So far it only seems to be necessary for the cipher import handling, so I've used it there. This should resolve #117, hopefully the last outstanding Vault 2 related issue.
=> Implement update_revision trigger

src/api/core/ciphers.rs, src/api/core/mod.rs
This should fix the issue with editing cipher in the Vault. I've also removed the TODO as I believe we actually did implement this correctly when we re-did the `Cipher::is_write_accessible_to_user`.
=> Add PUT alias for editing cipher

src/util.rs
This follows the new error object format as observed in upstream implementation.
=> Update the error format to show message in new Vault

src/db/models/user.rs
The function borrows the user struct mutably, but doesn't actually update the revision date there. In our current use case this wasn't a problem, but might be an issue later on.
=> Actually update the revision date for user struct, not just in DB

src/db/models/collection.rs, src/db/models/user.rs
It appears, that Vault 2 checks the revision to know whether it should update the cipher data. This change updates user's revision when major changes like collection access change occurs. This way the user can see proper ciphers as he gained/lost access to them without logging off and back in.
=> Update affected users revision when there are collection changes

src/api/core/mod.rs, src/api/core/organizations.rs, src/db/models/organization.rs
This adds revision update for affected users when Organization membership or Organization itself changes.
Also adds PUT alias for saving Organization details.
=> Organization update improvements

src/db/models/cipher.rs, src/db/models/folder.rs, src/db/models/organization.rs
This should update revision for all affected users on cipher and folder changes. The `find_by_cipher_and_org` definitely needs another pair of eyes to double-check. (from my limited testing it does what it should)
=> Update affected users revision on cipher and folder change

Cargo.toml
Can you also do a release? This is in preparation for next PR merging in beta.
=> Bump version to 0.13.0 - latest Vault v1

src/api/core/organizations.rs, src/db/models/organization.rs
This fixes multiple issues:
1. [Make sure](https://github.com/mprasil/bitwarden_rs/blob/049aa33f179076a6b1ba3b71351b5d7b95ef4fdc/src/api/core/organizations.rs#L481) the user is actually member of organization we're managing.
2. Fix #163 by [allowing](https://github.com/mprasil/bitwarden_rs/blob/049aa33f179076a6b1ba3b71351b5d7b95ef4fdc/src/api/core/organizations.rs#L486-L497) admin users to edit other admin users.
The implemented change allows admin users to change collection access for other admin users and themselves. Admin user is however not allowed to promote other users to Admin type or drop Admin privileges for other admin users.
3. Change `user_id` dynamic parameters to `org_user_id` as this better reflects the actual information that's provided.
=> Fix editing users in Organization

Dockerfile, Dockerfile.alpine
This exposes the port required for the websocket and notifications support for the docker images.
=> Expose 3012 in docker build file for notifications

README.md, migrations/2018-09-10-111213_add_invites/down.sql, migrations/2018-09-10-111213_add_invites/up.sql, src/api/core/accounts.rs, src/api/core/organizations.rs, src/db/models/mod.rs, src/db/models/organization.rs, src/db/models/user.rs, src/db/schema.rs, src/main.rs
This should allow invitation-only registration via Organization invitations. The way it works follows the suggested approach [outlined](https://github.com/dani-garcia/bitwarden_rs/issues/40#issue-331759674) in #40. When Admin/Owner invites user with an email that is not found, a new record in `invitations` table is created. At the same time an `User` is created with random password and key generated just as a "placeholder".
When user tries to register, they will be allowed to do so even if SIGNUPS_ALLOWED is set to false if their email is in the invitations table.
This should also allow user to register without the placeholder `User` already being present, which would accommodate some external integration like the one [suggested](https://github.com/dani-garcia/bitwarden_rs/issues/40#issuec …
=> Implement poor man's invitation via Organization invitation

PROXY.md
Added an example on how to proxy Bitwarden properly with [Traefik](https://traefik.io/)
=> traefik proxy example

src/api/core/ciphers.rs, src/api/core/folders.rs, src/api/core/organizations.rs, src/api/core/two_factor.rs
This sends `"ContinuationToken": null` every time we send `"Object": "list"` as it looks like Vault can get confused when such field isn't present.
=> Add continuation token when we return object list

src/api/core/mod.rs, src/api/core/organizations.rs
Fixes #188.
Displays an error message in the log when the user clicks the `Resend invitation` option for a user on the Organization/People admin panel.
=> Return proper error message for org reinvite

README.md, src/api/core/accounts.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/identity.rs, src/auth.rs, src/db/models/cipher.rs, src/db/models/device.rs, src/db/models/folder.rs, src/db/models/organization.rs, src/db/models/user.rs, src/main.rs
This enables you to configure one email account to be server administrator via the `SERVER_ADMIN_EMAIL` environment variable. This will give the user extra functionality and privileges to manage users on the server. In the Vault, the user will see a special (virtual) organization called `bitwarden_rs`. Deleting users from this organization will actually completely delete the user from the server. Inviting users into this organization will just invite the user so they are able to register, but will not grant any organization membership.
This should hopefully cover use cases like the one in #212 and #202 without actually creating the admin panel.
=> Implement poor man's admin panel

README.md, src/api/notifications.rs, src/main.rs
This let's users enable WebSockets by setting the `WEBSOCKET_ENABLED` variable to `true`. The reason why I suggest to have this off by default is that for users that won't do that extra proxy configuration this causes issues like the one observed in #203 - essentially breaking the organization functionality in unpredictable way. 
Users using WebSockets need to do some extra configuration anyways and while this change will break their configuration, it will not break the core functionality, just the WebSockets won't be used until they turn it back on.
=> Disable WebSockets negotiation by default

src/api/core/ciphers.rs, src/api/core/mod.rs
Due to Rocket being a bit weird with query strings currently (see [this Rocket issue](https://github.com/SergioBenitez/Rocket/issues/376)), my last change (#225) broke clients which call `/sync` without the `?excludeDomains=` query string. At least the Firefox addon is affected.
Until Rocket releases their new query string parsing logic [implemented here](https://github.com/SergioBenitez/Rocket/issues/608) in `0.4.0`, we're probably stuck with this rather ugly workaround.
=> Fix /sync without query string

src/api/core/mod.rs
Fixes #230.
It seems the Web Vault actually expects a JSON instead of any empty response too, so I changed that as well. Seems to work as expected.
=> Accept PUT and POST on /settings/domains, returns JsonResult, fixes saving Custom Equivalent Domains

Dockerfile.aarch64, Dockerfile.armv7
We used resin base images for raspberry images. Resin is now discontinued in favour of balenalib.
=> Switch from resin to balenalib

src/api/core/mod.rs, src/api/core/two_factor.rs
The Bitwarden API for u2f enrollment changed. Specifically, challenge generate was removed from `/api/two-factor/get-u2f` in to `/api/two-factor/get-u2f-challenge`. 
Presently, this PR restores the minimal functionality, but the desire is to implement multi-enrollment.
RE: #235
=> Make U2F work with vault 2.4.0 changes

src/db/models/cipher.rs
Small change to not show ciphers to user that wasn't yet confirmed.
=> Prevent accepted user from seeing ciphers until confirmed (fixes #196)

.env, Cargo.lock, Cargo.toml, README.md, src/api/core/mod.rs, src/api/core/two_factor.rs, src/api/identity.rs, src/main.rs
Resolves #86 
Feature Requests: #246
Features:
* Yubikey OTP Support
* Multiple keys (up to 5)
* Custom OTP Validation server
Known Issues:
* https://github.com/wisespace-io/yubico-rs/issues/4 The Yubico-rs library has an issue when sending out the OTP request to multiple validation servers simultaneously; any requests that finish after the caller has exited will panic.
* Impact: Validation still works as intended but the console will be populated with a couple panics every time a key is validated or registered.
Requires pkg-config and libusb
=> Adds Yubikey OTP Support

README.md
As discussed in #247 it would be nice if the documentation describes a way to do a backup of the database without installing sqlite to the host system. I also added the mkdir in Line 450 because it doesn't exist in the first place.
=> Update backup section of README.md

Dockerfile.aarch64, Dockerfile.alpine, Dockerfile.armv7
This updates the alpine Dockerfile to fix #259, it also simplifies the Dockerfiles for alpine, raspberry and aarch64 to build a little bit faster on docker hub.
=> Update dockerfile for alpine, armv7 and aarch64

Dockerfile.alpine
I forgot to update the path when copying built binary. This version should build successfully. (tested)
=> fix bad path in Alpine Dockerfile

README.md
=> Fail2Ban Setup & Walkthrough

src/api/identity.rs
Closes #264 by using the new rocket logging features to write IP addresses and usernames to logs on a successful login.
=> Close #264. Username and IP address is logged on successful authentication

Dockerfile.alpine
Currently docker hub fails to build alpine image, this should fix it.
=> Fix failing alpine build

BUILD.md, Dockerfile.alpine, src/api/core/accounts.rs, src/api/core/organizations.rs, src/auth.rs, src/mail.rs, src/main.rs
This PR adds support for emailing invite tokens to users who are invited to organizations. `EMAIL_INVITATIONS` has been added as a config option that, when enabled, will cause the /invite endpoint to generate a JWT which is valid for 5 days and email the user a link. When the user clicks the link, their UserOrganization status is set to "Accepted", which is what happened automatically before. The previous behavior is unchanged when `EMAIL_INVITATIONS` is not explicitly enabled.
Note the TODO in src/api/core/organizations.rs:511--currently, when the user clicks the invite link, they are just presented with a blank page. I couldn't figure out how to get redirection working in rocket but ideally they would be automatically redirected to the registration page with their email address …
=> Add Email Invite Functionality

README.md, src/api/core/organizations.rs
This PR updates the invitation /accept logic to rely on JWT validation for inviting existing users to new organizations. Previously, the invitations SQLite table was used, which resulted in a bug when an existing user was invited to join an organization because no invitation was created. 
I've also updated the README to document the new functionality surrounding email invitations and how it's necessary to set the `DOMAIN` configuration option so that links are generated correctly.
=> Fix email invitations for existing users and update README

README.md, src/main.rs
This PR makes a simple change to the timestamp format in the bitwarden logs so that fail2ban can parse it and take appropriate actions. I've also updated the fail2ban documentation to reflect these changes.
=> Change logging timestamp format so fail2ban can parse it

src/db/models/cipher.rs
It fixes #313 at least partially ... the other part being fixed by @mprasil's PR #314.
The problem was, that when multiple users in the same collection are Admin or Owner, the previous JOIN would include multiple rows for the same cipher. The PR fixes this by restricting the joined users_collections in the first place.
(It also makes another JOIN a little more explicit.)
=> Restrict join on users_collections to current user (fixes #313)

src/api/admin.rs, src/api/core/organizations.rs, src/auth.rs, src/mail.rs
This PR sends email notifications to users when their invitee accepts an invitation so they know when to confirm them. It also sends an email to the invitee when they are confirmed, which is the behavior indicated by the web vault when they call the /accept endpoint.
Additionally, I've replaced the specific `send_invite` function with a generic email sending function. This requires the subject and body to be formatted by the caller instead of the callee, which I think offers some flexibility for sending many different types of email, but I am open to discussion on whether we want to keep this approach.
=> Send email notifications when invitations are accepted/confirmed

src/api/core/ciphers.rs
Simple fix for issue in #341 - we didn't handle the case when the key is just being shared and hence the update won't have matching org IDs.
=> Fix sharing the item to organization.

src/api/icons.rs
Some sites use XSRF Tokens, or other Tokens to verify a subseqense
response. The cookies which are sent during the page request are now
used when downloading the favicon.
A site which uses this is mijn.ing.nl.
=> Added cookies to the icon download request.

src/api/core/ciphers.rs, src/db/models/user.rs
This should fix #383 (or any other mass operations that trigger a lot of updates)
=> Retry updating revision - fixes #383

src/db/models/collection.rs
We don't update revision for affected users when adding or removing Cipher from Collection. As a result users don't see new Ciphers and still see Ciphers they should no longer have access to. This should fix that.
=> Update revision when adding or removing cipher from collection

.env.template, src/api/admin.rs, src/config.rs
Adding this option so the /admin endpoint can be secured with an auth of your choosing.
=> Allow the Admin token to be disabled in the advanced menu

Cargo.lock, Cargo.toml, src/mail.rs
- Added quoted_printable crate to encode the e-mail messages.
- Change the way the e-mail gets build to use custom part headers.
=> Fixed long e-mail message extending 1000 lines.

Dockerfile.armv6
armv6 builds have been recently failing, because the `/lib/ld-linux.so.3` file seems to be already present in the latest `balenalib/rpi-debian:stretch` image. This removes the symlink.
=> Making a symlink is no longer necessary

Cargo.lock, Cargo.toml, src/mail.rs
URL-encode the email address when generating the invite link so that "+"s and other special characters get correctly filled-in by the vault instead of being interpreted as a space.
=> Fix #468 - Percent-encode the email address in invite link

src/api/identity.rs, src/config.rs
I've added a config option under Advanced.
=> Add config option to require new device emails

.env.template, src/config.rs, src/mail.rs
This allows using `Xoauth2` or forcing an auth mechanism over an unencrypted connection.
=> Allow explicitly defined smtp auth mechansim

docker/aarch64/mysql/Dockerfile, docker/aarch64/sqlite/Dockerfile, docker/amd64/mysql/Dockerfile, docker/amd64/mysql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/mysql/Dockerfile, docker/armv6/sqlite/Dockerfile, docker/armv7/mysql/Dockerfile, docker/armv7/sqlite/Dockerfile
This changes the healthcheck to use `sh` instead of bash, that is absent
from some image versions. (like alpine)
It also removes `*mariadb*` packages from runtime image of sqlite images
as these shouldn't be required.
=> Fix #603 and  remove mysql from sqlite image

Cargo.lock, Cargo.toml, build.rs, docker/amd64/postgresql/Dockerfile, docker/amd64/postgresql/Dockerfile.alpine, migrations/postgresql/2019-09-12-100000_create_tables/down.sql, migrations/postgresql/2019-09-12-100000_create_tables/up.sql, src/db/mod.rs, src/db/models/attachment.rs, src/db/models/cipher.rs, src/db/models/collection.rs, src/db/models/device.rs, src/db/models/folder.rs, src/db/models/organization.rs, src/db/models/two_factor.rs, src/db/models/user.rs, src/db/schemas/postgresql/schema.rs, src/main.rs
The biggest change to existing code is that `replace_into()` isn't supported by Diesel for the PostgreSQL back end, instead requiring the use of `on_conflict()`. This unfortunately requires a branch for `save()` on most of the models and requires PostgreSQL >= 9.5.
I've included `Dockerfile`'s for amd64 for both the Debian and Alpine variants, it should be straight forward to create new files for the other architectures but I don't currently have access to the other architectures and I didn't want to submit anything untested.
I've only done a couple hours worth of testing but everything seems to work. The migration SQL and model schema are both very similar to the existing two back ends.
Please let me know if you'd like any changes or if I missed anything.
=> Adds support for PostgreSQL which adds #87 and is mentioned in #246.

src/util.rs
- It's not `Access-Control-Allow-Methods` but `Access-Control-Allow-Method` where the value is the HTTP method that caused the preflight request.
- Changed the name to something shorter since it appears in the logging.
=> Use Access-Control-Allow-Method

docker/aarch64/sqlite/Dockerfile, docker/amd64/postgresql/Dockerfile, docker/amd64/postgresql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/sqlite/Dockerfile, docker/armv7/sqlite/Dockerfile, src/api/admin.rs
This is done to enable backup functionality in the admin interface while
we're waiting for the libsqlite-sys 0.17 to bubble up in the upstream
dependencies. Then we can start using `VACUUM INTO`
This also extends the check for the sqlite binary to also try `sqlite3`
as this is the name of the binary in baseimage distributions we use.
=> Add sqlite binary into the docker images

src/util.rs
All CORS header used to be added always even when that was not necessary.
Changed to only add Allow-Origin to all requests and move the others to preflight OPTIONS request.
Extension sends the request with `file://` Origin. This seems to cause problems.
If Origin is `file://` change it to the wildcard.
This seems to correspond with the responses from the official API.
Before merging
Fixes #629
=> Change CORS headers

src/api/icons.rs, src/config.rs, src/main.rs
- Blacklisting was not effective for redirects and rel href
- Able to blacklist non global IP's like RFC1918, multicast etc...
=> Updated icon blacklisting.

src/db/mod.rs
When a custom path is used the backup feature does not work.
Changed it so it will take the path of the sqlite file and use that.
=> Fixed a bug with the sqlite backup feature.

src/api/core/two_factor/email.rs, src/api/identity.rs
The 2FA email was not sent when email was the only 2FA method available.
Moved generate token, save token and send email logic to separate function.
Called from the separate `send-email-login` API call and when Email is the only 2FA provider in the `invalid grant` JsonError response.
Fixes #611
=> Fix 2FA email not sending

src/api/icons.rs, src/main.rs
When the icon_cache directory doesn't exists yet, and the first icon
catched is a miss this .miss file was not able to be created since the
directory was only created during a valid icon download.
=> Fixed issue #709 creating icon_cache directory.

.env.template, src/api/core/two_factor/authenticator.rs, src/config.rs
Added a config option to disable time drifted totp codes.
Default is false, since this is what the RFC recommends.
=> Fixed issue/request #705

src/static/global_domains.json
I added https://tv.apple.com/ to the global Apple domains. Its the website used to watch Apple TV+ series.
=> Added tv.apple.com to global domains

.env.template, src/api/core/accounts.rs, src/config.rs
This feature can be enabled by setting SIGNUPS_ALLOWED=false and
providing a comma-separated list of whitelisted domains in
SIGNUPS_DOMAINS_WHITELIST.
Fixes #727
=> Add the ability to disable signups, but allow signups from a whitelist

Cargo.lock, Cargo.toml, src/api/icons.rs
Some sites are using base64 encoded inline images for favicons.
This will try to match those with some sane checks and return that.
These icons will have lower prio then the icons with a normal URL.
=> Add an option to fetch and parse href="data:image"

docker/Dockerfile.j2, docker/Makefile, docker/aarch64/mysql/Dockerfile, docker/aarch64/sqlite/Dockerfile, docker/amd64/mysql/Dockerfile, docker/amd64/mysql/Dockerfile.alpine, docker/amd64/postgresql/Dockerfile, docker/amd64/postgresql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/mysql/Dockerfile, docker/armv6/sqlite/Dockerfile, docker/armv7/mysql/Dockerfile, docker/armv7/sqlite/Dockerfile, docker/render_template
No need to use two different base images. Debian buster is pulled later anyway so we can just use it for the vault stage as well.
My reason for this change is partly to avoid redundancy and partly to make it easier to build everything yourself. When all the build environment is based on Debian than you just have to figure out how to build a Debian Docker base image (ref: https://github.com/ypid/docker-makefile).
~~WIP: This PR is incomplete. I first wanted to check if this is acceptable two you because I put together a short script to replace this in all the Dockerfiles.~~
I assume the broken windows CI build is not my fault. Why support Windows anyway ;-)
=> Use Debian base image for all steps of the build process

src/db/models/two_factor.rs
Because of differences in how .on_conflict() works compared to .replace_into() the PostgreSQL backend wasn't correctly ensuring the unique constraint on user_uuid and atype wasn't getting violated.
This change simply issues a DELETE on the unique constraint prior to the insert to ensure uniqueness. PostgreSQL does not support multiple constraints in ON CONFLICT clauses.
Please let me know if you'd like to see any changes.
=> Fixes #635 - Unique constraint violation when using U2F tokens on PostgreSQL

src/config.rs
This reverts back to `SIGNUPS_ALLOWED` when there is no domain whitelist
set. The functionality was broken in 64d6f72.
=> SIGNUPS_ALLOWED with no whitelist [fixes #830]

src/api/admin.rs, src/db/models/user.rs
This was brought up today:
https://github.com/dani-garcia/bitwarden_rs/issues/752#issuecomment-586715073
I don't think it makes much sense in checking whether admin has the
right to send invitation as admin can change the setting anyway.
Removing the condition allows users to forbid regular users from
inviting new users to server while still preserving the option to do so
via the admin API.
=> Do not disable invitations via admin API

Cargo.lock, Cargo.toml, src/main.rs
I added help and version cli flags
Signed-off-by: zethra <benaagoldberg@gmail.com>
=> Added command line flags for help and version

src/mail.rs
If SSL is disabled, the SMTP `ClientSecurity` of the `lettre` crate defaults to `None`, that is, an insecure connection. 
This is changed to `Opportunistic`, which uses TLS if available. 
If TLS is not available, an insecure connection is used (i.e., this change is backward compatible).
=> Use opportunistic TLS in SMTP connections

docker/Dockerfile.j2, src/main.rs
Make openssl crate as default (non feature-flipped)
Make static build
=> Fix alpine build with openssl crate as default

src/main.rs
During migrations some queries are out of order regarding to foreign
keys.
Because of this the migrations fail when the sql database has this
enforced by default.
Turning of this check during the migrations will fix this and this is
only per session.
=> Fixing issue #759 by disabling Foreign Key Checks.

src/mail.rs
This breaks some setups with misconfigured TLS settings, reverting for now.
=> Revert "Use opportunistic TLS in SMTP connections"

src/auth.rs
The organization uuid is most of the time within the uri path as a
parameter. But sometimes it only is there as a query value.
This fix checks both, and returns the uuid when possible.
It also fixes the purge/delete functions within the org settings.
=> Fixed issue #908

src/api/identity.rs
Mobile push isn't currently supported, but this should get rid of spurious
`Detected unexpected parameter during login: devicepushtoken` warnings.
=> Handle `devicePushToken`

docker/Dockerfile.j2, docker/aarch64/mysql/Dockerfile, docker/aarch64/sqlite/Dockerfile, docker/amd64/mysql/Dockerfile, docker/amd64/mysql/Dockerfile.alpine, docker/amd64/postgresql/Dockerfile, docker/amd64/postgresql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/mysql/Dockerfile, docker/armv6/sqlite/Dockerfile, docker/armv7/mysql/Dockerfile, docker/armv7/sqlite/Dockerfile, docker/healthcheck.sh
* Switch healthcheck interval/timeout from 30s/3s to 60s/10s.
30s interval is arguably overkill, and 3s timeout is definitely too short
for lower end machines.
* Use HEALTHCHECK CMD exec form to avoid superfluous `sh` invocations.
* Add `--silent --show-error` flags to curl call to avoid progress meter being
shown in healthcheck logs.
=> Healthcheck fixes/optimizations

src/api/core/ciphers.rs
The config values (in KB) need to be converted to bytes when comparing
against total attachment sizes.
Fixes #937.
=> Fix attachment size limit calculation

src/api/admin.rs, src/config.rs
The admin page will still be disabled.
Fixes #849.
=> Warn on empty `ADMIN_TOKEN` instead of bailing out

src/db/models/attachment.rs, src/db/models/cipher.rs, src/db/models/device.rs, src/db/models/user.rs
PostgreSQL updates/inserts ignored None/null values.
This is nice for new entries, but not for updates.
Added derive option to allways add these none/null values for Option<>
variables.
This solves issue #965
=> Fixed issue #965

src/api/core/accounts.rs, src/api/core/organizations.rs, src/config.rs
* Make `SIGNUPS_DOMAINS_WHITELIST` override the `SIGNUPS_ALLOWED` setting.
Otherwise, a common pitfall is to set `SIGNUPS_DOMAINS_WHITELIST` without
realizing that `SIGNUPS_ALLOWED=false` must also be set.
* Whitespace is now accepted in `SIGNUPS_DOMAINS_WHITELIST`. That is,
`foo.com, bar.com` is now equivalent to `foo.com,bar.com`.
* Add validation on `SIGNUPS_DOMAINS_WHITELIST`. For example, `foo.com,`
is rejected as containing an empty token.
* Make org owner invitations respect the email domain whitelist.
This closes a loophole where org owners can invite new users from any domain.
=> Domain whitelist cleanup and fixes

src/api/admin.rs
This is technically required per RFC 2616 (HTTP/1.1); some proxies will
rewrite a plain `/admin` path to an unexpected URL otherwise.
=> Use absolute URIs for admin page redirects

src/static/scripts/bootstrap.css
The file bootstrap.css.map is missing, the reference can be deleted.
Or else you have to add the file.
=> Delete the call to the map file

src/util.rs
As discussed in the matrix chat, I fixed the rounding issue on arm by using format! to get a 2 digit precision
=> Use format! for rounding to fix arm issue

src/static/templates/email/invite_accepted.hbs, src/static/templates/email/invite_accepted.html.hbs, src/static/templates/email/invite_confirmed.hbs, src/static/templates/email/invite_confirmed.html.hbs, src/static/templates/email/new_device_logged_in.hbs, src/static/templates/email/new_device_logged_in.html.hbs, src/static/templates/email/send_org_invite.hbs, src/static/templates/email/send_org_invite.html.hbs
For example, this causes org names like `X&Y` to appear as `X&amp;Y`.
=> Don't HTML-escape email subject lines

src/api/admin.rs, src/db/models/attachment.rs, src/db/models/cipher.rs, src/db/models/organization.rs, src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
Added attachment info per user and some layout fix
Fixed an issue when DNS resolving fails.
In the event of a failed DNS Resolving checking for new versions will
cause a huge delay, and in the end a timeout when loading the page.
- Check if DNS resolving failed, if that is the case, do not check for
new versions
- Changed `fn get_github_api` to make use of structs
- Added a timeout of 10 seconds for the version check requests
- Moved the "Unknown" lables to the "Latest" lable
- Added the amount and size of the attachments per user
- Changed the items count function a bit
- Some small layout changes
Updated Organizations overview
- Changed HTML to match users overview
- Added User count
- Added Org cipher amount
- Added Attachment count and size
=> Admin interface

src/main.rs
For whatever reason this is still required in some situation to avoid openssl linking errors.
=> Add back openssl crate

src/config.rs
This PR adjusts the config validation so that `DATABASE_URL`s of the form `postgres://...` are valid when using the PostgreSQL database backend
=> Allow postgres:// in DATABASE_URL

docker/Dockerfile.j2, docker/aarch64/mysql/Dockerfile, docker/aarch64/sqlite/Dockerfile, docker/amd64/mysql/Dockerfile, docker/amd64/mysql/Dockerfile.alpine, docker/amd64/postgresql/Dockerfile, docker/amd64/postgresql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/mysql/Dockerfile, docker/armv6/sqlite/Dockerfile, docker/armv7/mysql/Dockerfile, docker/armv7/sqlite/Dockerfile, docker/start.sh
This is useful for making local customizations upon container start. To use
this feature, mount a script into the container as `/etc/bitwarden_rs.sh`
and/or a directory of scripts as `/etc/bitwarden_rs.d`. In the latter case,
only files with an `.sh` extension are sourced, so files with other
extensions (e.g., data/config files) can reside in the same dir.
Note that the init scripts are run each time the container starts (not just
the first time), so these scripts should be idempotent.
=> Add startup script to support init operations

Cargo.lock, Cargo.toml, src/api/identity.rs, src/mail.rs
In this implementation, the `TZ` environment variable must be set
in order for the formatted output to use a more user-friendly
time zone abbreviation (e.g., `UTC`). Otherwise, the output uses
the time zone's UTC offset (e.g., `+00:00`).
=> Use local time in email notifications for new device logins

src/util.rs
As of Rust 1.45.0, `strip_prefix()` is now stable.
=> Use `strip_prefix()` instead of `trim_start_matches()` as appropriate

hooks/push
=> Skip cleanup of `arm32v6` arch-specific tags

src/api/core/ciphers.rs
A soft-deleted entry should now show up in the trash folder immediately
(previously, an extra sync was required).
=> Fix soft delete notifications

src/static/global_domains.json, tools/global_domains.py
The script works by reading the relevant files from the upstream Bitwarden
source repo and generating a matching JSON file. It could potentially be
integrated into the build/release process, but for now it can be run manually
as needed.
=> Add a script to auto-generate the global equivalent domains JSON file

.env.template
Just a small attempt to make it more clear that the value of settings in the `.env` file may be ignored in some cases.
I'm not sure on the exact wording, please tell me if you have other suggestions :)
=> Add a note that settings in .env can be overridden

.env.template
Note that Diesel implements its own parser for MySQL connection URIs, so it
probably doesn't accept the full range of syntax that would be accepted by
MySQL's client libraries, whereas for PostgreSQL, Diesel simply passes the
connection string/URI to PostgreSQL's libpq for processing.
=> Add more doc comments for MySQL/PostgreSQL connection URIs

migrations/mysql/2020-08-02-025025_add_favorites_table/down.sql, migrations/mysql/2020-08-02-025025_add_favorites_table/up.sql, migrations/postgresql/2020-08-02-025025_add_favorites_table/down.sql, migrations/postgresql/2020-08-02-025025_add_favorites_table/up.sql, migrations/sqlite/2020-08-02-025025_add_favorites_table/down.sql, migrations/sqlite/2020-08-02-025025_add_favorites_table/up.sql, src/api/core/ciphers.rs, src/db/models/cipher.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs, src/main.rs
Currently, favorites are tracked at the cipher level. For org-owned ciphers,
this means that if one user sets it as a favorite, it automatically becomes a
favorite for all other users that the cipher has been shared with.
Fixes #885.
=> Track favorites on a per-user basis

src/db/models/cipher.rs, src/db/models/favorite.rs, src/db/models/mod.rs, src/db/models/user.rs
This prevents foreign key constraint violations.
=> Delete associated favorites when deleting a cipher or user

src/api/notifications.rs
The type of the field "headers" in MsgPack structure seems to be a Map instead of an Array.
This cause crashes with the package SignalR C# client, but not with the Typescript one used by desktop/browser clients.
The package SignalR is also checking if the client is a browser, and will set a header value or a query parameter according the case ([see here](https://github.com/dotnet/aspnetcore/blob/7a65454466e0f17b7879794205e3887471f5839e/src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/WebSocketsTransport.cs#L127)).
So, a dedicated function to resolve any of them seemed better.
Now notifications should works with any SignalR/MsgPack packages, i'm needing this to continue to implement notifications on mobile app.
Thanks @BlackDex for helping about research and for the code …
=> Fixing MsgPack headers type and support mobile SignalR

src/api/core/ciphers.rs, src/db/models/cipher.rs, src/db/models/collection.rs
If org owners/admins set their org access to only include selected
collections, then ciphers from non-selected collections shouldn't
appear in "My Vault". This matches the upstream behavior.
Fixes #1123.
=> Hide ciphers from non-selected collections for org owners/admins

.env.template, src/config.rs, src/mail.rs
- Allow all SMTP Auth meganisms supported by Lettre.
- The config value order is leading and values can be separated by a
comma ','
- Case doesn't matter, and invalid values are ignored.
- Warning is printed when no valid value is found at all.
=> Allow multiple SMTP Auth meganisms.

src/error.rs, src/mail.rs
Currently when for example using the admin interface to send out a test e-mail just
returns `SmtpError`. This is not very helpful. What i have done.
- Match some common Lettre errors to return the error message.
- Other errors will just be passed on as before.
Some small other changes:
- Fixed a clippy warning about using clone().
- Fixed a typo where Lettere was spelled with one t.
=> Format some common Lettre errors a bit simpler

src/api/core/accounts.rs
If for some reason the hashed password is cleared from memory within a
bitwarden client it will try to verify the password at the server side.
This endpoint was missing.
Resolves #1156
=> Add /api/accounts/verify-password endpoint

Cargo.lock, Cargo.toml
This feature enables the `vendored` feature from the `openssl` crate and build a statically linked version of openssl.
With this feature, I am able to build a fully static binary with [cross](https://github.com/rust-embedded/cross):
```
cross +nightly build --target x86_64-unknown-linux-musl --features "vendored_openssl sqlite" --release
```
=> Add `vendored_openssl` feature.

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/arm32v6/Dockerfile, docker/arm32v7/Dockerfile, docker/arm32v7/Dockerfile.alpine, docker/arm64v8/Dockerfile, hooks/arches.sh
With some apt/dpkg magic building multidb containers for arm versions
now also works. As long as the build stage and docker-image stage use
the same base (debian buster now) it should all work.
Resolves #530, resolves #1066
=> Fixed building mysql, postgresql and sqlite3 for arm

docker/Dockerfile.j2, docker/arm32v7/Dockerfile.alpine
The runtime image was using a very old Alpine version.
This caused issues with the catatonit install
Now using the Balena armv7hf Alpine image for this.
=> Fixed issue with building Alpine armv7 image.

.env.template, src/config.rs, src/db/mod.rs
Tiny change to allow the database connection pool size to be configured externally (useful for those of us deploying to databases with limited connection count allowances)
=> Add DATABASE_MAX_CONNS config setting

azure-pipelines.yml
Updated the azure-pipelines.yml to build multidb now.
- Updated to Ubuntu 18.04 (Closer matches the docker builds)
- Added some really needed apt packages to be sure that they are
installed
- Now run cargo test using all database backeds in one go.
=> Updated the azure-pipelines.yml for multidb

src/db/models/org_policy.rs
While this patch (which is based on src/db/models/collection.rs's find_by_user_uuid) was initially to fix #1218, you already pushed https://github.com/dani-garcia/bitwarden_rs/commit/013d4c28b2e06dc654b7f2a1f21b56b1c8a7838d just as I was making the PR.
There's however one case that doesn't seem to account that is fixed by this PR: User B (owner of Org A) can invite User A to Org A, and even if User A doesn't accept this invitation, the policies will be applied to them:
I've tested this behavior with and without this patch, verified that that behavior happens, and that this PR resolves that issue.
=> Ensure that a user is actually in an org when applying policies

src/error.rs
Fixes #1233.
This change makes the `err!()` macro to log the namespace it was called from instead of `bitwarden_rs::error`.
I did my best to test a few error cases, however it might have some unintended side effects to error logging. Please let me know if it's broken.
=> Log proper namespace in the err!() macro

src/util.rs
Fixes #1194.
This is a better implementation of the change previously posted in #1235.
This change allows the user to read configuration variable values from arbitrary files by using the `_FILE` suffix in environment variables.
=> Read config vars from files

src/api/admin.rs, src/db/models/device.rs, src/db/models/user.rs, src/static/templates/admin/users.hbs
Feature request from #246.
This change implements saving last login date and time for users to the database and adds this information to the admin panel's user list. I also added the user creation date to the admin page.
=> Show last active it on admin users page

src/api/core/organizations.rs, src/auth.rs
This has been requested a few times (#1136 & #246 & forum), and there already were two
(1:1 duplicate) PR's (#1222 & #1223) which needed some changes and no
followups or further comments unfortunally.
This PR adds two auth headers.
- ManagerHeaders
Checks if the user-type is Manager or higher and if the manager is
part of that collection or not.
- ManagerHeadersLoose
Check if the user-type is Manager or higher, but does not check if the
user is part of the collection, needed for a few features like
retreiving all the users of an org.
I think this is the safest way to implement this instead of having to
check this within every function which needs this manually.
Also some extra checks if a manager has access to all collections or
just a selection.
fixes #1136
=> Adding Manager Role support

.env.template, src/api/icons.rs, src/config.rs, src/main.rs
- Added more checks to prevent panics (Removed unwrap)
- Try do download from base domain or add www when the provided domain
fails
- Added some more domain validation checks to prevent errors
- Added the ICON_BLACKLIST_REGEX to a Lazy Static HashMap which
speeds-up the checks!
- Validate the Regex before starting/config change.
- Some cleanups
- Disabled some noisy debugging from 2 crates.
=> Updated icon downloading.

src/api/icons.rs
- Changed the user-agent, which caused at least one site to stall the
connection (Same happens on icons.bitwarden.com)
- Added default_header creation to the lazy static CLIENT
- Added referer passing, which is checked by some sites
- Some small other changes
=> Small update on favicon downloading

src/api/admin.rs, src/mail.rs, src/static/templates/admin/diagnostics.hbs, src/util.rs
* For clarity, add `UTC` suffix for datetimes in the `Diagnostics` admin tab.
* Format datetimes in the local timezone in the `Users` admin tab.
* Refactor some datetime code and add doc comments.
=> Clean up datetime output and code

migrations/mysql/2020-12-09-173101_add_stamp_exception/up.sql, migrations/postgresql/2020-12-09-173101_add_stamp_exception/up.sql, migrations/sqlite/2020-12-09-173101_add_stamp_exception/up.sql, src/api/core/accounts.rs, src/auth.rs, src/db/models/mod.rs, src/db/models/user.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
When ticking the 'Also rotate my account's encryption key' box, the key
rotated ciphers are posted after the change of password.
During the password change the security stamp was reseted which made
the posted key's return an invalid auth. This reset is needed to prevent other clients from still being able to read/write.
This fixes this by adding a new database column which stores a stamp exception which includes the allowed route and the current security stamp before it gets reseted.
When the security stamp check fails it will check if there is a stamp exception and tries to match the route and security stamp.
Currently it only allows for one exception. But if needed we could expand it by using a `Vec<UserStampException>` and change the functions accordingly.
fixes #1240
=> Fix Key Rotation during password change.

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/arm64/Dockerfile, docker/armv6/Dockerfile, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine
**Description of the change**
@mfriedenhagen pointed at an init process in this issue here: https://github.com/dani-garcia/bitwarden_rs/issues/905#issuecomment-753454442
First I thought that this would not help, since Rocket does not explicitly handly any signal sent to it. But it seems that adding an init process like `dumb-init` still improves the shutdown behavior. According to the [documentation](https://github.com/Yelp/dumb-init/blob/master/README.md) of dumb-init this might be the reason why:
> The Linux kernel applies special signal handling to processes which run as PID 1.
**Benefits**
Especially running bitwarden inside kubernetes resulted, that evicting a node which runs bitwarden takes a long time becase we need to wait until kublet kills bitwarden hardly. With this …
=> Improve shutdown behavior (on kubernetes and allow CTRL+C)

src/auth.rs
The implementation of the `Manager` user type (#1242) introduced a regression
whereby owner/admin users are incorrectly denied access to certain collection
APIs if their access control for collections isn't set to "access all".
Owner/admin users should always have full access to collection APIs, per
https://bitwarden.com/help/article/user-types-access-control/#access-control:
> Assigning Admins and Owners to Collections via Access Control will only
> impact which Collections appear readily in the Filters section of their
> Vault. Admins and Owners will always be able to access "un-assigned"
> Collections via the Organization view.
Fixes #1307.
=> Fix collection access issues for owner/admin users

src/util.rs
The `twofactorauth.org` domain has apparently been sold to some company for marketing purposes.
This is related to upstream web vault changes picked up in dani-garcia/bw_web_builds#31.
=> Change `twofactorauth.org` to `2fa.directory`

src/api/admin.rs, src/main.rs, src/util.rs
Currently, when starting up for the first time (running standalone, outside of Docker), bitwarden_rs panics when the `openssl` tool isn't able to create `data/rsa_key.pem` due to the `data` dir not existing:
```
[2021-02-26 18:35:01.596][bitwarden_rs][INFO] JWT keys don't exist, checking if OpenSSL is available...
OpenSSL 1.1.1f  31 Mar 2020
[2021-02-26 18:35:01.604][bitwarden_rs][INFO] OpenSSL detected, creating keys...
genrsa: Can't open "data/rsa_key.pem" for writing, No such file or directory
Can't open data/rsa_key.pem for reading, No such file or directory
140549065942336:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('da
ta/rsa_key.pem','r')
140549065942336:error:2006D080:BIO routines:BIO_new_file:no such …
```
=> Check for data folder on startup

src/api/core/organizations.rs
The org name in the invitation email was made customizable in 8867626, but
the org name is still hardcoded as "bitwarden_rs" in the confirmation email.
=> Fix custom org name in invitation confirmation email

docker/Makefile
Add a dot indicting current directory to search by find. 
find in mac won't work without the dot
=> Add a dot in find command.

src/api/core/sends.rs
Adjust checks for max access count, expiration date, and deletion date.
The date checks aren't that important, but the access count check
currently allows one more access than it should.
=> Send access check fixes

src/api/icons.rs, src/util.rs
Cache icons on the client too, to reduce requests when loading the homepage.
Caching without `immutable` will still issue requests, and because Rocket doesn't support conditional GETs, it's basically like not caching at all.
This also caches vault static files, which are cachebusted anyway so updates will still work fine. I've not changed the `/` route for this reason.
Bitwarden upstream doesn't do these, but they also use cloudflare for a CDN which makes this far less of an issue. For home users who don't use a global CDN, this should make quite a difference!
=> Client caching

.gitattributes
Nothing else in `src/static` is vendored external scripts, so just ignore these.
This also fixes the glob, which previously wasn't matching anything
=> Just ignore scripts

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/arm64/Dockerfile, docker/armv6/Dockerfile, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, src/api/admin.rs, src/db/mod.rs, src/static/templates/admin/diagnostics.hbs
- Fixed bug when web-vault is disabled.
- Updated sql-server version check to be simpler thx to @weiznich ( https://github.com/dani-garcia/bitwarden_rs/pull/1548#discussion_r604767196 )
- Use `VACUUM INTO` to create a SQLite backup instead of using the external sqlite3 application.
- This also removes the dependancy of having the sqlite3 packages installed on the final image unnecessary, and thus removed it.
- Updated backup filename to also have the current time.
- Add specific bitwarden_rs web-vault version check (to match letter patched versions)
Will work when https://github.com/dani-garcia/bw_web_builds/pull/33 is build (But still works without it also).
=> Some admin interface updates.

.env.template, Cargo.lock, Cargo.toml, src/api/core/ciphers.rs, src/api/core/mod.rs, src/api/core/sends.rs, src/api/mod.rs, src/config.rs, src/db/models/cipher.rs, src/db/models/send.rs, src/main.rs
Upstream will soon auto-delete trashed items after 30 days, but some people use the trash as an archive folder, so to avoid unexpected data loss, this implementation requires the user to explicitly enable auto-deletion.
This PR also adds a generic job scheduler, and rewrites deletion of old sends to use it.
=> Add support for auto-deleting trashed items

Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/core/mod.rs, src/api/core/two_factor/duo.rs, src/api/icons.rs, src/util.rs
This allows a couple things:
- Outbound request code is now more consistent, and clients are constructed in the same place (icons is _slightly_ different, but might fix that too)
- Outbound requests can be forwarded through a proxy, to hide the location of their server. Because the icons API is unauthenticated, anyone can force Bitwarden_RS to make a request.
=> Allow outbound requests to go via a proxy

src/api/admin.rs
```
Instead of having the caller dig through /admin/users for the right one,
just return the user upon creation.
```
=> admin: Return newly-created user in invite_user

src/api/admin.rs, src/error.rs
Based on: #1663
```
admin: Specifically return 404 for user not found
- Modify err_code to accept an expr for err_code
- Add get_user_or_404, properly returning 404 instead of a generic 400
for cases where user is not found
- Use get_user_or_404 where appropriate.
```
```
admin: Make invite_user error codes more specific
- Return 409 Conflict for when a user with that email already exists
- Return 500 InternalServerError for everything else
```
=> admin: More granular HTTP return codes for user-related endpoints

.env.template, src/api/core/sends.rs, src/config.rs
This provides global control over whether users can create Bitwarden Sends.
=> Add `sends_allowed` config setting

migrations/mysql/2021-05-11-205202_add_hide_email/up.sql, migrations/postgresql/2021-05-11-205202_add_hide_email/up.sql, migrations/sqlite/2021-05-11-205202_add_hide_email/up.sql, src/api/core/sends.rs, src/db/models/org_policy.rs, src/db/models/send.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
Note: The original Vaultwarden implementation of Bitwarden Send would always
hide the email address, while the upstream implementation would always show it.
Also, add support for the `Send Options` policy.
Upstream refs:
* https://github.com/bitwarden/server/pull/1234
* https://bitwarden.com/help/article/policies/#send-options
=> Add support for hiding the sender's email address in Bitwarden Sends

src/api/admin.rs, src/api/core/ciphers.rs, src/api/web.rs
Upstream switched to new upload/download APIs. Uploads fall back to the
legacy APIs for now, but not downloads apparently.
Fixes #1697.
Upstream PR: https://github.com/bitwarden/server/pull/1153
=> Fix attachment downloads

src/api/core/ciphers.rs, src/api/core/sends.rs, src/crypto.rs, src/db/models/attachment.rs
Upstream PR: https://github.com/bitwarden/server/pull/1229
The legacy upload flow can be tested with v2.19 of the web vault.
The v2 upload flow can be tested with v2.20 of the web vault.
=> Add support for v2 attachment upload APIs

src/api/core/ciphers.rs
When creating a new cipher, the mobile clients seem to set this field to an
invalid value, which causes a warning to be logged:
Error parsing LastKnownRevisionDate '0001-01-01T00:00:00': premature end of input
Avoid this by dropping the `LastKnownRevisionDate` field on cipher creation.
=> Avoid `Error parsing LastKnownRevisionDate` warning for mobile clients

Cargo.lock, Cargo.toml
- Updated webauthn-rs commit hash which resolves #1796
=> Fixes issue with multiple security keys.

docker/Dockerfile.j2, docker/armv7/Dockerfile.alpine
The `messense/rust-musl-cross` has removed OpenSSL in favor of the
vendored option. Enabled vendored openssl to resolve this.
Resolves #1807
=> Fix armv7 alpine build.

.pre-commit-config.yaml
There is a nice tool called pre-commit: https://pre-commit.com/
It can run actions prior to a commit to validate everything is working.
People can choose to enable this for them selfs, but it would be nice to have a base config by default.
=> Adding pre-commit config

.env.template, src/api/core/ciphers.rs, src/api/core/sends.rs, src/config.rs
The user and org attachment limit use `size` as wording while it should
have been `storage` since it isn't per attachment, but the sum of all attachments.
- Changed the wording in the config/env
- Changed the wording of the error messages.
Resolves #1818
=> Updated attachment limit descriptions

src/util.rs
Edge's frame-ancestors are required for Edge extension to do WebAuthn.
=> Add Edge's frame-ancestors

.env.template, src/api/core/accounts.rs, src/config.rs
* Disable `show_password_hint` by default.
A setting that provides unauthenticated access to potentially sensitive data    shouldn't be enabled by default.
*  Prevent user enumeration via password hints
When `show_password_hint` is enabled but mail is not configured, the previous implementation returned a differentiable response for non-existent email addresses.
Even if mail is enabled, there is a timing side channel since mail is sent synchronously. Add a randomized sleep to mitigate this somewhat.
=> Password hint enhancements

Cargo.lock, Cargo.toml, src/api/core/two_factor/webauthn.rs, src/api/notifications.rs
- Updated some packages
- Updated code related to package updates.
- Disabled User Verification enforcement when WebAuthn Key sends UV=1
This makes it compatible with upstream and resolves #1840
- Fixed a bug where removing an individual WebAuthn key deleted the wrong key.
=> Fix WebAuthn issues and some small updates

src/api/core/sends.rs, src/api/notifications.rs, src/db/models/send.rs
This small pull request fixes the notification format for `SyncSendCreate`, `SyncSendUpdate` and `SyncSendDelete`notification types.
With the correct notification format, the sends in the web vault and other bitwarden clients are automatically updated when the user creates, updates or deletes a send in another session. To allow the clients to update specific sends, this PR also includes new endpoints for getting all sends or one specific send by uuid.
I've verified that this works with the web vault and the bitwarden mobile client.
=> Fix sends notification format and add endpoints to get all sends or one send by id

docker/Dockerfile.j2, docker/amd64/Dockerfile.alpine, docker/armv7/Dockerfile.alpine
To be able to set a timezone inside a Alpine container with the env variable TZ the tzdata package is needed. Otherwise only UTC will be set. In my case fail2ban (which is running on the host with Europe/Berlin) is complaining about a too large time deviation.
=> Adding tzdata to Alpine container

src/api/core/ciphers.rs, src/db/models/attachment.rs
This check is several years old, so maybe there was a valid reason for having it before, but it's not correct anymore.
Fixes #1909.
=> Fix limitation on sharing ciphers with attachments

src/db/models/organization.rs, src/db/models/user.rs
Syncing with the latest desktop client (v1.28.0) fails because it expects some json key/values to be there.
This PR adds those key/value pairs.
Resolves #1924
=> Fix syncing with Bitwarden Desktop v1.28.0

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, hooks/push
Since docker hub stopped Autobuild, we need to switch to something else.
This will trigger building of images on Github Actions and pushes them
to Docker Hub.
You only need to add 3 secrets before you merge this PR to have it working directly.
- DOCKERHUB_USERNAME : The username of the account you are going to push the builds to
- DOCKERHUB_TOKEN : The token needed to login and push builds
- DOCKERHUB_REPO : The repo name in the following form `index.docker.io/<user>/<repo>`
So for vaultwarden that would be `index.docker.io/vaultwarden/server`
=> Build Docker Hub images via Github Actions

src/api/core/two_factor/webauthn.rs
This mainly affects users running Vaultwarden under a subpath.
Refs:
* https://github.com/kanidm/webauthn-rs/blob/b2cbb34/src/core.rs#L941-L948
* https://github.com/kanidm/webauthn-rs/blob/b2cbb34/src/core.rs#L316
* https://w3c.github.io/webauthn/#dictionary-client-data
=> Fix incorrect WebAuthn origin

src/api/admin.rs, src/api/core/accounts.rs, src/api/core/organizations.rs, src/db/models/user.rs
In the case when SMTP is disabled and.
when inviting new users either via the admin interface or into an
organization and using uppercase letters, this would fail for those
users to be able to register since the checks which were done are
case-sensitive and never matched.
This PR fixes that issue by ensuring everything is lowercase.
Fixes #1963
=> Fix issue when using uppercase chars in emails

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, docker/Dockerfile.j2, docker/Makefile, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile.buildx, docker/armv6/Dockerfile, docker/armv6/Dockerfile.buildx, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine, hooks/build, hooks/push
- Split Debian and Alpine into different build matrix
This starts building both Debian and Alpine based images at the same time
- Make use of Docker BuildKit, which improves speed also.
- Use BuildKit caching for Rust Cargo across docker images.
This prevents downloading the same crates multiple times.
- Use Github Actions Services to start a docker registry, starting it
via the build script sometimes caused issues.
- Updated the Build workflow to use Ubuntu 20.04 which is more close to
the Bullseye Debian release regarding package versions.
As a side-note, i also tried adding the apt files to the cache, it did not cause any change into the build-time (both local and on GHA) so to have less complexity i did not add it.
=> Optimize release workflow.

src/api/core/organizations.rs
Boolean-toggle enterprise policies (like 'Two-Step Login' and 'Personal Ownership') don't provide a data attribute in the new version of the web client. This updates the backend to expect these to be optional.
Web change introduced in https://github.com/bitwarden/web/pull/1147 which added https://github.com/bitwarden/web/blob/2cbe023a38792ff70a2a4907f4748354bb4e0573/src/app/organizations/policies/base-policy.component.ts#L48-L50
=> fix: Support no-data enterprise policies

Cargo.toml, src/api/icons.rs, src/error.rs
- Unicode websites could break (www.post.japanpost.jp for example).
regex would fail because it was missing the unicode-perl feature.
- Be less verbose in logging with icon downloads
- Removed duplicate info/error messages
- Added err_silent! macro to help with the less verbose error/info messages.
=> Updated icon downloading

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.buildx, docker/arm64/Dockerfile, docker/arm64/Dockerfile.buildx, docker/armv6/Dockerfile, docker/armv6/Dockerfile.buildx, docker/armv7/Dockerfile, docker/armv7/Dockerfile.buildx
This fixes #1998 where with some checking it seems Bullseye has some
issues with the glibc sleep call. It returns a SIGILL.
The glibc on Buster doesn't seem to have this issue, so revert back for
now until a fix has been released.
=> Revert Debian images back to Buster.

src/db/models/cipher.rs
For one of these flags to be in effect for a cipher, upstream requires all of
(rather than any of) the collections the cipher is in to have that flag set.
Also, some of the logic for loading access restrictions was wrong. I think
that only malicious clients that also had knowledge of the UUIDs of ciphers
they didn't have access to would have been able to take advantage of that.
Fixes #2072.
=> Fix conflict resolution logic for `read_only` and `hide_passwords` flags

src/api/core/emergency_access.rs
Rejecting an emergency access request should transition the grantor/grantee
relationship back into the `Confirmed` state, and the grantor's encrypted key
should remain in escrow rather than being cleared, or else future emergency
access requsts from that grantee will fail.
This probably fixes #2061.
=> Fix missing encrypted key after emergency access reject

migrations/postgresql/2021-10-24-164321_add_2fa_incomplete/up.sql
The PostgreSQL migration should have used `TIMESTAMP` rather than `DATETIME`.
Fixes #2079.
=> Fix PostgreSQL migration

Cargo.lock, Cargo.toml, src/api/admin.rs, src/main.rs, src/static/scripts/bootstrap-native.js, src/static/scripts/bootstrap.css, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/admin/diagnostics.hbs
- Enabled trust-dns feature which seems to help a bit when DNS is
causing long timeouts. Though in the blocking version it is less visible
then on the async branch.
- Removed some redundant code
- Updated javascript/css libraries
Resolves #2118
Resolves #2119
=> Enabled trust-dns and some updates.

.env.template, src/api/icons.rs, src/config.rs
If an external icon service is configured, icon requests return an HTTP redirect to the corresponding icon at the external service.
An external service may be useful for various reasons, such as if:
* The Vaultwarden instance has no external network connectivity.
* The Vaultwarden instance has trouble handling large bursts of icon requests.
* There are concerns that an attacker may probe the instance to try to detect whether icons for certain sites have been cached, which would suggest that the instance contains entries for those sites.
* The external icon service does a better job of providing icons than the built-in fetcher.
=> Add support for external icon services

src/api/icons.rs
As requested in #2136, some small changes on the type of log messages
and wording used.
Resolves #2136
=> Small changes to icon log messages.

.env.template, Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/identity.rs, src/config.rs, src/main.rs, src/ratelimit.rs
Might need to adjust the default rate limiting values and explain their use better.
Also needs to document their use in the .env template.
=> Basic ratelimit for user login (including 2FA) and admin login

.env.template, src/api/icons.rs, src/config.rs
The default code is 307 (temporary) to make it easier to test different icon services, but once a service has been decided on, users should ideally switch to using permanent redirects for cacheability.
=> Add config option to set the HTTP redirect code for external icons

src/api/core/emergency_access.rs
For emergency access invitations we need to check if invites are
allowed, not if sign-ups are allowed.
Resolves #2154
=> Fixed issue #2154

src/api/core/sends.rs
The CLI seems to send a String instead of an Integer for the maximum access count.
It now accepts both types and converts it to an i32 in all cases.
Fixes #2196
=> Fix issue with Bitwarden CLI.

src/api/core/accounts.rs
If a new user gets invited it should check if the user is invited via
emergency access, if so, allow that user to register.
=> Fix emergency access invites for new users

.env.template, src/api/icons.rs, src/config.rs
At least on Android, it seems the Bitwarden mobile client responds to
HTTP 307, but not to HTTP 308 for some reason.
=> Add support for legacy HTTP 301/302 redirects for external icons

src/util.rs
Convert old, [soon to be defunct](https://w3c.github.io/webappsec-permissions-policy/), Feature-Policy with its replacement Permissions-Policy
=> Upgrade Feature-Policy to Permissions-Policy

migrations/mysql/2022-01-17-234911_add_api_key/up.sql, migrations/postgresql/2022-01-17-234911_add_api_key/up.sql, migrations/sqlite/2022-01-17-234911_add_api_key/up.sql, src/api/core/accounts.rs, src/api/identity.rs, src/crypto.rs, src/db/models/device.rs, src/db/models/user.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
This is mainly useful for CLI-based login automation.
Upstream PR: https://github.com/bitwarden/server/pull/981
Upstream docs: https://bitwarden.com/help/personal-api-key/
=> Add support for API keys

.env.template, src/api/core/accounts.rs, src/api/core/two_factor/email.rs, src/config.rs, src/crypto.rs
The current limit of 19 is an artifact of the implementation, which can be
easily rewritten in terms of a more general string generation function.
The new limit is 255 (max value of a `u8`); using a larger type would
probably be overkill.
=> Increase length limit for email token generation

src/api/core/sends.rs
What it says on the tin, the messages will now include the IP of the request originator:
```
2022-02-13 13:29:17 | [2022-02-13 13:29:17.923][vaultwarden::api::core::sends][ERROR] Invalid password. IP: 192.168.1.246.
2022-02-13 13:29:05 | [2022-02-13 13:29:05.839][vaultwarden::api::core::sends][ERROR] Password not provided. IP: 192.168.1.246.
```
I have implemented this because I wanted fail2ban to also guard against trying to bruteforce Send password.
=> Add IP address to missing/invalid password message for Sends

.env.template, src/config.rs
Hi! I'm working on packaging this for Void, and in writing the runit service, I came across an annoyance: since the `.env` file can't be in the current working directory, it won't find it and thus has to read from the environment variables directly. This *can* be done with something like:
```
#!/bin/sh
exec chpst -u _vaultwarden:_vaultwarden \
env $(grep -v '^#' ${ENV_FILE:-/etc/vaultwarden.env} | xargs -d '\n') vaultwarden
```
But that is less than ideal IMO. This patch is a simple way to pass a single custom location where the env/config can be found.
=> Add support for custom .env file path

Cargo.lock, Cargo.toml, migrations/mysql/2022-03-02-210038_update_devices_primary_key/up.sql, migrations/postgresql/2022-03-02-210038_update_devices_primary_key/up.sql, migrations/sqlite/2022-03-02-210038_update_devices_primary_key/up.sql, src/api/identity.rs, src/auth.rs, src/db/models/device.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
- Updated jsonwebtoken to latest version
- Trim `username` received from the login form ( Fixes https://github.com/dani-garcia/vaultwarden/issues/2348 )
- Make uuid and user_uuid a combined primary key for the devices table ( Fixes https://github.com/dani-garcia/vaultwarden/issues/2295 )
- Updated crates including regex which contains a CVE ( https://blog.rust-lang.org/2022/03/08/cve-2022-24713.html )
=> Update login API code and update crates to fix CVE

.github/workflows/build.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine, src/api/core/accounts.rs, src/api/core/mod.rs, src/api/identity.rs, src/config.rs, src/main.rs, src/util.rs
- Removed all `thread::sleep` and use `tokio::time::sleep` now.
This solves an issue with updating to Bullseye ( Resolves #1998 )
- Updated all Debian images to Bullseye
- Added MiMalloc feature and enabled it by default for Alpine based images
This increases performance for the Alpine images because the default
memory allocator for MUSL based binaries isn't that fast
- Updated `dotenv` to `dotenvy` a maintained and updated fork
- Fixed an issue with a newer jslib (not fully released yet)
That version uses a different endpoint for `prelogin` Resolves #2378 )
=> Several updates and fixes

src/util.rs
Obsolete in modern browsers, unsafe, and largely replaced by CSP.
- [XS-Leak attacks](https://github.com/xsleaks/xsleaks/wiki/Links#annex-xss-filters-information-leaks)
- Removal of XSS auditor in [Chrome](https://chromestatus.com/feature/5021976655560704), [Edge ](https://blogs.windows.com/windows-insider/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/) and [Safari](https://bugs.webkit.org/show_bug.cgi?id=230499)
Since there are still [a few browsers using it](https://caniuse.com/mdn-http_headers_x-xss-protection), we should explicitly disable it for now to be on the safe side.
=> disable legacy X-XSS-Protection feature

docker/Dockerfile.j2, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx.alpine
The armv6 builds need a specific location for the libatomic.a file.
This commit fixes that by adding a RUSTFLAGS argument for this.
Also removed the `link-arg=-s` since this is now already done during via the release profile
And removed the CFLAGS for armv7, this is already fixed by default in the blackdex/rust-musl images.
=> Fix building mimalloc on armv6

src/api/core/mod.rs, src/api/web.rs
The added endpoints work the same as in their upstream implementations.
Upstream also implements `/api/ip`. This seems to include the server's public
IP address (the one that should be hidden behind Cloudflare), which doesn't
seem like a great idea.
=> Add `/api/{alive,now,version}` endpoints

.env.template, src/config.rs, src/db/mod.rs
Adds support for database connection init statements. This is probably mainly useful for running connection-scoped pragma statements.
Also adds default connection-scoped pragmas for SQLite:
* [`PRAGMA busy_timeout = 5000`](https://www.sqlite.org/pragma.html#pragma_busy_timeout) tells SQLite to keep trying for up to 5000 ms when there is lock contention, rather than aborting immediately. This should hopefully prevent the vast majority of "database is locked" panics observed since the async transition, e.g.: #2436
* [`PRAGMA synchronous = NORMAL`](https://www.sqlite.org/pragma.html#pragma_synchronous) trades better performance for a small potential loss in durability (the default is `FULL`). The SQLite docs recommend `NORMAL` as "a good choice for most applications running in WAL mode".
=> Database connection init

src/main.rs
The limits for uploading files were to small in regards to the allowed
maximum filesize of the Bitwarden clients including the web-vault.
Changed both `data-form` (used for Send) and `file` (used for
attachments) to be 525MB, this is the same size we already check our selfs.
Also changed the `json` limit to be 20MB, this should allow very large
imports with 4000/5000+ items depending on if there are large notes or not.
And, also disabled Rocket from outputting colors, these colors were also
send to the log files and syslog. I think this changed in Rocket 0.5rc
somewhere, need to look a bit further into that maybe.
=> Fix upload limits and disable color logs

.github/workflows/build.yml, docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine
Updated Rust from v1.60 to v1.61 for building the images.
Also made the rust version fixed for the Alpine build images to prevent
those images being build with a newer version when released.
=> Update Rust version in Dockerfile

.env.template
The TMP_FOLDER env variable is missing in .env.template.
=> Add TMP_FOLDER to .env.template

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine
It seemed there were some issues building the cross-platform images.
This PR fixes #2501 so building the containers will work again.
=> Fix persistent volume check

src/api/admin.rs
Adding "UserEnabled"  and "CreatedAt" member to the json output of a User in the `admin/users` and `admin/users/<ID>` web routes.
=> Adding "UserEnabled" and "CreatedAt" member to the json output of a User

Cargo.lock, Cargo.toml
Fixes the last remaining header encoding issues
Diff: https://github.com/lettre/lettre/compare/v0.10.0-rc.6...v0.10.0-rc.7
=> Bump lettre to 0.10.0-rc.7

Cargo.lock, Cargo.toml, src/mail.rs
Changes building `Address` by going through the `FromStr` implementation. Also removes the manual `MultiPart` build implementation, which must have been a workaround for a bug in a previous version.
Depends on #2531
=> Small email sending code improvements

src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/mod.rs, src/api/core/organizations.rs
This PR fixes #2566
If Organizational syncs returned a FolderId it would cause the web-vault
to hide the cipher because there is a FolderId set. Upstream seems to
not return FolderId and Favorite. When set to null/false it will behave
the same.
In this PR I have added a new CipherSyncType enum to select which type
of sync to execute, and return an empty list for both Folders and Favorites if this is for Orgs.
This also reduces the database load a bit since it will not execute those queries.
=> Fix hidden ciphers within organizational view.

Cargo.lock, Cargo.toml, src/api/icons.rs
- Updated dependencies 
* html5gum for favicon downloading
* openssl (latest patch 1.1.1p),
* time
* jsonwebtoken
* r2d2 (removes 2 older crate versions from the dep-tree)
The FaviconEmitter now only emits tokens which needs to be parsed, all others are
being skipped. This prevents unneeded items within the for-loop from being parsed.
=> Update dep's and small improvements on favicons

src/main.rs
Regarding some recent issues with sending attachments, but previously
also some changes to the API for example which could cause a `400` error
it just returned that there is something wrong, but not to much details
on what exactly.
To help with getting a bit more detailed information, we should set the
log-level for `_` to at least `Warn`.
=> Small change in log-level for better debugging

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine
Looks like it mainly just affects documentation of process, but it did result in some of the files having 'vv2022.5.02' in them. 
Any idea when the new vault will be merged to production/latest?
=> Address inconsistency v{version} with and without a v in the version with most recent updates. 

src/api/core/ciphers.rs, src/api/core/sends.rs, src/config.rs
This is to support scenarios where the attachments and sends folder are to be stored on a separate device from the tmp_folder (i.e. fuse-mounted S3 storage), due to having the tmp_dir on the same device being undesirable.
Example being fuse-mounted S3 storage with the reasoning that because S3 basically requires a copy+delete operations to rename files, it's inefficient to rename files on device, if it's even allowed.
=> Fall back to move_copy_to  if persist_to fails while saving uploaded files.

src/api/admin.rs, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/sends.rs, src/api/core/two_factor/authenticator.rs, src/api/core/two_factor/yubikey.rs, src/api/icons.rs, src/db/models/device.rs, src/db/models/send.rs, src/db/models/user.rs, src/main.rs, src/util.rs
A bit inspired by @paolobarbolini from this commit at lettre https://github.com/lettre/lettre/pull/784 .
I added a few more clippy lints here, and fixed the resulted issues.
Overall i think this could help in preventing future issues, and maybe
even peformance problems. It also makes some code a bit more clear.
We could always add more if we want to, i left a few out which i think
arn't that huge of an issue. Some like the `unused_async` are nice,
which resulted in a few `async` removals.
Some others are maybe a bit more estatic, like `string_to_string`, but i
think it looks better to use `clone` in those cases instead of `to_string` while they already are a string.
=> Add more clippy checks for better code/readability

Cargo.lock, Cargo.toml
- Update deps. One of them is multer-rs which fixes #2516
- Changed MSRV to `1.59.0`, since that is the correct MSRV currently.
It could be lower, but that would mean removing the `strip` option.
=> Update deps and fix file-uploads

src/api/icons.rs, src/config.rs, src/util.rs
When using anything else but the `internal` icon service it would
trigger an CSP block because the redirects were not allowed.
This PR fixes #2623 by dynamically adding the needed CSP strings.
This should also work with custom services.
For Google i needed to add an extra check because that does a redirect
it self to there gstatic.com domain.
=> Fix issue with CSP and icon redirects

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine, src/main.rs
The previous persistent folder check worked by checking if a file
exists. If you used a bind-mount, then this file is not there. But when
using a docker/podman volume those files are copied, and caused the
container to not start.
This change checks the `/proc/self/mountinfo` for a specific patern to
see if the data folder is persistent or not.
Fixes #2622
=> Fix persistent folder check within containers

.github/workflows/build.yml
Because we want to support MSRV, we also need to run a CI for this.
This PR adds checks for the MSRV and rust-toolchain defined versions.
It will also run all cargo test, clippy and fmt checks no matter the outcome of the previous job.
This will help when there are multiple issues, like clippy errors and formatting.
Previously it would show only the first failed check and stopped.
It will also output a nice step summary with some details on which checks have failed.
Or it will output a success message.
=> Update build workflow for CI

src/api/core/ciphers.rs, src/api/core/sends.rs
This PR attends to mitigate (not fix) #2644.
There seems to be an issue when uploading files either as attachment or
via send via the mobile (Android) client.
The binary data gets transfered correctly to Vaultwarden (Checked via
Wireshark), but the data is not parsed correctly for some reason.
Since the parsing is not done by Vaultwarden it self, i think we should
at least try to prevent saving the data and letting users think all
fine.
Further investigation is needed to actually fix this issue.
This is just a quick patch.
=> Mitigate attachment/send upload issues

.github/workflows/build.yml, Cargo.lock, Cargo.toml, docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine, docker/healthcheck.sh, docker/start.sh
- Updated deps
- Updated Alpine images to 3.16
- Removed dumb-init, not needed anymore
- Some small shellcheck tweaks on the start/healthcheck scripts
=> Update deps and Alpine image

Cargo.lock, Cargo.toml
This patch fixes the file upload send by the mobile clients.
It fixes #2644 by always providing a `Content-Type` even though one
isn't set in this specific case.
I do hope it will be fixed upstream by either Bitwarden by fixing the
client. Or Rocket by allowing to override this somehow.
Until then, we can use this patched version of multer-rs.
Issue @ Rocket: https://github.com/SergioBenitez/Rocket/issues/2299
Issue @ Bitwarden: https://github.com/bitwarden/mobile/issues/2018
Also updated some dependencies.
=> Fix uploads from mobile clients (and dep updates)

src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/settings.hbs
- Changed one link to open in a new Tab
- Prevent tabnabbing on three links
=> External Links | Optimize behavior

src/api/admin.rs, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/organizations.rs, src/api/core/sends.rs, src/db/models/mod.rs, src/db/models/org_policy.rs, src/db/models/organization.rs, src/db/models/user.rs
This PR adds a the new v2022.8.x revoke feature which allows an
organization owner or admin to revoke access for one or more users.
This PR also fixes several permissions and policy checks which were faulty.
- Modified some functions to use DB Count features instead of iter/count aftwards.
- Rearanged some if statements (faster matching or just one if instead of nested if's)
- Added and fixed several policy checks where needed
- Some small updates on some response models
- Made some functions require an enum instead of an i32
**NOTE:**
Please look at this PR carefully, I think i have done all the tests regarding the changed policy validation. But I could have missed a situation of course.
Also this PR is needed to use  the v2022.8.x version of the web-vault: …
=> Add Org user revoke feature

src/api/admin.rs, src/api/web.rs, src/static/scripts/bootstrap.css, src/static/scripts/jquery-3.6.1.slim.js, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
Previously FlashMessage was used to provide an error message during login.
This PR changes that flow to not use redirect for this, but renders the HTML and responds using the correct status code where needed. This should solve some issues which were reported in the past.
Thanks to @RealOrangeOne, for initiating this with a PR.
Fixes #2448
Fixes #2712
Closes #2715
=> Change the handling of login errors.

src/api/core/two_factor/mod.rs, src/util.rs
- The new web-vault version supports fastmail.com anon email, add the correct api host to support it.
- Removed Firefox Relay, this seems only to be supported on SaaS.
- Added a function to the two-factor api to prevent 404 errors.
=> Added support for web-vault v2022.9

src/api/core/organizations.rs
There was a small oversight on upgrading to v2022.9.0 web-vault version. It seems the call to the /plans/ endpoint doesn't provide authentication anymore.
Removed this check and it seems to work again.
Fixes #2737
=> Fix issue 2737, unable to create org

src/api/core/organizations.rs, src/db/models/organization.rs
In web-vault v2022.9.x it seems the endpoints changed.
- activate > restore
- deactivate > revoke
This PR adds those endpoints and renames the functions. It also keeps the previous endpoints for now to be compatible with previous vault verions for now, just in case.
=>  Rename/Fix revoke/restore endpoints

.github/workflows/build.yml, .github/workflows/hadolint.yml
Currently the branch protection is set on specific workflows which needs to be run every time a PR is created (or a push).
Because it isn't possible to tell the branch protection only to do it's job if specific files are touched or not, we just need to make sure these jobs are always started.
Also, because we now check the builds for an MSRV, and the title would change all the time, that would cause the branch protection to be updated everytime the MSRV would change. This is now also addressed by naming that job 'msrv' instead of the version number.
=> Update build workflow

src/api/core/ciphers.rs, src/api/core/sends.rs
This PR adds support for the Send v2 API.
It should prevent 404 errors which could cause some issues with some
configurations on some reverse proxies.
In the long run, we can probably remove the old file upload API, but for
now lets leave it there, since Bitwarden also still has this endpoint in
the code.
Might fixes #2753
=> Add support for send v2 API endpoints

src/api/core/organizations.rs, src/util.rs
Since v2022.9.x it seems they changed the export endpoint and way of working. This PR fixes this by adding the export endpoint.
Also, it looks like the clients can't handle uppercase first JSON key's. Because of this there now is a function which converts all the key's to lowercase first.
I have an issue reported at Bitwarden if this is expected behavior: https://github.com/bitwarden/clients/issues/3606
Fixes #2760
Fixes #2764
=> Fix organization vault export

src/api/core/mod.rs, src/api/mod.rs, src/api/web.rs, src/main.rs
=> add not_found catcher for 404 errors

src/api/core/organizations.rs
If you invite a new user as another owner of an organization you cannot remove or change the role of the user until the user accepts the invitation and is confirmed. This behavior was introduced in 1722742a (previously, in 1.25.2 you could remove yourself as the owner as long as you had invited someone else as owner which would also be incorrect).
This change ensures user_to_edit and user_to_delete are actually confirmed users, before checking if they are the last owner of an organization.
=> allow the removal of non-confirmed owners

src/api/core/accounts.rs
This is a minimal change to make vaultwarden compatible with v2022.9.2 because the web-vault expects a JSON response while registering now. It checks for the existence of a CaptchaBypassToken (see bitwarden/clients#3531) in the response which leads to a syntax error when trying to parse the Empty result.
=> v2022.9.2 expects a json response while registering

.env.template, src/auth.rs, src/config.rs
Add an option to configure the number of hours after which organization invites, emergency access invites, email verification emails and account deletion requests expire (defaults to 5 days or 120 hours and must be at least 1 hour).
=> make invitation expiration time configurable

src/auth.rs
This should fix #2792 by returning a bit more descriptive error messages when validating tokens, e.g. when a JWT has expired.
=> return more descriptive JWT validation messages

src/main.rs, src/util.rs
Adds a check if the data folder is a directory and also returns a more verbose error message if the permission was denied when creating a file.
I tried adding something like the following to `check_data_folder()` as well
```rust
let metadata = path.metadata().unwrap();
if metadata.permissions().readonly() {
warn!("Data folder '{}' is read-only.", data_folder);
}
```
However,  this does not really work because [`readonly()`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/fs.rs#L498-L501) only checks if _anyone_ has write permissions. :confounded:
=> check if data folder is a writable directory

src/db/models/cipher.rs
Upstream PR: https://github.com/bitwarden/server/pull/2142
I don't think this field is used for anything currently, but probably better to add it now than be surprised later.
=> Add `CreationDate` to cipher response JSON

src/api/core/organizations.rs
While testing locally (where I don't have mail enabled) I noticed that inviting a new user will save them as [invited](https://github.com/dani-garcia/vaultwarden/blob/6fa6eb18e88f6d090eff5139d5a67bb56d25bf7f/src/api/core/organizations.rs#L625). Removing and inviting the same user again (or inviting them in a second organization) they will be listed as [accepted](https://github.com/dani-garcia/vaultwarden/blob/6fa6eb18e88f6d090eff5139d5a67bb56d25bf7f/src/api/core/organizations.rs#L606) instead. This should not happen, because until the user has actually created an account they cannot be confirmed yet (and without admin panel access you would not know when they have done so).
If you try to confirm an <s>invited</s>accepted but non-existing user you will be greeted with this error message: …
=> fix invitations of new users when mail is disabled

src/api/core/accounts.rs
if signups are allowed invited users should be able to complete their registration even when they don't have the invite link at hand.
fixes #2800
=> allow registration without invite link

src/api/core/accounts.rs
- The Master Password Hint input has changed it's location to the password update form. This PR updates the code to process this.
- Also changed the `ProfileData` struct to exclude `Culture` and `MasterPasswordHint`, since both are not used at all, and when not defined they will also not be allocated.
Fixes #2833
=> Fix master password hint update not working.

src/api/core/accounts.rs
I think we can skip a verification step when a user registers via an invite link because they will only have the invite link if the email address is theirs and they should not be able register another email address with the link either.
=> verify email on registration by invite

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml
Updated all the actions where possible.
This should at least for the most actions mean that they are using the latest github actions core and should partially resolve the issue #2847
The only actions left are the actions from `actions-rs`.
=> Update github workflows

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildx, docker/amd64/Dockerfile.buildx.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildx, docker/arm64/Dockerfile.buildx.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildx, docker/armv6/Dockerfile.buildx.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildx, docker/armv7/Dockerfile.buildx.alpine
This pull request bumps webvault to 2022.10.1, what else?
=> feat: Bump web-vault to v2022.10.1

src/api/core/accounts.rs
Added a new endpoint which the currently beta client for at least Android v2022.10.1 seems to be calling, and crashes with the response we currently provide
Fixes #2890
Fixes #2891
Fixes #2892
Seems to be added first here: https://github.com/bitwarden/server/pull/2276/files#diff-43a69d1ec29236593aecde2a6496c066e2e7065f2f7ea1b827540d16d0373d18R134
=> Add `/devices/knowndevice` endpoint

Cargo.lock, Cargo.toml, src/api/core/organizations.rs, src/auth.rs
Since v2022.9.x the org export uses a different endpoint. But, since v2022.11.x this endpoint will return a different format. See: https://github.com/bitwarden/clients/pull/3641 and https://github.com/bitwarden/server/pull/2316
To support both version in the case of users having an older client either web-vault or cli this PR checks the version and responds using the correct format. If no version can be determined it will use the new format as a default.
=> Support Org Export for v2022.11 clients

src/api/core/two_factor/authenticator.rs, src/api/core/two_factor/mod.rs, src/api/notifications.rs, src/config.rs, src/crypto.rs, src/db/models/device.rs, src/db/models/send.rs, src/db/models/user.rs
All uses of `get_random()` were in the form of:
`&get_random(vec![0u8; SIZE])`
with `SIZE` being a constant.
Building a `Vec` is unnecessary for two reasons. First, it uses a very short-lived dynamic memory allocation. Second, a `Vec` is a resizable object, which is useless in those context when random data have a fixed size and will only be read.
`get_random_bytes()` takes a constant as a generic parameter and returns an array with the requested number of random bytes.
Stack safety analysis: the random bytes will be allocated on the caller stack for a very short time (until the encoding function has been called on the data). In some cases, the random bytes take less room than the `Vec` did (a `Vec` is 24 bytes on a 64 bit computer). The maximum used size is 180 bytes, which makes it for …
=> Use constant size generic parameter for random bytes generation

.env.template
TL;DR : Port 465 with implicit TLS for SMTP isn't outdated since RFC 8314
As stated in [RFC 8314](https://tools.ietf.org/html/rfc8314) : 
Also as stated [here](https://github.com/iredmail/iRedMail/issues/22#issuecomment-731779992) 
The IANA registry has been modified to register port 465 for native tls smtp connections :
=> Update config comment to reflect rfc8314.

src/config.rs
It was possible to disable the admin security via the admin interface. This is kinda insecure as mentioned in #2761.
This PR set this value as read-only and admin's need to set the correct ENV variable. Currently saved settings which do override this are still valid though. If an admin want's this removed, they either need to reset the config, or change the value in the `config.json` file.
Fixes #2761
=> Set "Bypass admin page security" as read-only

src/util.rs
The DuckDuckGo email service is not supported for self-hosted servers. This option is already hidden via the latest web-vault.
This PR also removes some server side headers.
Fixes #2828
=> Fully remove DuckDuckGo email service.

src/api/core/accounts.rs, src/api/identity.rs
In the upcomming web-vault and other clients they changed the register endpoint from `/api/accounts/register` to `/identity/register`.
This PR adds the new endpoint to already be compatible with the new clients.
Fixes #2889
=> Added missing `register` endpoint to `identity`

.env.template, src/config.rs
Update description from `login` to `admin` in admin page.
`Read-Only Config`
=> Update settings description

src/api/core/organizations.rs
Managers should be allowed to set the groups of a collection. In order to do that, they'll need the permission to get the groups of an organization. 
fixes #2932
fixes #2930
=> allow managers to set groups of a collection

src/config.rs, src/db/mod.rs
Instead of creating the parent folders to a sqlite database vaultwarden should just exit.
This should fix most issues like #2835 where a wrongly configured `DATABASE_URL` falls back to using sqlite.
=> check if sqlite folder exists

src/api/admin.rs, src/api/mod.rs, src/main.rs, src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/login.hbs
Currently, if the admin guard fails the user will get a 404 page instead of being forwarded to the login page.
This change addresses issues like #2880 and #2883 by implementing a default forward catcher for all admin pages so this comment is correct:
https://github.com/dani-garcia/vaultwarden/blob/f60a6929a9a289bd39c38eeb793ebf54c4d88199/src/api/admin.rs#L656
=> redirect to admin login page when forward fails

.env.template, src/api/admin.rs, src/api/core/emergency_access.rs, src/api/core/organizations.rs, src/api/icons.rs, src/auth.rs, src/config.rs, src/db/mod.rs, src/db/models/emergency_access.rs, src/db/models/user.rs, src/error.rs, src/mail.rs
- Several cleanups and code optimizations for Emergency Access
- Fixed a race-condition regarding jobs for Emergency Access
- Some other small changes like `allow(clippy::)` removals
Fixes #2925
Fixes #2955
=> Cleanups and Fixes for Emergency Access

src/api/core/ciphers.rs
As discussed in #2937, this will limit the amount of encrypted characters to 10.000 characters, same as Bitwarden. This will not break current ciphers which exceed this limit, but it will prevent those ciphers from being updated.
Fixes #2937
=> Limit Cipher Note encrypted string size

src/static/templates/admin/base.hbs
Currently when you login into the admin, and then directly hit the save button, it will come with a re-post/re-submit warning. This has to do with the `window.location.reload()` function, which triggers the admin login POST again.
By changing the way to reload the page, we prevent this repost.
=> Fix admin repost warning.

Cargo.lock, Cargo.toml, build.rs, src/db/mod.rs, src/main.rs
This PR adds query logging support as an optional feature. It is only allowed during development/debug builds, and will abort when used during a `--release` build.
For this feature to be fully activated you also need to se an environment variable `QUERY_LOGGER=1` to activate the debug log-level for this crate, else there will be no output.
The reason for this PR is that sometimes it is useful to be able to see the generated queries, like when debugging an issue, or trying to optimize a query. Currently i always added this code when needed, but having this a part of the code could benifit other developers too who maybe need this.
=> Add dev-only query logging support

src/config.rs
This changes the masking function to hide a bit more information from the generated support string. It will still keep showing the `://` for example, and `,`, but other characters will be hidden.
Also did some small changes on some key's which all showed up as `Internal` on the Settings page.
Fixes #2929
=> Increase privacy of masked config

.env.template
- The first one was not a proper sentence.
- The second one mixed passive and active form in the second part of the sentence.
- fixed spelling error
=> Improve comments

Cargo.lock, Cargo.toml, src/main.rs
- Removed ctrlc crate and use the tokio provided ctrl_c function.
- Updated some crates.
=> Remove ctrlc crate and some updates

src/api/core/organizations.rs
It looks like Bitwarden, in-the-end, didn't changed the export feature on v2022.11.0, and now have put in on v2023.1.0.
This patch now changes that to the same version.
Before those new clients are being released, we should see if they changed that again, and adjust where needed.
=> Fix org export (again)

src/db/models/collection.rs
Using the `inner_join` seems to cause issues, even though i have tested it. Strangely it does cause issues. Reverting it back to `left_join` seems to solve the issue for me.
Fixes #2975
=> Revert collection queries back to `left_join`

src/api/core/two_factor/mod.rs, src/api/identity.rs, src/auth.rs
When audit logging was introduced there entered a small bug preventing the recover-2fa from working.
This PR fixes that by add a new headers check to extract the device-type when possible and use that for the logging.
Fixes #2985
=> Fix recover-2fa not working.

src/api/core/two_factor/yubikey.rs, src/api/identity.rs
The yubico crate uses blocking reqwest, and we called the `verify` from a async thread. To prevent issues we need to wrap it within a `spawn_blocking`.
=> Fix a panic during Yubikey register/login

Cargo.lock, Cargo.toml, src/api/core/ciphers.rs, src/api/core/sends.rs
Seems like the fix was merged into 2022.10.0: https://github.com/bitwarden/mobile/releases/tag/v2022.10.0. Which is few months old now, so I think it is safe to remvove the workarounds
cc @BlackDex
=> Remove patched multer-rs

src/api/admin.rs, src/api/web.rs, src/config.rs, src/static/scripts/404.css, src/static/scripts/admin.css, src/static/scripts/admin.js, src/static/scripts/admin_diagnostics.js, src/static/scripts/admin_organizations.js, src/static/scripts/admin_settings.js, src/static/scripts/admin_users.js, src/static/scripts/bootstrap.css, src/static/templates/404.hbs, src/static/templates/admin/base.hbs, src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/organizations.hbs, src/static/templates/admin/settings.hbs, src/static/templates/admin/users.hbs, src/util.rs
- Removed `unsafe-inline` for javascript from CSP. The admin interface now uses files instead of inline javascript.
- Modified javascript to work not being inline.
- Run eslint over javascript and fixed some items.
- Added a `to_json` Handlebars helper. Used at the diagnostics page.
- Changed `AdminTemplateData` struct to be smaller. The `config` was always added, but only used at one page. Same goes for `can_backup` and `version`.
- Also inlined CSS.
We can't remove the `unsafe-inline` from css, because that seems to
break the web-vault currently. That might need some further checks.
But for now the 404 page and all the admin pages are clear of inline scripts and styles.
=> Removed unsafe-inline JS from CSP and other fixes

src/config.rs
If the `YUBICO_SERVER` is defined to an empty string, the whole yubikey implementation doesn't work anymore.
This PR adds a check for this variable that it at least starts with `https://`.
Resolves #3003
=> Validate YUBICO_SERVER string (#3003)

src/config.rs
Closes #3055. Logs a message to stderr if the configured log file isn't writable. Because the `error!` macro is configured to use any log files already set up I'm using `eprintln!` here. Let me know if there's another way you would prefer.
=> Log message to stderr if LOG_FILE is not writable

src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/folders.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/core/sends.rs, src/api/notifications.rs
Previously the websocket notifications were using the string `app_id` as the
`ContextId`. This was incorrect and should have been the device_uuid
from the client device executing the request. The clients will ignore
the websocket request if the uuid matches. This also fixes some issues
with the Desktop client which is able to modify attachments within the
same screen and causes an issue when saving the attachment afterwards.
Also changed the way to handle removed attachments, since that causes an
error saving the vault cipher afterwards, complaining about a missing
attachment. Bitwarden ignores this, and continues with the remaining
attachments (if any). This also fixes #2591 .
Further some more websocket notifications have been added to some other
functions which enhance the user …
=> Update WebSocket Notifications

src/config.rs
As kinda discussed here #3090, the messages regarding loading the configuration files is a bit strange or unclear. There have been some other reports regarding this in the past, but wasn't that big a of a deal.
But to make the whole process it bit more nice, this PR adjusts the way it reports issues and some small changes to the messages to make it all a bit more clear.
- Do not report a missing `.env` file, but only send a message when using one.
- Exit instead of Panic, a panic causes a stacktrace, which isn't needed here. I'm using a exit code 255 here so it is different to the other exit's we use.
- Exit on more issues, since if we continue, it could cause configuration issues if the user thinks all is fine.
- Use the actual env file used in the messages instead of `.env`.
- Added a …
=> Optimize config loading messages

src/mail.rs, src/static/templates/email/send_org_invite.hbs, src/static/templates/email/send_org_invite.html.hbs
If org_name contains spaces, the generated link will not work in some email clients unless it is percent-encoded
=> Percent-encode org_name in links

.github/workflows/build.yml, Cargo.lock, Cargo.toml
- Updated dependencies. This includes a janked openssl crate version we currently use.
- Updated MSRV to v1.61.0 because hashbrown/cached has this version restriction.
=> Update dependencies and MSRV

src/static/templates/admin/base.hbs
Although still valid -> Remove HTML4.x legacy code in favour of shorter HTML5
=> Use more modern meta tag for charset encoding

src/util.rs
Will need of course client change, but feel free to merge this when bumping next bitwarden vault
FIxes #3066
=> fix (2fa.directory): Allow api.2fa.directory, and remove 2fa.directory

src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/organizations.rs, src/db/models/attachment.rs
As mentioned in #3111, using a very very large vault causes some issues. Mainly because of a SQLite limit, but, it could also cause issue on MariaDB/MySQL or PostgreSQL. It also uses a lot of memory, and memory allocations.
This PR solves this by removing the need of all the cipher_uuid's just to gather the correct attachments.
It will use the user_uuid and org_uuid's to get all attachments linked to both, weither the user has access to them or not. This isn't an issue, since the matching is done per cipher and the attachment data is only returned if there is a matching cipher to where the user has access to.
I also modified some code to be able to use `::with_capacity(n)` where possible. This prevents re-allocations if the `Vec` increases size, which will happen a lot if there are a lot …
=> Optimize CipherSyncData for very large vaults

migrations/mysql/2023-01-11-205851_add_avatar_color/up.sql, migrations/postgresql/2023-01-11-205851_add_avatar_color/up.sql, migrations/sqlite/2023-01-11-205851_add_avatar_color/up.sql, src/api/core/accounts.rs, src/db/models/user.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs, src/main.rs
The new web-vault v2023.1.0 supports a custom color for the avatar. https://github.com/bitwarden/server/pull/2330
This PR adds this feature.
=> Add avatar color support

src/db/models/organization.rs
The Organization member overview supports showing an icon if the user has MFA enabled or not. This PR adds this feature.
This is very useful if you want to enable force mfa for example.
Example:
=> Add MFA icon to org member overview

src/api/admin.rs, src/api/core/accounts.rs, src/api/notifications.rs
We also need to validate the note sizes on key-rotation. If we do not validate them before we store them, that could lead to a partial or total loss of the password vault. Validating these restrictions before actually processing them to store/replace the existing ciphers should prevent this.
There was also a small bug when using web-sockets. The client which is triggering the password/key-rotation change should not be forced to logout via a web-socket request. That is something the client will handle it self. Refactored the logout notification to either send the device uuid or not on specific actions.
Fixes #3152
=> Validate note sizes on key-rotation.

src/api/core/emergency_access.rs
I've looked into this some more and the client [does not send the key](https://github.com/bitwarden/clients/blob/7ebedbecfbbdfe17b011ca6490bf98fdd5116016/apps/web/src/app/settings/emergency-access-add-edit.component.ts#L74-L78) while editing an emergency access contact, so the field would be emptied on a change of the wait days or access level.
This simple fix should hopefully prevent issues like #3196 where the key has been set to `NULL`.
Closes #3196
=> don't nullify key when editing emergency access

src/auth.rs, src/config.rs
Bitwarden send won't work if the domain includes a trailing slash. This should be documented, as it may lead to confusion among users.
=> Fix trailing slash not getting removed from domain

src/api/icons.rs
When an icon will not be downloaded due to matching a configured blacklist, ensure that the log message indicates the type of blacklist that was matched.
=> Generate distinct log messages for regex vs. IP blacklisting.

src/db/models/collection.rs
=> allow editing/unhiding by group

.env.template, Cargo.lock, Cargo.toml, src/config.rs, src/mail.rs
This PR enables using `lettre`'s `SendmailTransport` in Vaultwarden.
It adds two configuration options:
- `USE_SENDMAIL` wether to use sendmail instead of directly connecting to a SMTP server
-  `SENDMAIL_COMMAND` what sendmail command to use. By default the one from the `$PATH` is used, but I think there are cases where it makes sense to specify a different one
Supporting the system MTA allows for more flexible mail configuration without too much effort and does not require packaging any sendmail client as assumed in #2198.
While there are other usecases like sending through a local mailserver without having to create a dedicated SMTP Account as mentioned in #2198, my specific usecase for this is the following:
I have msmtp configured with an account that all applications use without me …
=> add support for system mta though sendmail

src/api/identity.rs
During the client API login we need to have a `device_identifier`, `device_name` and `device_type`.
When these were not provided Vaultwarden would panic.
This PR add checks for these fields and makes sure it returns a better error message instead of causing a panic.
=> Validate all needed fields for client API login

src/db/models/group.rs, src/db/models/organization.rs
With existing groups configured within an org, deleting that org would fail because of Foreign Key issues.
This PR fixes this by making sure the groups get deleted before the org does.
Fixes #3247
=> Fix Organization delete when groups are configured

src/db/models/collection.rs
Previously only user rights where checked for collection when adding a new entry. 
The problem was with a group with only read-only access, the user had the collection in his collection list when adding a new entry as explained in issue #3249  .
Fixes #3249
=> Fix Collection Read Only access for groups

.env.template, src/api/admin.rs, src/auth.rs, src/config.rs
In my opinion, it may be useful if this value is adjustable to personal needs. For example, I want to access the Admin API programmatically and accordingly I want to set this value to as short as possible. Others may want to set the value higher if they often spend a long time in the Admin UI or something.
=> Make the admin session lifetime adjustable

src/static/scripts/admin_users.js
As someone who has inadvertently pressed "Remove all 2FA" instead of "Deauthorize sessions" one too many times (and had to re-add all my YubiKeys) - there should be a confirmation prompt before taking either of those actions.
Regardless of my accidental misclicks - any action that modifies user state should be protected by a confirmation prompt.
=> Add confirmation for removing 2FA and deauthing sessions in admin panel

src/api/admin.rs, src/db/models/collection.rs, src/db/models/event.rs, src/db/models/group.rs, src/static/scripts/admin.css, src/static/scripts/admin_diagnostics.js, src/static/scripts/admin_organizations.js, src/static/scripts/admin_users.js, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
- Updated datatables
- Added NTP Time check
- Added Collections, Groups and Events count for orgs
- Renamed `Items` to `Ciphers`
- Some small style updates
=> Some Admin Interface updates

src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/db/models/cipher.rs, src/db/models/collection.rs, src/db/models/group.rs, src/db/models/organization.rs
- Supports the new Collection/Group/User editing UI's
- Support `/partial` endpoint for cipher updating to allow folder and favorite update for read-only ciphers.
- Prevent `Favorite`, `Folder`, `read-only` and `hide-passwords` from being added to the organizational sync.
- Added and corrected some `Object` key's to the output json.
Fixes #3279
=> Fix the web-vault v2023.2.0 API calls

.env.template, Cargo.lock, Cargo.toml, src/api/admin.rs, src/config.rs, src/main.rs, src/static/scripts/admin_settings.js, src/static/templates/admin/settings.hbs
Added support for Argon2 hashing support for the `ADMIN_TOKEN` instead of only supporting a plain text string.
The hash must be a PHC string which can be generated via the `argon2` CLI **or** via the also built-in hash command in Vaultwarden.
You can simply run `vaultwarden hash` to generate a hash based upon a password the user provides them self.
Added a warning during startup and within the admin settings panel is the `ADMIN_TOKEN` is not an Argon2 hash.
Within the admin environment a user can ignore that warning and it will not be shown for at least 30 days. After that the warning will appear again unless the `ADMIN_TOKEN` has be converted to an Argon2 hash.
I have also tested this on my RaspberryPi 2b and there the `Bitwarden` preset takes almost 4.5 seconds to generate/verify the …
=> Admin token Argon2 hashing support

src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/events.rs, src/api/core/organizations.rs, src/api/core/two_factor/authenticator.rs, src/api/core/two_factor/duo.rs, src/api/core/two_factor/email.rs, src/api/core/two_factor/mod.rs, src/api/core/two_factor/webauthn.rs, src/api/core/two_factor/yubikey.rs, src/api/identity.rs, src/api/notifications.rs, src/auth.rs, src/db/models/cipher.rs, src/main.rs, src/util.rs
Since we now use the `ClientIp` Guard on a lot more places, it also increases the size of binary, and the macro generated code because of this extra Guard. By merging the `ClientIp` Guard with the several `Header` guards we have it reduces the amount of code generated (including LLVM IR), but also a small speedup in build time.
I also spotted some small `json!()` optimizations which also reduced the amount of code generated.
There was no decrease in the speed of the code as far as i could tell. It btw also lowered the amount of allocations done.
=> Merge ClientIp with Headers.

src/api/core/organizations.rs, src/auth.rs
I'm not sure if this is the best way but this should fix #3350
=> add endpoints to bulk delete collections/groups

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, README.md, src/main.rs, src/util.rs
- Updated workflows to use new checkout version
This probably fixes the curl download for hadolint if that is related?
- Updated crates including Rocket to the latest rc3 🎉 
- Applied 2 nightly clippy lints to prevent future clippy issues.
- Added shields for quay and ghcr
=> Some small fixes and updates

src/api/core/accounts.rs
The clients end up removing the padding characters [1][2].
[1] https://github.com/bitwarden/clients/blob/web-v2023.3.0/libs/common/src/misc/utils.ts#L141-L143
[2] https://github.com/bitwarden/mobile/blob/v2023.3.1/src/Core/Utilities/CoreHelpers.cs#L227-L234
Fixes #3375
=> Decode knowndevice `X-Request-Email` as base64url with no padding

src/api/admin.rs, src/static/scripts/admin_users.js, src/static/templates/admin/users.hbs
This PR adds new admin endpoint and action button in admin ui to resend invitation link to user (only by email, if smtp enabled).
=> support `/users/<uuid>/invite/resend` admin api

src/api/core/accounts.rs, src/api/core/emergency_access.rs, src/api/identity.rs
As discussed in #3390 we could simplify the login logic a bit because the client will ignore the value of theses fields in case of `PBKDF2` (whether they are unset or set to any value from trying out `Argon2id` as KDF)
With `Argon2id` those fields should never be `null` but always in a valid state. Be aware that if they are `null` the client will assume the bitwarden presets (i.e. m=64 and p=4) and if the fields are set to something else (not sure how this would happen but it's technically possible with a sqlite database) the login would most likely fail.
So there should not be a reason to panic.
Disclaimer: I've only tested this change with the web-vault. Since this seems to be also the behavior of vault.bitwarden.com I'm assuming that the other clients will not behave differently in …
=> always return KdfMemory and KdfParallelism

src/db/models/organization.rs
For some reason I encountered a strange bug which resulted in sending out multiple websocket notifications for the exact same user.
Added a `distinct()` for the query to filter out multiple uuid's.
=> Fix sending out multiple websocket notifications

src/db/models/org_policy.rs
should fix #3424
edit: i just checked and only active send options policies should be returned by `find_confirmed_by_user_and_active_policy` anyway.
=> check if reset password policy is enabled

Cargo.lock, Cargo.toml, src/api/notifications.rs
This PR implements a (not yet fully released) new feature of Rocket which allows WebSockets/Upgrade connections.
No more need for multiple ports to be opened for Vaultwarden.
No explicit need for a reverse proxy to get WebSockets to work (Although I still suggest to use a reverse proxy).
- Using a git revision for Rocket, since `rocket_ws` is not yet released.
- Updated other crates as well.
- Added a connection guard to clear the WS connection from the Users list.
Fixes #685
Fixes #2917
Fixes #1424
=> WebSockets via Rocket's Upgrade connection

.env.template, src/api/web.rs, src/config.rs, src/static/scripts/admin.css, src/static/scripts/admin.js, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/scripts/jquery-3.6.4.slim.js, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
- Fixed issue with domains starting with `admin`
- Fixed issue with DUO not being enabled globally anymore (regression)
- Renamed `Ciphers` to `Entries` in overview
- Improved `ADMIN_TOKEN` description
- Updated jquery-slim and datatables
Resolves #3382
Resolves #3415
Resolves discussion on #3288
=> Several config and admin interface fixes

src/auth.rs
From my understanding, rust never inlines static variables meaning that these variables are separately statically allocated and wasting space.
Even if there's not codegen diff, separately defining these static variables is (imo) code smell.
=> inline static rsa keys

Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/events.rs, src/api/core/folders.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/core/sends.rs, src/api/icons.rs, src/api/web.rs, src/auth.rs, src/mail.rs, src/main.rs, src/static/scripts/admin_settings.js, src/static/scripts/admin_users.js, src/util.rs
During setting the latest commit hash for Rocket and updating all the other crates, there were some messages regarding the usage of `String` for the Rocket endpoint function calls.
I acted upon this message and changed all `String` types to `&str` and modified the code where needed.
This ended up in less `alloc` calls, and probably also a bit less memory usage.
- Updated all the crates and commit hashes
- Modified all `String` to `&str` where applicable
- Prevent some `::_` logs from outputting
- Added some extra routes to be logged
- Fix some admin post endpoints
=> Change `String` to `&str` for all Rocket functions and some other fixes

Cargo.lock, Cargo.toml, src/util.rs
There now is a `v0.5` branch which will be the final release version
when the time is there. Switched to this instead of the `master` branch
which contains other fixes and enhancements as well (for `v0.6`).
This should solve all the endpoint issue we were having.
Fixes #3495
Fixes #3494
Fixes #3506
=> Use Rocket `v0.5` branch to fix endpoints

src/api/core/organizations.rs
The web-vault will throw an error in the web console when editing new policies with an empty data field (like "Require two-step login", "Single organization", "Remove individual vault" and "Remove Send")
=> policy data should be `null` not an empty object

Cargo.lock, Cargo.toml, docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildkit, docker/amd64/Dockerfile.buildkit.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildkit, docker/arm64/Dockerfile.buildkit.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildkit, docker/armv6/Dockerfile.buildkit.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildkit, docker/armv7/Dockerfile.buildkit.alpine
Update to latest web-vault using [vaultwarden/web-vault:v2023.4.2](https://hub.docker.com/layers/vaultwarden/web-vault/v2023.4.2/images/sha256-33f95dff16d8b62a6c0334ec0e425e5e549e6a826a4d8d3ea1beb95ded6acb0e)
=> update web-vault to v2023.4.2

src/api/admin.rs
When you are not loggedin, and have no cookie etc.. we always returned a 401. This was mainly to allow the login page on all the sub pages, and after login being redirected to the requested page, for these pages a 401 is a valid response, since, you do not have access.
But for the main `/admin` page, it should just respond with a `200` and show the login page.
This PR fixes this flow and response. It should prevent people using Fail2ban, or other tools being triggered by only accessing the login page.
Resolves #3540
=> Prevent 401 on main admin page

src/api/core/ciphers.rs, src/api/notifications.rs
When chaning a collection this did not got notified via WebSockets. This PR adds this feature and resolves #3534
=> Fix collection change ws notifications

.env.template, migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql, migrations/postgresql/2023-02-18-125735_push_uuid_table/up.sql, migrations/sqlite/2023-02-18-125735_push_uuid_table/up.sql, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/folders.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/core/sends.rs, src/api/mod.rs, src/api/notifications.rs, src/api/push.rs, src/config.rs, src/db/models/device.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
[Push-demo.webm](https://user-images.githubusercontent.com/45696571/222894552-109e3c34-e9b2-44a0-9474-304123f78b0a.webm)
Special thanks to @samb-devel for your help
Get your keys from [the Bitwarden website](https://bitwarden.com/host)
Set environment variables to the required values:
```env
PUSH_ENABLED=true
PUSH_INSTALLATION_ID=CHANGEME
PUSH_INSTALLATION_KEY=CHANGEME
```
PUSH_RELAY_URI is already configured to use default Bitwarden server.
Start the server, then test.
This was my first shot at Rust.
=> feat: Implement Push Notifications sync

migrations/mysql/2022-07-21-200424_create_organization_api_key/up.sql, migrations/mysql/2023-06-02-200424_create_organization_api_key/up.sql, migrations/postgresql/2022-07-21-200424_create_organization_api_key/up.sql, migrations/postgresql/2023-06-02-200424_create_organization_api_key/up.sql, migrations/sqlite/2022-07-21-200424_create_organization_api_key/up.sql, migrations/sqlite/2023-06-02-200424_create_organization_api_key/up.sql, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/core/public.rs, src/api/identity.rs, src/auth.rs, src/db/models/device.rs, src/db/models/group.rs, src/db/models/mod.rs, src/db/models/organization.rs, src/db/models/user.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
I previously started a branch to implement the API Key support for Organizations.
Later @Kurnihil used that branch to further implement this and created a PR #2907, which hasn't been touched for a while now.
I refreshed this by rebasing and merging and updateing the work already done by @Kurnihil and tested this using a very small set of users and groups via an OpenLDAP server. I do not have access to an Microsoft AD or Azure AD environment which I can use for testing, so that is not taken into account here.
Closes #2907
Co-authored-by: Daniele Andrei <daniele.andrei@geo-satis.com>
Co-authored-by: Kurnihil
=> Implement the Organization API Key support for the new Directory Connector v2022

src/api/admin.rs, src/api/core/accounts.rs, src/api/core/organizations.rs, src/api/core/sends.rs, src/api/notifications.rs, src/api/push.rs, src/db/models/device.rs
Partially fixes #3577.
Over time, old devices accumulate in the SQL device table. Even when the device push uuid is NULL, a push request is sent for them when mobile push is active. For my server, this lead to ~100 requests to the Bitwarden push servers without a single active mobile push client, and a request time of ~15 seconds.
This requests adds a filter to prevent mobile push notifications from being sent to clients who did not even register for mobile push.
=> Add mobile push device filter to non-null push uuid

src/api/core/sends.rs
In a previous commit push notifications for mobile were added, but this introduced a header guard which caused issues with anonymous endpoints.
This PR fixes this by using a uuid with only 0's.
Fixes #3607
=> Fix send access regression

src/api/core/ciphers.rs, src/db/models/cipher.rs
1. Checkout [this branch](https://github.com/bitwarden/server/tree/EC-598-beeep-properly-store-passkeys-in-bitwarden), then install dependencies with `npm i` (`npm ci` didn't worked, where `npm i` somehow worked in my case)
2. Enable feature flag for the extension. As I didn't figured out how to do this properly, I changed the values [there](https://github.com/bitwarden/clients/pull/4715/files#diff-ee9271bfbbddd589f955418cf1fc8a360ea76819afe2400d96d2f8a79dc3dd6dR41-R43) and [there](https://github.com/bitwarden/clients/pull/4715/files#diff-ee9271bfbbddd589f955418cf1fc8a360ea76819afe2400d96d2f8a79dc3dd6dR194-R196) to make them always return true
3. Follow the [docs](https://contributing.bitwarden.com/getting-started/clients/browser/#build-instructions) to build and install the modified …
=> feat: Support for storing passkeys in the vault

README.md
I added `--restart unless-stopped` to the docker run command to let vaultwarden restart itself after a crash for example.
I added it to my run command because I found vaultwarden stopped for unknown reasons (maybe because docker tries to safe resources if this is a thing).
And you don't have to manual start the container on every server restart.
=> Updated docker run command

src/api/core/organizations.rs
While enrolling reset password as user the web interface forces to type the password to authenticate oneself.
In its current state the backend doesn't check the password. Therefore a random passord can be used for authentification.
This PR solves this issue.
=> fix missing password check while manual reset password enrollment

Cargo.lock, Cargo.toml, src/api/notifications.rs
- Update all crates
- Remove async which is reported by clippy in v1.72.0
=> Update crates and small clippy fix

build.rs
When a specific commit is checked out from the main branch, the vaultwarden version is reported as `vaultwarden x.y.z-githash (HEAD)`. This is a problem, because the admin interface reports this as a version from a branch called HEAD, while in reality the commit was from the main branch.
=> fix version when compiled at a specific commit

src/api/core/organizations.rs
A previous PR added a field which isn't there on the initial creation of an org. This PR fixes that.
=> Fix org creation regresion

src/util.rs
Added with web vault v2023.7.0
=> feat: Add support for forwardemail

src/api/core/organizations.rs, src/db/models/group.rs, src/db/models/organization.rs
- Do not update `externalId` on group updates Groups are only updated via the web-vault currently, and those do not send the `externalId` value, and thus we need to prevent updating it.
- Refactored some other ExternalId functions
- Prevent empty `externalId` on `Collections`
- Return `externalId` for users
Fixes #3685
=> Fix some external_id issues

src/api/web.rs
There was some debug code during attachment downloads. This produces extra logs not needed or even wanted.
=> Remove debug code during attachment download

.env.template, src/config.rs
There was one item missing and one item wrongly named.
This has been fixed including a spellcheck.
=> Fix .env.template file

src/api/core/public.rs
When a user does not have an account yet and SMTP was disabled it would set the UserOrg status still to Accepted, though that would make it possible to verify the user by the Org Admin's.
This would fail, since the user didn't actually crated his account, and therefor no PublicKey existed.
This PR fixes this behaviour by checking if the password is empty and if so, puts the user to an `Invited` state instead of `Accepted`.
Fixes #3737
=> Fix UserOrg status during LDAP Import

migrations/mysql/2023-06-17-200424_create_auth_requests_table/up.sql, migrations/postgresql/2023-06-17-200424_create_auth_requests_table/up.sql, migrations/sqlite/2023-06-17-200424_create_auth_requests_table/up.sql, src/api/core/accounts.rs, src/api/core/mod.rs, src/api/identity.rs, src/api/mod.rs, src/api/notifications.rs, src/api/push.rs, src/config.rs, src/db/models/auth_request.rs, src/db/models/device.rs, src/db/models/mod.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs, src/main.rs
This is a **very WIP** pull-request for login-with-device. To run this, you need a new client version, for the web client this is 2023.06 (or latest master as of today) since login-with-device was disabled for self-hosted installations previously.
Basic login-with-device on WebSocket clients (desktop/web/webextension) works, but there is still quite some work to be done.
[Screencast from 2023-06-17 23-53-39.webm](https://github.com/dani-garcia/vaultwarden/assets/11866552/88a9360f-483a-4bcb-9e8f-58a264f2457e)
This PR implements a few components to make the login-with-device work, each still partially incomplete.
- A few new rocket endpoints for adding / updating requests (mostly done, some request validation / responses missing)
- A new database table for keeping the auth_requests (only …
=> Implement "login with device"

Cargo.lock, docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildkit, docker/amd64/Dockerfile.buildkit.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildkit, docker/arm64/Dockerfile.buildkit.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildkit, docker/armv6/Dockerfile.buildkit.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildkit, docker/armv7/Dockerfile.buildkit.alpine
Requires #3592 for https://github.com/dani-garcia/vaultwarden/pull/3769/commits/2f594d4299574db622e500be0bb73a98637dc4ee
=> chore: Bump web vault to v2023.7.1 and bump Rust

Cargo.toml, src/api/icons.rs
Some optimizations in regards to downloading Favicon's.
I also encounterd some issues with accessing some sites where the connection got dropped or closed early. This seems a reqwest/hyper thingy, https://github.com/hyperium/hyper/issues/2136. This is now also fixed.
General:
- Decreased struct size (reduces memory usage)
- Decreased memory allocations (faster HTML parsing)
- Optimized tokenizer a bit more to only emit tags when all attributes are there and are valid.
reqwest/hyper connection issue:
The following changes helped solve the connection issues to some sites. The endresult is that some icons are now able to be downloaded always instead of sometimes.
- Enabled some extra reqwest features, `deflate` and `native-tls-alpn` (Which do not bring in any extra crates since other crates …
=> Optimized Favicon downloading

src/api/identity.rs
needed for web-v2023.8.2+ compatibility due to the inclusion of the new [trusted device encryption](https://github.com/bitwarden/clients/commit/bf2cc019c55ae17b948e3988f852d10b03125fc2) feature. without this change, the web vault will assume that you don't have a master password set and force you to set one:
=> add UserDecryptionOptions to login response

src/api/core/organizations.rs
in `web-v2023.8.x` the [`getPlans()`](https://github.com/bitwarden/clients/blob/627b39f6f378528107eacaa4053d79f8f3c14608/libs/common/src/services/api.service.ts#L891-L894) call was changed from `/plans/` to `/plans/all` and the form to create new organizations also [requires a bitwardenProduct](https://github.com/bitwarden/clients/blob/b403f2bcc79426abb9d8f02c391b7c8158876960/apps/web/src/app/billing/settings/organization-plans.component.ts#L140) to differentiate between plans for PasswordManager and the SecretsManager. by adding a second plan with `"BitwardenProduct": 1` this should work again.
=> add new secretsmanager plan for web-v2023.8.x

src/api/notifications.rs, src/auth.rs
Some clients (Thirdparty) might use the `Authorization` header instead of a query param. We didn't supported this since all the official clients do not seem to use this way of working. But Bitwarden does check both ways.
This PR adds an extra check for this header which can be optional.
Fixes #3776
=> Allow Authorization header for Web Sockets

docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/amd64/Dockerfile.buildkit, docker/amd64/Dockerfile.buildkit.alpine, docker/arm64/Dockerfile, docker/arm64/Dockerfile.alpine, docker/arm64/Dockerfile.buildkit, docker/arm64/Dockerfile.buildkit.alpine, docker/armv6/Dockerfile, docker/armv6/Dockerfile.alpine, docker/armv6/Dockerfile.buildkit, docker/armv6/Dockerfile.buildkit.alpine, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, docker/armv7/Dockerfile.buildkit, docker/armv7/Dockerfile.buildkit.alpine
Update to use [vaultwarden/web-vault:v2023.8.2](https://hub.docker.com/layers/vaultwarden/web-vault/v2023.8.2/images/sha256-b361e79309ef2c4368f880f350166daade41eb0927a9adf376c76e3713027252)
=> update web-vault to v2023.8.2

src/util.rs
anonaddy.com [has been rebranded](https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/) to addy.io.
=> csp: rename anonaddy.com to addy.io

README.md
A comma in this place forces an unnatural pause in the sentence.
=> README.md: Fix grammar nit

src/db/mod.rs, src/util.rs
During a WebSocket connection we currently also send several headers
which could cause issues with some reverse proxy, or with the CloudFlare
tunnel for example. This PR resolves these issues.
Fixes #3881
The PostgreSQL migrations do not need this setting.
I tested this by running an old Vaultwarden instance (v1.18.0) on a new
PostrgreSQL database, created a few users and some vault items, after
that run the new code and it doesn't break.
Fixes #3930
=> Fix small issues

Cargo.lock, Cargo.toml, src/main.rs
This change makes Vaultwarden reopen the log file on SIGHUP, enabling proper log rotation without logrotate's copytruncate hack.
=> Reopen log file on SIGHUP

migrations/mysql/2023-09-02-212336_move_user_external_id/up.sql, migrations/postgresql/2023-09-02-212336_move_user_external_id/up.sql, migrations/sqlite/2023-09-02-212336_move_user_external_id/up.sql, src/api/core/public.rs, src/db/models/organization.rs, src/db/models/user.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
While working on the fix for #3777 I realized the location where the `external_id`
is stored was wrong. It was stored in the `users` table, but it actually
should have been stored in the `users_organizations` table.
This will move the column to the right table. It will not move the
values of the `external_id` column, because if there are more
organizations, there is no way to really know which organization it is
linked to. Setups using the Directory Connector can clear the sync
cache, and sync again, that will store all the `external_id` values at
the right location.
Also changed the function to revoke,restore an org-user and set_external_id to return a boolean.
It will state if the value has been changed or not, and if not, we can
prevent a `save` call to the database.
The `users` table …
=> Fix External ID not set during DC Sync

.env.template, src/api/core/accounts.rs, src/config.rs
Added new configuration option to prevent users from changing their email.
By default is set to allow it.
=> New config option disable email change

src/static/templates/email/twofactor_email.hbs, src/static/templates/email/twofactor_email.html.hbs
Changed subject lines in both the regular and HTML version of the 2FA confirmation email because previous subject line ("Your Two-step Login Verification Code") was being blocked by Google's servers.
The new subject line is "Vaultwarden Confirmation Code"
Please comment if a different subject line is preferable for any reason.
I've only tested this subject line with the emailer configured to use a Google SMTP server. If you have Vaultwarden configured to use another email service, please test this template using your email service.
=> 2FA Confirmation Code Email subject line change to fix triggering Google spam blocker

migrations/mysql/2023-10-21-221242_add_cipher_key/up.sql, migrations/postgresql/2023-10-21-221242_add_cipher_key/up.sql, migrations/sqlite/2023-10-21-221242_add_cipher_key/up.sql, src/api/core/ciphers.rs, src/api/core/mod.rs, src/db/models/cipher.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
New versions of the bitwarden clients will very soon start using separate encryption keys for each cipher, so we need to handle those.
At the same time, I've noticed that the clients have started depending on the version value of the `/config` endpoint to do backwards compatibility checks, so I think the simplest solution for everyone would be for us to return the server version that most closely matches the features we support.
They are doing the semver checks here: 
https://github.com/bitwarden/clients/blob/3e495ab082e2152284a36bb5d2b2fb7a4060cfb3/libs/common/src/platform/services/config/config.service.ts#L116-L127
For now the only check they are doing is for version 2023.9.1 for the cipher key encryption feature that this PR implements, so we report that we support that version: …
=> Implement cipher key encryption

migrations/mysql/2023-10-21-221242_add_cipher_key/up.sql
MariaDB/MySQL doesn't like the normal `"` quotes around the column name. This needs to be a backtick **`**.
This PR changes the migration script to fix this issue.
Fixes #3993
=> Fix issue with MariaDB/MySQL migrations

.github/workflows/trivy.yml
to ensure critical and high vulnerabilties are detected quickly
=> ci: add trivy workflow

docker/docker-bake.hcl
The bake recipt was missing the single `:alpine` tag for the alpine builds when we were releasing a `stable/latest` version of Vaultwarden.
This PR fixes this by checking for those conditions and add the `:alpine` tag too.
We will keep the `:latest-alpine` also, which i find even nicer then just `:alpine`
Fixes #4035
=> Fix missing alpine tag during buildx bake

src/api/core/mod.rs
Disabled autofill-v2 as it seems to cause strange issues as reported here: https://github.com/dani-garcia/vaultwarden/discussions/4052
Also added the Vaultwarden server version back again but at a different location.
Fixes #4052
=> Disable autofill-v2

src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/organizations.rs, src/api/core/two_factor/authenticator.rs, src/api/core/two_factor/duo.rs, src/api/core/two_factor/email.rs, src/api/core/two_factor/mod.rs, src/api/core/two_factor/protected_actions.rs, src/api/core/two_factor/webauthn.rs, src/api/core/two_factor/yubikey.rs, src/api/mod.rs, src/config.rs, src/db/models/two_factor.rs, src/mail.rs, src/static/templates/email/protected_action.hbs, src/static/templates/email/protected_action.html.hbs
Since the feature `Login with device` some actions done via the web-vault need to be verified via an OTP instead of providing the MasterPassword.
This only happens if a user used the `Login with device` on a device which uses either Biometrics login or PIN. These actions prevent the athorizing device to send the MasterPasswordHash. When this happens, the web-vault requests an OTP to be filled-in and this OTP is send to the users email address which is the same as the email address to login.
The only way to bypass this is by logging in with the your password, in those cases a password is requested instead of an OTP.
In case SMTP is not enabled, it will show an error message telling to user to login using there password.
Fixes #4042
=> Add Protected Actions Check

src/api/notifications.rs
When a WebSocket connection was closing it was sending a message after it was closed already. This generated an error in the logs. While this error didn't harm any of the functionallity of Vaultwarden it isn't nice to see them of course.
This PR Fixes this by catching the close message and breaks the loop at that point. This prevents the `_` catch-all from replying the close message back to the client, which was causing the error message.
Fixes #4090
=> Prevent generating an error during ws close

.github/CODEOWNERS, .github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/releasecache-cleanup.yml, .github/workflows/trivy.yml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml
- Updated Rust to v1.74.0
- Updated all crates (where possible)
- Changed release profile to use
* fat lto
* 1 codegen-unit This should optimize a bit for speed and a lot for size ~15MB smaller
- Updated Github actions to use caching for the bake process
- Added a schedule to clean the cache every week to prevent stale Debian/Alpine base images
- During the release action, the Alpine/static binaries are added as artifects. Later we could also automatically add them to the releases maybe.
- Added CODEWONERS to prevent unchecked changes to github actions workflows
=> Update Rust, Crates, Profile and Actions

Cargo.lock, Cargo.toml, build.rs, docker/healthcheck.sh, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/db/models/organization.rs, src/util.rs
If someone is using a `.env` file or configured the `ENV_FILE` variable
to use that as it's configuration, this was missed by the healthcheck.
So, `DOMAIN` and `ROCKET_TLS` were not seen, and not used in these cases.
This commit fixes this by checking for this file and if it exists, then
it will load those variables first.
Fixes #4112
---
Previously during a `delete_file` check we also tried to delete the
parent directory and ignored all errors, like not being empty for
example.
Since this function is called `delete_file` and does not mention
anything in regards to a directory i have removed that code and it will
now only delete the file and leave the rest as-is.
If this somehow is still needed or wanted, which i do not think we want,
then we should create a new function.
Fixes #4081
--- …
=> Several small fixes for open issues

.github/workflows/build.yml, Cargo.lock, Cargo.toml, build.rs, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.j2, rust-toolchain.toml
For some reason still not known, the `.git` directory was not copied into the container. I think buildkit (buildx) did this by default before, and stopped this with newer versions.
This PR fixes this by also touching `build.rs` besides `src/main.rs`.
This PR also updates Rust to v1.74.1 and some crates, including the latest version of Alpine 3.19.
Fixes #4150
=> Fix the version string

src/api/identity.rs, src/auth.rs, src/db/models/device.rs
Large JWT's could cause issue because of header or body sizes of the HTTP request could get too large when you are a member of a lot of organizations.
This PR removes these specific keys since they are not used either client side or server side.
Because Bitwarden does add these in there JWT's i would suggest to keep the code we had but then commented out as a reference.
Removing it and searching for this when needed would be a waist of time.
Fixes #4156
=> Decrease JWT Refresh/Auth token

Cargo.toml
OpenWRT (https://openwrt.org) is a project which builds and distributes firmware for embedded devies like routers, access points, and so on. These devices are usually very limited in terms of storage. Therefore, **optimizing binaries for size** at the cost of execution speed is usually desired. As I intend to provide a vaultwarden package for OpenWRT this change would help significantly.
This PR adds an additional build-target, namely "release-micro", which implements several parameters which optimize in favor of binary size.
The following parameters were chosen:
- opt-level "z": Optimize for size with disabled loop vectorization
- strip "symbols": Strip debuginfo and symbols from binary
- lto "fat": Enable link-time optimizations across all crates
- codegen-units 1: Disable …
=> Add additional build target which optimizes for size

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml, src/api/core/mod.rs
- Updated Rust to v1.75.0
- Fixed warning generated by latest version of Rust
=> Update Rust and Crates

src/db/models/organization.rs
There was an error in the single org policy check to determine how many users there are in an org. The `or` check was at the wrong location in the DSL.
This is now fixed.
Fixes #4205
=> Fix Single Org Policy check

.env.template, src/api/core/mod.rs, src/config.rs, src/util.rs
Instead of statically disabling autofill-v2 and enabling fido2-vault-credentials let the user decide which features to en-/disable.
By default the above mentioned standard values are used but can be changed by specifying a comma separated list of any of the currently available in the bitwarden clients: https://github.com/bitwarden/clients/blob/00fd45a678956c76dde6caa76e8ba266c204471c/libs/common/src/enums/feature-flag.enum.ts
~To disable a feature just prepend an exclamation mark (!). The default value is: `!autofill-v2,fido2-vault-credentials`~
=> Allow customizing the featureStates

src/db/models/cipher.rs, src/db/models/organization.rs
I bet it can be done with a single query within the `find_by_cipher_and_org` function but I didn't managed to get it work (the `filter` gets complicated, adding `groups::access_all.eq(true)` works but I can't figure out how to check if the user is in a group that has access to the collection).
Basically it retrieves the users having access to the cipher with a group that either has access to all collections or is bound to the cipher's collection. Then users uuid are used to push changes to clients.
=> Fix #3413: push to users accessing the collections using groups

.env.template, src/api/push.rs, src/config.rs
Following https://github.com/dani-garcia/vaultwarden/discussions/3731
Add the possibility of choosing between data region us or eu for push notifications
=> US or EU Data Region Selection

src/api/core/emergency_access.rs, src/config.rs
This PR addresses the suggestion https://github.com/dani-garcia/vaultwarden/discussions/4223 by @zacknewman so that the client does not throw an exception.
=> improve emergency access when not enabled

src/api/core/organizations.rs
The bulk collection delete seems to have removed the extra org_id in the posted data. Now we only use the org_id from the path.
Fixes #4253
=> Fix bulk collection deletion

src/static/templates/admin/diagnostics.hbs
=> fix: use black text for update badge (better contrast)

src/api/core/ciphers.rs, src/api/core/organizations.rs, src/db/models/cipher.rs, src/db/models/collection.rs
while working on #3754 I noticed that if I disable groups the collections and ciphers that I had access to via a group are still shown because the queries don't take into account if the groups are enabled or not.
=> prevent side effects if groups are disabled

.github/workflows/build.yml, .github/workflows/trivy.yml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
- Update GitHub Actions
- Updated web-vault to v2024.1.2
=> Update crates, web-vault and GHA

src/api/core/accounts.rs
Hey,
So, when working on the SSO PR, I introduced a bug with the `SSO_ACCEPTALL_INVITES`  which made possible for a user to be `UserOrgStatus::Accepted` while not yet having a public key.
What made the issue worse is that then the admin can confirm the user while using a public key with a `null` value.
When the user finally login the vault will be broken and does not load.
So of course fixed the issue, but this change would make it so that the admin can't confirm the user and prevent entering a broken state. Sadly the error is not displayed (be it a `400` or `404`).
Lastly this would be more inline with the official server implementation which In believe throw a `NotFoundException` in this [case](https://github.com/bitwarden/server/blob/aeca1722fc61680715e5b439aea8bf6cc4e7b300/src/Api/Cont …
=> Return 404 when user public_key is empty

.env.template, Cargo.lock, Cargo.toml, migrations/mysql/2024-01-12-210182_change_attachment_size/up.sql, migrations/postgresql/2024-01-12-210182_change_attachment_size/up.sql, migrations/sqlite/2024-01-12-210182_change_attachment_size/up.sql, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/organizations.rs, src/api/core/sends.rs, src/api/core/two_factor/authenticator.rs, src/api/core/two_factor/mod.rs, src/api/core/two_factor/webauthn.rs, src/api/mod.rs, src/config.rs, src/db/models/attachment.rs, src/db/models/send.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs, src/util.rs
- Add separate Send limit, previously it was using the Attachment limit, which wouldn't work correctly
- Change file sizes in attachment to be i64, both in code and in the database, to limit the amount of number casting
- Switched number operations to use checked operations
Haven't tested MySQL or Postgres but I think the migrations are correct.
=> Improve file limit handling

src/api/core/ciphers.rs
The min/max were reversed with the `add` and `sub` functions. This caused the files to always be out of bounds in the check.
Fixes #4281
=> Fix attachment upload size check

src/config.rs
As mentioned in the PR https://github.com/dani-garcia/vaultwarden/pull/4168#discussion_r1431892943 we have to `err!` to disallow unknown flags otherwise all flags are allowed.
I've just tested it and the warning is not even displayed. Might be the same reason as
https://github.com/dani-garcia/vaultwarden/blob/890e668071cffe2833834348e19bbef3c061d014/src/config.rs#L128
=> err on invalid feature flag

src/api/identity.rs
Don't try to register a push device when the device is new
It will be registered when the push token is saved
fixes #4296
=> fix push device registration

docker/healthcheck.sh
It seems Debian based images see the `.env` file in the `pwd` path, but sourcing it via `. .env` breaks. It does work if you provide the full path `/.env`. Changed the default to `/.env`.
Alpine does not have an issue with both ways.
Fixes #4295
=> Fix healthcheck when using .env file

Cargo.lock, Cargo.toml
Because handlebars yanked a version which was there for a few days, we need to downgrade this crate. In this process update all the others.
Fixes #4307
=> Update crates to fix new builds

.github/workflows/release.yml, .github/workflows/releasecache-cleanup.yml
- Update the workflow GH Actions.
- Configured the release workflow to always run on main/tag as discussed in #4226
Closes #4226
=> Update GHA Workflows

Cargo.lock, Cargo.toml, build.rs, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml, src/api/core/events.rs, src/api/core/organizations.rs, src/main.rs
- Updated Rust to v1.76.0
- Updated web-vault to v2024.1.2b
- Fixed some Clippy lints
- Moved lint check configuration to Cargo.toml
- Fixed issue with Reset Password Enrollment when logged-in via device
- Added a `release-low` profile to build Vaultwarden on systems with low system resources
=> Update Rust, crates and web-vault

Cargo.toml
It seems (as disscusses here #4320) a single codegen unit makes it still crash. This sets it to the default 16 Rust uses for the release profile.
=> Change the codegen-units for low resources

.env.template
This commit addresses an issue in the Vaultwarden project's `.env.template` file where comments explaining environment variable options were incorrectly placed on the same line as the variable definitions. Systemd's `EnvironmentFile` directive only recognizes comment symbols (#) at the beginning of a line. Therefore, explanatory comments placed on the same line as environment variable definitions can lead to misinterpretations or errors when the file is used in a systemd service file.
=> Fix env templateto ensure compatibility with systemd's EnvironmentFile parsing

src/api/core/events.rs
I think `// Collection events` was repeated twice
=> Fix comment in events.rs

src/auth.rs, src/config.rs, src/db/models/attachment.rs, src/main.rs, src/util.rs
Based on the discussion on #4083
=> Improve JWT RSA key initialization and avoid saving public key

.env.template, Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/mod.rs, src/api/notifications.rs, src/config.rs, src/error.rs, src/main.rs
Remove our custom WebSocket code and only use the Rocket code. Removed all options in regards to WebSockets
Added a new option `WEBSOCKET_DISABLED` which defaults too `false`. This can be used to disable WebSockets if you really do not want to use it.
Also:
- Updated crates, including Rocket to the latest merged v0.5 changes
- Removed an extra header which should not be sent for websocket connections
=> Remove custom WebSocket code

src/main.rs
This change replaces the panic when a wrong log level is used with an error message and a graceful exit.
Please note that I did not hardcode the levels, because I rather dislike hardcoding options, if there's a way to retrieve the list dynamically. ~~It makes the code by 9 lines longer, but it is more futureproof.~~
Either way, if this is not wanted, I can still hardcode the list.
see https://github.com/dani-garcia/vaultwarden/discussions/4393#discussioncomment-8656343
=> refactor: replace panic with a graceful exit

src/api/core/accounts.rs, src/static/templates/email/change_email.hbs, src/static/templates/email/change_email.html.hbs
Hey,
Was recently testing some code change around the change email code for the SSO PR and found those minor points:
- Adding a log to be able to obtain the email change token without having to configure SMTP.
- Change the language in the email change; if the user is not the one at the origin of the request then it means something fishy is going on since the master password should be required to trigger the email change.
=> Small improvements around email change

src/api/core/organizations.rs, src/db/models/group.rs
Fix #3624 by checking if the user is member of a group that has access to the collection.
=> Fix #3624: fix manager permission within groups

.env.template, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/organizations.rs, src/api/core/two_factor/email.rs, src/config.rs, src/db/models/org_policy.rs
When an organization policy requires a 2FA provider the registration via the organizations invite link should add the email address as 2FA provider. You can also skip the policy check if you set `EMAIL_2FA_ENFORCE_ON_VERIFIED_INVITE=true` (e.g. so that email provider is added to users that are invited via the `/admin` panel).
This should fix #4303, however I've also added a way to ensure that the email address will be used automatically as fallback 2FA provider whenever needed (which you have to opt in by setting `EMAIL_2FA_AUTO_FALLBACK=true`). I'd consider this an experimental feature as it would be Vaultwarden only.
If you don't want your users to enable email 2FA provider at all, you should set `_ENABLE_EMAIL_2FA=false` to disable email as 2FA provider entirely.
=> automatically use email address as 2fa provider

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
Update the web-vault to `v2024.3.0` that ships [Bitwarden's new vertical layout](https://bitwarden.com/blog/bitwarden-design-updating-the-navigation-in-the-web-app/):
Cf. https://github.com/dani-garcia/bw_web_builds/pull/157
=> update web-vault to v2024.3.1 (new vertical layout)

src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/mod.rs, src/api/core/sends.rs
Key rotation was changed since 2024.1.x.
Multiple other items were added to be rotated like password-reset and emergency-access data to be part of just one POST instead of having multiple.
See: https://github.com/dani-garcia/bw_web_builds/pull/157
=> Update Key Rotation web-vault v2024.3.x

docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.j2, docker/README.md, docker/docker-bake.hcl
There was a PR (#4370) to add i686/i386 support for Vaultwarden. That specific PR was not a viable way of adding this.
This PR adds extra architectures for Debian based containers which we will not support by default. Those images will not be build and pushed to our container registries.
Added the following architectures:
- linux/386
- linux/ppc64le
- linux/s390x
Again, there will be no major support for these architectures, but it will allow people who use these architectures to build a Debian based binary more easily
Closes #4370
=> Add extra (unsupported) container build arch's

src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/organizations.rs
(sorry about hitting publish too soon).
This PR fixes a bug where moving a cipher from a personal vault to an organization does not attach the collection ids of which the cipher is now a member. 
The front-end relies on these if the notification type is `NotificationType.SyncCipherUpdate` (https://github.com/bitwarden/clients/blob/91f1d9fb86142805d0774182c3ee6234e13946e3/libs/common/src/services/notifications.service.ts#L150) which in turn controls `isEdit` in `syncUpsertCipher` (https://github.com/bitwarden/clients/blob/91f1d9fb86142805d0774182c3ee6234e13946e3/libs/common/src/vault/services/sync/sync.service.ts#L177). If `isEdit` is `true` (we moved a cipher, we didn't create one) we need the `collectionIds` otherwise `shouldUpdate` remains `false` …
=> Pass in collection ids to notifier when sharing cipher.

src/api/core/organizations.rs, src/auth.rs, src/db/models/collection.rs
I've refactored the check if a user has access to a collection so it also takes into account access via groups (but only if `ORG_GROUPS_ENABLED=true`).
This should also return the correct result for `get_org_collection_detail` (though I'm not sure if this is used by the client).
=> improve access to collections via groups

src/api/core/accounts.rs, src/api/core/emergency_access.rs, src/db/models/emergency_access.rs, src/db/models/user.rs
When mail is disabled instead of accepting emergency access for all invited users automatically, we only accept the emergency access invitation immediately if the user already exists and has a `password_hash`. For invited users any open emergency access invitations will be accepted on registration.
Also prevent invited emergency access contacts to register if emergency access is disabled (this is only relevant for when mail is enabled, if mail is disabled they would have an Invitation entry).
This should address the issue reported in https://github.com/dani-garcia/vaultwarden/discussions/3183 without any breaking changes (i.e. this will not disable the emergency access feature when mail is disabled).
=> fix emergency access invites

docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.j2
Move some ARGs closer to the build stage (potentially improving caching):
Example: I usually set VW_VERSION to be the latest commit hash, without this change I'd have to also rebuild the dependencies even if they didn't change since the previous layers would get invalidated.
Remove redundant COPY commands:
They can be combined, no point in using extra layers if it can be avoided.
Remove redundant RUN command:
apt-get and xx-apt-get commands can be moved into the same RUN command, thus saving another layer.
Move CARGO_HOME's "&&" operator to the first line (improves consistency)
=> Optimize Dockerfiles

src/api/core/public.rs
Vaultwarden is currently unable to handle the Bitwarden Directory Connector when the base domain includes a path prefix.
Example:
`DOMAIN=https://example.com/` -> works
`DOMAIN=https://example.com/vault/` -> doesn't work
Vaultwarden rejects the token issued seconds before with the error message `"Token not issued by this server"`.
This message is thrown when the token issuer check fails. When a organization api token is issued, the iss attribute follows the scheme `"domain_origin|scope"`. But when the issuer is checked in api/core/public.rs, the iss attribute is expected to contain `"domain|scope"`.
When using a domain with path prefix this leads to conflicts. To fix this I replaced the domain check through a domain_origin check as issued in auth.rs.
=> Fix public api for domains with path prefix

src/api/core/public.rs, src/db/models/group.rs
should fix [Group support and directory connector within multiple organisations](https://vaultwarden.discourse.group/t/group-support-and-directory-connector-within-multiple-organisations/3659?u=stefan0xc)
=> differentiate external groups by organization id

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml, src/auth.rs
Updated rust to 1.79, and removed some unused values in the Header guards that Clippy was complaining about not being used anywhere.
=> Update rust and remove unused header values

build.rs, src/db/models/attachment.rs, src/db/models/collection.rs
I was building vaultwarden with the latest rust nightly and was met with a couple of build errors/warnings.
- Some `unknown cfg` warnings about the cfg's that we define based on features, which I disabled in the build.rs file
- Some type inference errors, where a couple of functions were inferring the `!` type instead of `()`. I'm not sure if this is a transient error or will become a hard error in a future stable release, but it was easy enough to solve.
This was using nightly `2024-06-18`
=> Fix some nightly build errors

src/api/core/ciphers.rs
The new android app is sending PascalCase for these two values. Ideally this will be updated in the app but it's an easy fix from our side for now. Using `serde(alias)` it will check both the camel case and pascal case versions.
=> Fix cipher creation on new android app

docker/Dockerfile.alpine, docker/Dockerfile.j2
- libatomic linking for armv6 has been fixed in mimalloc v0.1.42
For reference: https://github.com/purpleprotocol/mimalloc_rust/commit/446fc231151cfab485b0ac7d5178baf797799dda
=> Remove mimalloc workaround

src/db/models/cipher.rs, src/db/models/organization.rs
Collections were not visible in the organization view.
This was because the `flexibleCollections` was set to `true`
Found an issue with loading some old created Secure Notes which had `{}` or `{"type":null}` as there `data` value.
This isn't allowed. When detected, replace it with `{"type":0}`
Fixes #4682
Fixes #4590
=> Fix collections and native app issue

src/api/core/ciphers.rs, src/api/core/folders.rs
During import you are able to select an existing folder, or with Bitwarden exports it can contain existing folders already. In either case it didn't matter, we always created new folders.
Bitwarden uses the same UUID of the selected or existing folders if they are already there.
This PR fixes this by using the same behaviour.
Fixes #4700
=> Fix duplicate folder creations during import

src/api/core/ciphers.rs, src/db/models/cipher.rs, src/db/models/collection.rs
join group infos assigned to a collection to check whether user has been given access to all collections via any group or they have access to a specific collection via any group membership
fixes #4588
=> add group support for Cipher::get_collections()

.github/workflows/release.yml
- faster builds than with gzip (the default)
Quick comparison I did (vaultwarden built for 3 platforms: linux/amd64, linux/amd64/v3 and linux/arm64):
gzip
• No cache: 22m 7s
• Cached: 11m 20s
zstd:
• No cache: 19m 36s
• Cached: 10m 48s
=> Switch registry cache compression algorithm to zstd

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
- Updated the crates Removed the patch for mimalloc
- Updated the web-vault to v2024.5.1b
The reason for not updating to v2024.6.x is that there are several items not working correctly or need some more research.
=> Update crates and web-vault

src/api/core/accounts.rs, src/api/core/emergency_access.rs, src/db/models/emergency_access.rs
- Add missing `Headers` parameter for some functions This allowed any request from allowing these endpoints by not validating the user correctly.
- Changed the functions to retreive the emergency access record by using the user uuid which calls the endpoint, instead of validating afterwards. This is more secure and prevents the need of an if check.
=> Some fixes for emergency access

src/db/models/organization.rs
this should fix #4707 and other related issues from using the free tier plan (like the totp display not working in the admin console).
Fixes #4707
=> use a custom plan of enterprise tier to fix limits

docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.j2
as of [v1.31.0](https://github.com/dani-garcia/vaultwarden/releases/tag/1.31.0), this is no longer needed
=> chore: Dockerfile to Remove port 3012

src/db/models/cipher.rs
Fixes #4719 
Fixes bug where the value of my notes is an empty string, and thus doesn't pass the check for an empty array.
This adds empty strings to the if condition.  Tested with the mobile app and this fixes my issue
=> Fix bug where secureNotes is empty

.env.template, src/api/admin.rs, src/api/core/mod.rs, src/api/core/two_factor/duo.rs, src/api/icons.rs, src/api/mod.rs, src/api/push.rs, src/config.rs, src/error.rs, src/http_client.rs, src/main.rs, src/util.rs
In an effort to defend against rebinding attacks more thoroughly, I've done some changes to the HTTP client.
- Extracted it from `util` to a separate file, as it was getting a bit too crowded there
- Removed `get_reqwest_client` and replaced it with `make_http_request`, which will check the provided URL for possible blacklisted domains/ips or non-global IPs, when relevant.
- Added the custom DNS resolver to all HTTP clients, not just `icons`
- Added a redirect policy that checks the targets for possible blacklisted domains/ips or non-global IPs. This is enabled for all HTTP clients as well
- Renamed both `ICON_BLACKLIST_` settings to `HTTP_REQUEST_BLACKLIST_*`, to better reflect that this should affect more than just the `icons` endpoints. We're still reading the old values for backwards …
=> Improved HTTP client

src/api/admin.rs, src/auth.rs, src/config.rs, src/static/scripts/admin.js, src/static/scripts/admin_diagnostics.js, src/static/scripts/admin_settings.js, src/static/scripts/admin_users.js, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
- Updated datatables
- Set Cookie Secure flag if the connection is https
- Prevent possible XSS via Organization Name
Converted all `innerHTML` and `innerText` to the Safe Sink version `textContent`
- Removed `jsesc` function as handlebars escapes all these chars already and more by default
=> Update admin interface

src/auth.rs, src/main.rs
Sometimes an RSA Key file could be read only.
We currently failed because we also wanted to write. Added an extra check if the file exists already and is not 0 in size. If it does already exists and is larger then 0, then open in read only mode.
Fixes #4644
=> Fix for RSA Keys which are read only

src/api/core/two_factor/email.rs
The new native android app still seems to send PascalCase entries for Email 2FA. Added aliasses for these keys.
Tested all other 2FA's (Except Duo, which might be fixable via #4637) and they all work fine using the Native Android Beta v2024.7.0 version.
Fixes #4713
=> Fix Email 2FA login on native app

Cargo.lock, Cargo.toml, src/config.rs
- fixes GHSA-q445-7m23-qrmw by updating openssl to version 0.10.66
=> Update crates & fix crate vulnerability

docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.j2
- they seem to have started appearing with buildx v0.16.0
Alpine warnings:
```
13 warnings found (use --debug to expand):
- FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64" (line 37)
- FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64" (line 38)
- RedundantTargetPlatform: Setting platform to predefined $TARGETPLATFORM in FROM is redundant as this is the default behavior (line 133)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 35)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 36)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 42)
- FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64" …
```
=> Fix Dockerfile linter warnings

.env.template, src/config.rs, src/main.rs
Useful for either silencing some target when running in `debug` or switching `debug` only for a specific target,
With this a good chunk of the default overrides could be moved to the conf, cf:
```rust
// Hide unknown certificate errors if using self-signed
.level_for("rustls::session", log::LevelFilter::Off)
// Hide failed to close stream messages
.level_for("hyper::server", log::LevelFilter::Warn)
// Silence Rocket `_` logs
.level_for("_", rocket_underscore_level)
.level_for("rocket::response::responder::_", rocket_underscore_level)
.level_for("rocket::server::_", rocket_underscore_level)
.level_for("vaultwarden::api::admin::_", rocket_underscore_level)
.level_for("vaultwarden::api::notifications::_", rocket_underscore_level)
// Silence Rocket logs
.level_for("rocket::launch", …
```
=> Allow to override log level for specific target

.env.template, migrations/mysql/2024-06-05-131359_add_2fa_duo_store/down.sql, migrations/mysql/2024-06-05-131359_add_2fa_duo_store/up.sql, migrations/postgresql/2024-06-05-131359_add_2fa_duo_store/down.sql, migrations/postgresql/2024-06-05-131359_add_2fa_duo_store/up.sql, migrations/sqlite/2024-06-05-131359_add_2fa_duo_store/down.sql, migrations/sqlite/2024-06-05-131359_add_2fa_duo_store/up.sql, src/api/core/two_factor/duo.rs, src/api/core/two_factor/duo_oidc.rs, src/api/core/two_factor/mod.rs, src/api/identity.rs, src/auth.rs, src/config.rs, src/db/models/mod.rs, src/db/models/two_factor_duo_context.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs, src/main.rs
This adds support for MFA using Duo's "Universal Prompt".
On March 30th, 2024, the Duo MFA integration that Vaultwarden uses, the 'Traditional Prompt' was end-of-lifed. While Duo's API continues to allow the traditional prompt to be used in some cases, it is entirely unsupported, and it will eventually stop working. Some Vaultwarden users have already begun reporting that their Duo API keys are no longer functional in Vaultwarden. Bitwarden introduced Universal Prompt support in release 2024.2.3 on March 5th.
Duo's Universal Prompt uses the OIDC Authorization Code flow. This flow requires us to pack information about the authentication we want to be prompted for MFA into an authorization request (a JWT signed with a secret key provided by Duo) and send the user to their service, where MFA …
=> Add support for MFA with Duo's Universal Prompt

.env.template, src/api/core/ciphers.rs, src/config.rs, src/db/models/cipher.rs
This PR adds a config option to allow the note size to increase to 100_000, instead of the default 10_000. Since this might cause issues with the clients (in the future), and will cause issues with importing into a Bitwarden server, i added warnings regarding this.
Closes #3168
=> Allow to increase the note size to 100_000

src/api/core/ciphers.rs
This should fix the issues reported in #4767 where an entry added via the native iOS app cannot be decrypted:
The problem seems to be that the iOS app sends an [organizationID](https://github.com/bitwarden/ios/blob/3ec242eb73735608fbed32837303b22ceb531abb/BitwardenShared/Core/Vault/Models/Request/CipherRequestModel.swift#L47) which serde fails to deseralize and because it's an optional argument adding the cipher will not fail but it will be added incorrectly to your personal vault, unless you have disabled personal ownerships. So to prevent such corruptions from occurring again I've added a reverse sanity check, just in case some other clients send the organization_id in an unrecognizable format.
=> fix issue with adding ciphers to organizations on native ios app

.env.template
- also update the European Union related information for a working setup
- fixes https://github.com/dani-garcia/vaultwarden/issues/4609
=> Rewrite the Push Notifications section in the configuration template

src/api/core/organizations.rs
As noted here https://github.com/dani-garcia/vaultwarden/issues/4775#issuecomment-2251024214 the `access_all` flag has been removed in the newer web-vaults resulting in an error when editing a user:
```
[2024-08-01 13:29:25.313][vaultwarden::api::core::organizations::_][WARN] Data guard `Json < EditUserData >` failed: Parse("{\"collections\":[{\"id\":\"64256828-6251-4bef-8dee-2128b63f520a\",\"readOnly\":true,\"hidePasswords\":false,\"manage\":false}],\"groups\":[],\"permissions\":{\"response\":null},\"type\":0}", Error("missing field `accessAll`", line: 1, column: 169)).
```
Note: Since newer web-vaults don't have the `access_all` flag anymore, it will be removed if you update a user with that permission. Due to the new view admins/owners will also not see all items in the password …
=> make access_all optional

src/util.rs
- needed to match Bitwarden, some of the feature flags might have uppercase characters (for example: ```PM-4154-bulk-encryption-service```)
=> Remove lowercase conversion for featureStates

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, src/api/core/mod.rs, src/api/core/organizations.rs, src/db/models/cipher.rs
- Updated web-vault to v2024.6.2 This version is currently the latest version compatible with our API implementation. For newer versions we need more code updates to make it compatible. Thanks to @stefan0xC this version fixes #4628
- Added a small fix to prevent errors in the Vaultwarden and Client logs. The v2024.6.2 web-vault calls an endpoint with invalid arguments. If this happens we ignore the call and just return an Ok.
- Added the bulk-collection endpoint (Though not yet available in v2024.6.2)
Fixes #4628
=> Update crates, web-vault and fixes

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
Updated web-vault to v2024.6.2b to include a missing patch.
=> Updated web-vault to v2024.6.2b

src/api/core/organizations.rs, src/db/models/organization.rs
- All users were able to request organizational details from any org, even if they were not a member (anymore). Now it will check if that user is a member of the org or not.
- The `/organization/<uuid>/keys` endpoint returned also the private keys. This should not be the case. Also, according to the upstream server code the endpoint changed, but the clients do not seem to use it. I added it anyway just in case they will in the future.
- Also require a valid login before being able to retreve those org keys. Upstream does not do this, but i see no reason why not.
Fixes: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-39925
=> Fix data disclosure on organization endpoints

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/releasecache-cleanup.yml, .github/workflows/trivy.yml
- Set the buildx parallel back to 2 again, 3 still produces issues
- Updated several workflows to use Ubuntu 24.04 Omitted the `build` workflow to keep the libraries the same as the Debian container images.
- Updated all actions
- Added `docker build --check` to the hadolint workflow
=> Update GitHub Action Workflows

src/api/core/two_factor/duo_oidc.rs
The URL crate treats `https://domain.tld/path` differently then `https://domain.tld/path/` the latter will make sure a `.join()` will append the given path instead of using the base as a relative path.
Fixes #4858
=> Fix Duo Redirect not using path

src/api/core/organizations.rs, src/db/models/collection.rs, src/db/models/group.rs, src/db/models/organization.rs
The web-vault v2024.6.2 we use needs some extra information to allow managers to actually be able to manage collections.
The v2024.6.2 web-vault has somewhat of a mixture of the newer roles and older manager roles. To at least fix this for the web-vault we bundle these changes will make the manager able to manage.
For future web-vaults we would need a lot more changes to be done to fix this in a better way though.
Fixes #4844
=> Fix manager in web-vault v2024.6.2 for collections

src/api/core/two_factor/duo.rs
Hey,
Was checking the OIDC pr change and realized that this change was still present.
I forgot to include it in the recent https://github.com/dani-garcia/vaultwarden/pull/4779.
Note that for stronger guaranty that the email is correctly formatted (would apply to `duo_oidc.validate_duo_login` too):
- Could change the parameter to `User`.
- Could define a custom type for a formatted email and wrap it.
=> Remove unecessary email normalization

src/api/admin.rs, src/static/scripts/admin.js
Since the change to camelCase variables the error messages in the Vaultwarden Admin were not shown correctly anymore.
This PR fixes this by changing the case of the json key's. Also updated the save and delete of the config to provide a more descriptive error instead of only `Io` or which ever other error might occure.
Fixes #4834
=> Fix Vaultwarden Admin page error messages

src/api/core/ciphers.rs
when cloning an item from an organization to the personal vault the client sends the collection id of the cloned item
cf. https://vaultwarden.discourse.group/t/moving-logins-between-organisations-clone-or-move-doesnt-work/3909
=> remove overzealous sanity check

.dockerignore
Hey,
Recently mistakenly added `.git` to the `.dockerignore` in another PR because I thought it might be responsible for unnecessary rebuild (it was not anyway).
But with so many blacklisted element I think switching to a whitelist style is simpler.
=> Switch to Whitelisting in .dockerignore

Cargo.lock, Cargo.toml
- Fixed MSRV to actually be N-2
- Changed some features to use the `dep:` prefix. This is needed for edition-2024 anyway although that will be a while before we can use that.
This also updates Diesel which seems to have a possible CVE.
=> Update crates (GHSA-wq9x-qwcq-mmgf)

docker/start.sh
To provide a way to add more security regarding file/folder permissions this PR adds a way to allow setting a custom `UMASK` variable.
This allows people to set a more secure default like only allowing the owner the the process/container to read/write files and folders.
Examples:
- `UMASK=022` File: 644 | Folder: 755 (Default of the containers)
This means Owner read/write and group/world read-only
- `UMASK=027` File: 640 | Folder: 750
This means Owner read/write, group read-only, world no access
- `UMASK=077` File: 600 | Folder: 700
This means Owner read/write and group/world no access
resolves #4571
=> Allow custom umask setting

src/api/identity.rs
We didn't returned the master password policy for the user. If the `Require existing members to change their passwords` check was enabled this should trigger the login to show a change password dialog.
All the master password policies are merged into one during the login response and it will contain the max values and all `true` values which are set by all the different orgs if a user is an accepted member.
Fixes #4507
=> Allow Org Master-Pw policy enforcement

.env.template, src/api/core/organizations.rs, src/config.rs
Bitwarden only allows the Reset Password policy to be set when the Single Org policy is enabled already. This PR adds a check so that this can be enforced when a config option is enabled.
Since Vaultwarden encouraged to use multiple orgs when groups were not available yet we should not enable this by default now. This might be something to do in the future.
When enabled, it will prevent the Reset Password policy to be enabled if the Single Org policy is not enabled. It will also prevent the Single Org policy to be disabled if the Reset Password policy is enabled.
Fixes #4855
=> Allow enforcing Single Org with pw reset policy

src/api/admin.rs, src/db/mod.rs, src/main.rs, src/util.rs
Many users request to add the sqlite3 binary to the container image. This isn't really ideal as that might bring in other dependencies and will only bloat the image. There main reason is to create a backup of the database.
While there already was a feature within the admin interface to do so (or by using the admin API call), this might not be easy.
This PR adds several ways to generate a backup.
1. By calling the Vaultwarden binary with the `backup` command like:
- `/vaultwarden backup`
- `docker exec -it vaultwarden /vaultwarden backup`
2. By sending the USR1 signal to the running process like:
- `kill -s USR1 $(pidof vaultwarden)`
- `killall -s USR1 vaultwarden`
This should help users to more easily create backups of there SQLite database.
Also added the Web-Vault version number when …
=> Add a CLI feature to backup the SQLite DB

src/api/admin.rs, src/api/core/organizations.rs, src/api/core/public.rs, src/mail.rs, src/static/templates/email/send_org_invite.hbs, src/static/templates/email/send_org_invite.html.hbs
With the new web-vault `web-v2024.6.2` the organization invitation logic was rewritten (had a look since organization invitation is now working even with sso :tada:).
Discovered that there were additional parameters that were not used such as `orgUserHasExistingUser` which allows to control if the user is redirected to the create account or login page (Cf  [web-v2024.6.2/accept-organization.component.ts](https://github.com/bitwarden/clients/blob/web-v2024.6.2/apps/web/src/app/auth/organization-invite/accept-organization.component.ts#L69), but this already existed before).
The additional `orgSsoIdentifier` parameter could then be added to the SSO PR.
=> Add orgUserHasExistingUser parameters to org invite

src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/organizations.rs, src/db/models/cipher.rs
This should fix syncing with the new native clients.
- Filter out password history items which have `null`
- Redesigned the Secure Note Type check to be more robust
- Check for `null` passwords in history during import (or key rotation)
This should not be an issue during the key rotation, since we do not return the invalid password history items anymore.
Fixes #4870
Fixes #4921
=> Fix sync with new native clients

src/api/core/ciphers.rs
For some strange reason the native clients send `CollectionIds` instead of `collectionIds` for updating the collection. Added an alias to allow this.
Fixes an issue reported via Matrix.
=> Fix collection update from native client

src/db/models/cipher.rs
It seemed to have been possible to have `null` date values. This PR fixes this by setting the epoch start date if either the date does not exists or is not a string.
This should solve sync issues with the new native mobile clients.
Fixes https://github.com/dani-garcia/vaultwarden/pull/4932#issuecomment-2357581292
=> Fix Pw History null dates

src/api/core/accounts.rs, src/db/models/org_policy.rs
Email as 2FA provider has not automatically been setup by default for new invitations when the 2FA required policy was enabled because I did not check the correct uuid.
=> fix 2fa policy check on registration

migrations/mysql/2024-09-04-091351_use_device_type_for_mails/down.sql, migrations/mysql/2024-09-04-091351_use_device_type_for_mails/up.sql, migrations/postgresql/2024-09-04-091351_use_device_type_for_mails/down.sql, migrations/postgresql/2024-09-04-091351_use_device_type_for_mails/up.sql, migrations/sqlite/2024-09-04-091351_use_device_type_for_mails/down.sql, migrations/sqlite/2024-09-04-091351_use_device_type_for_mails/up.sql, src/api/core/two_factor/mod.rs, src/api/identity.rs, src/db/models/two_factor_incomplete.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs, src/mail.rs, src/static/templates/email/incomplete_2fa_login.hbs, src/static/templates/email/incomplete_2fa_login.html.hbs, src/static/templates/email/new_device_logged_in.hbs, src/static/templates/email/new_device_logged_in.html.hbs
- match Bitwarden behaviour
- remove upcase_first, no longer needed and it would also interfere with device types like iOS, macOS
Examples:
Chrome Extension
Before -> New Device Logged In From/Incomplete Two-Step Login From/Device Type: Chrome
After -> New Device Logged In From/Incomplete Two-Step Login From/Device Type: Chrome Extension
Poco F3 (shows up as M2012K11AG)
Before -> New Device Logged In From/Incomplete Two-Step Login From/Device Type: M2012K11AG
After -> New Device Logged In From/Incomplete Two-Step Login From/Device Type: Android
=> Actually use Device Type for mails

migrations/postgresql/2024-09-04-091351_use_device_type_for_mails/down.sql, migrations/postgresql/2024-09-04-091351_use_device_type_for_mails/up.sql
postgres does [not support backtics for escaping keywords](https://wiki.postgresql.org/wiki/Things_to_find_out_about_when_moving_from_MySQL_to_PostgreSQL) so we shouldn't use them in postgres migrations. 
should fix the issue reported here: https://github.com/dani-garcia/vaultwarden/pull/4916#issuecomment-2361033931
=> remove backtics from postgresql migrations

Cargo.lock, Cargo.toml, migrations/mysql/2024-09-04-091351_use_device_type_for_mails/up.sql, migrations/postgresql/2024-09-04-091351_use_device_type_for_mails/up.sql, migrations/sqlite/2024-09-04-091351_use_device_type_for_mails/up.sql
The migration can still fail because there is no default set. If the table contains values it will fail because there is no default set. Also removed all the backticks, they only causes issues
=> Fix Device Type column for 2FA migration

src/db/models/cipher.rs
It appears that some password histories have an encrypted value on the `lastUsedDate` Instead of only checking if it is a string, also check if it is a valid RFC Date/Time String. If not, set it also to epoch 0.
=> Fix encrypted lastUsedDate

Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/organizations.rs, src/api/core/public.rs, src/api/core/two_factor/email.rs, src/api/core/two_factor/protected_actions.rs, src/api/core/two_factor/yubikey.rs, src/api/icons.rs, src/api/notifications.rs, src/auth.rs, src/config.rs, src/db/mod.rs, src/db/models/emergency_access.rs, src/db/models/organization.rs, src/db/models/user.rs, src/error.rs, src/http_client.rs, src/main.rs, src/util.rs
Added extra linting for some code styles.
Also added some of the Rust Edition 2024 lints since our MSRV does not yet support the group lint.
Once we reach 1.81.0 as MSRV we can uncomment it and use that lint.
Closes #4974
=> Add extra linting

Cargo.toml, src/main.rs
The `unix::signal` was also included during Windows compilations. This of course will not work. Fix this by only including it for `unix` targets.
Also changed all other conditional compilation options to use `cfg(unix)` instead of `cfg(not(windows))`. The latter may also include `wasm` for example, or any other future target family. This way we will only match `unix`
Fixes #5052
=> Fix compiling for Windows targets

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, Cargo.lock, Cargo.toml, src/api/core/organizations.rs, src/db/models/organization.rs
Since a newer version of the web-vault we use manager were not able to create sub collections anymore.
This was because of some missing details in the response of some json objects.
This commit fixes this by using the `to_json_details` instead of the `to_json`
Fixes #5066
Fixes #5044
- Updated all the GHA dependencies
- Configured the trivy workflow to only run on the main repo and not on forks
Also selected a random new scheduled date so it will not run at the same time as all other forks.
The two changes should help running this scan every day without failing, and also prevent the same for new or updated forks.
=> Updates and collection management fixes

src/db/models/cipher.rs
It seems the iOS clients are not able to handle the `type` key within the `fields` array when they are of the type string.
All other clients seem to handle this just fine though.
This PR fixes this by validating it is a number, if this is not the case, try to convert the string to a number, or return the default of `1`. 
`1` is used as this is the type `hidden` and should prevent accidental data disclosure.
Fixes #5069
Possibly Fixes #5016
Possibly Fixes #5002
=> Fix iOS sync by converting field types to int

src/db/models/cipher.rs
In an oversight i forgot to set the type to a hidden type if converting the int was not possible. This fixes that.
=> Fix field type to actually be hidden

src/api/core/organizations.rs, src/static/templates/email/send_org_invite.hbs, src/static/templates/email/send_org_invite.html.hbs
Ever since we changed to pass the full url as a template value handlebars now html-encodes this. This causes issues with the plain/text mails, but it also could potentially cause issues with the text/html templates.
This PR encloses the template values inside triple braces `{{{ }}}` which prevents html-encoding. Since the URL is generated via the `url` crate the values are percent-encoded anyway.
Fixes #5097
=> Fix org invite url being html encoded

src/db/models/organization.rs, src/main.rs
A possible user disclosure when you invite an user into an organization which already has an account on the same instance. This was because we always returned the user's name. To prevent this, this PR only returns the user's name if the status is accepted or higher, else we will return null. This is the same as Bitwarden does.
Resolves a reported issue.
Also resolved a new `nightly` reported clippy regarding a regex within a loop.
=> Hide user name on invite status

src/api/core/accounts.rs
Fixing a logical error in an if statement where we used `&&` which should have been `||`.
=> Fix if logic error

src/api/core/accounts.rs, src/api/identity.rs
We were checking the user uuid against the authrequest uuid, which would always fail and error out.
Fixes https://github.com/dani-garcia/vaultwarden/issues/5174
I've also noticed that we were rotating the user password hash when login in with auth request (where instead of the password, a randomly generated access code is used), this could lead to inoperable accounts.
Also tried to delete the auth requests after they were used or denied, rather than waiting for the timer to clear them up.
=> More authrequest fixes

Cargo.lock, Cargo.toml, src/api/web.rs, src/config.rs, src/static/templates/scss/user.vaultwarden.scss.hbs, src/static/templates/scss/vaultwarden.scss.hbs
Together with https://github.com/dani-garcia/bw_web_builds/pull/180 this PR will add support for dynamic CSS changes.
For example, we could hide the register link if signups are not allowed. In the future show or hide the SSO button depending on if it is enabled or not.
There also is a special `user.vaultwarden.scss` file so that users can add custom CSS without the need to modify the default (static) changes. This will prevent future changes from not being applied and still have the custom user changes to be added.
Also added a special redirect when someone goes directly to `/index.html` as that might cause issues with loading other scripts and files.
This is still a WIP to fine tune and add some more dynamic options where applicable.
=> Add dynamic CSS support

src/api/identity.rs
2FA is needed to login even when using login-with-device. If the user didn't saved the 2FA token they still need to provide this. We deleted the auth-request after validation the request, but before 2FA was triggered.
Removing the deletion of this record from that point as it will get cleaned-up automatically anyways.
=> Remove auth-request deletion

src/api/core/organizations.rs, src/db/models/group.rs
the web-vault v2024.6.2 currently cannot deal with manage permission so instead of relying on the org user type this should just default to `false` (until we implement this correctly).
should fix #5160
=> don't infer manage permission for groups

src/api/core/accounts.rs, src/api/identity.rs
- Previously we weren't setting the response date anywhere, it doesn't seem used but might as well return it just in case.
- If an authentication request was approved already, we don't allow to do it again. This is to match with what Bitwarden is doing, though I don't think there's a way to actually do it or exploit it somehow.
- Added an explicit time limit for the auth requests, previously we relied on our scheduled job to clean them up, and a user could technically disable that.
=> Some more authrequest changes

.env.template, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/organizations.rs, src/auth.rs, src/config.rs, src/db/models/cipher.rs
Added support for the new SSH item key type in desktop 2024.12+
To test it, you need a desktop build from `bitwarden/clients:main`, and to enable the feature flags on server.
=> Support SSH keys on desktop 2024.12

src/api/core/ciphers.rs, src/api/core/organizations.rs, src/api/core/two_factor/duo_oidc.rs
This fixes an issue with collections be duplicated same as was an issue with folders. Also made some optimizations by using HashSet where possible and define the Vec/Hash capacity. And instead of passing objects only use the UUID which was the only value we needed.
Also found an issue with importing a personal export via the Org import where folders are used. Since Org's do not use folder we needed to clear those out, same as Bitwarden does.
Fixes #5193
=> Fix Org Import duplicate collections

src/api/push.rs
The new native mobile clients seem to use PascalCase for the push payload. Also the date/time could cause issues.
This PR fixes this by formatting the date/time correctly and use PascalCase for the payload key's I now receive cipher updates and login-with-device requests again.
Fixes #5182
=> Fix push not working

src/api/core/ciphers.rs, src/db/models/cipher.rs, src/db/models/mod.rs
The `reprompt` value somehow sometimes has a value of `4`. This isn't a valid value, and doesn't cause issues with other clients, but the native clients are more strict.
This commit fixes this by validating the value before storing and returning.
Fixes #5237
=> Fix another sync issue with native clients

src/config.rs
The following item in the support string should be masked as well, because it reveals the domain:
```
"_smtp_img_src": "https://vault.example.com/vw_static/",
```
P.S.: `domain` is masked, so it's kind of strange that it then shows up in `_smtp_img_src`
=> feat: mask _smtp_img_src in support string

Cargo.lock, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/emergency_access.rs, src/api/core/folders.rs, src/api/core/organizations.rs, src/api/core/public.rs, src/api/core/sends.rs, src/api/core/two_factor/authenticator.rs, src/api/core/two_factor/duo.rs, src/api/core/two_factor/email.rs, src/api/core/two_factor/mod.rs, src/api/core/two_factor/webauthn.rs, src/api/identity.rs, src/api/push.rs, src/auth.rs, src/db/models/auth_request.rs, src/db/models/folder.rs, src/db/models/group.rs, src/db/models/org_policy.rs, src/db/models/send.rs, src/mail.rs
- Refactored several code to use more modern syntax
- Made some checks a bit more strict
=> Some refactoring and optimizations

.env.template, src/config.rs, src/util.rs
Bitwarden allows to use self-hosted forwarded email services. But for this to work you need to add custom URL's to the `connect-src` CSP entry.
This commit allows setting this and checks if the URL starts with `https://` else it will abort loading.
Fixes #5290
=> Allow adding connect-src entries

Cargo.lock, Cargo.toml
Use updated fern instead of patch
=> Use updated fern instead of patch

src/db/models/cipher.rs
If the uri match value is a string, empty or not it will not work. Though an empty string will cause mobile sync issues.
This commit fixes this by checking the values and if it is a string it will convert it to null.
=> Fix issues when uri match is a string

src/api/core/organizations.rs
As pointed out in #5320 we have a small bug in this call:
> For example I noticed that we are passing the wrong id here:
> 
> https://github.com/dani-garcia/vaultwarden/blob/ed4ad67e732c213beaec78970cdb68e48bee3dc1/src/api/core/organizations.rs#L910
> 
> Because in contrast to `CollectionUser` the `GroupUser::new` actually expects a different id:
> 
> https://github.com/dani-garcia/vaultwarden/blob/ed4ad67e732c213beaec78970cdb68e48bee3dc1/src/db/models/group.rs#L122
> This was probably overlooked because it's not a major issue when a user is not correctly invited to a group and it only shows up as a small warning in the logs:
> 
> ```
> [2024-12-22 21:23:47.022][request][INFO] POST /api/organizations/152bd996-19f9-40ee-b991-e52333a7e719/users/invite
> [2024-12-22 …
```
=> fix group issue in send_invite

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml
- Updated crates to the latest version
- Updated GitHub Actions to the latest version
=> Update crates and GHA

src/db/models/cipher.rs
Refactored the uri match fix to also convert numbers within a string to an int. If it fails it will be null.
If any of the mandatory ssh-key json data values are not a string or are an empty string, this will break the mobile clients.
This commit fixes this by checking if any of the values are missing or invalid and converts the json data to `null`.
It will ensure the clients can sync and show the vault.
Fixes https://github.com/dani-garcia/vaultwarden/issues/5343
Fixes https://github.com/dani-garcia/vaultwarden/issues/5322
=> Refactor the uri match fix and fix ssh-key sync

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, src/api/core/organizations.rs, src/api/web.rs, src/config.rs, src/db/models/collection.rs, src/db/models/group.rs, src/db/models/organization.rs, src/static/templates/scss/vaultwarden.scss.hbs
- Add the custom role which replaces the manager role
- Added mini-details endpoint used by v2024.12.0
These changes try to add the custom role in such a way that it stays compatible with the older manager role. It will convert a manager role into a custom role, and if a manager has `access-all` rights, it will enable the correct custom roles. Upon saving it will convert these back to the old format.
What this does is making sure you are able to revert back to an older version of Vaultwarden without issues. This way we can support newer web-vault's and still be compatible with a previous Vaultwarden version if needed.
In the future this needs to be changed to full role support though.
=> Add partial role support for manager only using web-vault v2024.12.0

src/api/core/accounts.rs, src/api/core/mod.rs
The new web-vault seems to call an extra endpoint, which looks like it is only used when passkeys can be used for login. Since we do not support this (yet), we can just return an empty data object.
=> Fix issue with key-rotate

src/static/scripts/admin_users.js
due to this hack the returned type in the overview has changed:
https://github.com/dani-garcia/vaultwarden/blob/ef4bff09eb4414117cd8ea25c809988872e2016b/src/db/models/organization.rs#L383-L385
=> fix manager role in admin users overview

src/api/core/organizations.rs, src/api/core/public.rs
Currently when a (new) user gets invited as a member to an org, and SMTP is enabled, but sending the invite fails, the user is still created.
They will only not have received a mail, and admins/owners need to re-invite the member again.
Since the dialog window still keeps on-top when this fails, it kinda invites to click try again, but that will fail in mentioning the user is already a member.
To prevent this weird flow, this commit will delete the user, invite and member if sending the mail failed.
This allows the inviter to try again if there was a temporary hiccup for example, or contact the server admin and does not leave stray users/members around.
Fixes #5349
=> Prevent new users/members to be stored in db when invite fails

Cargo.toml, src/api/notifications.rs
These changes allow building Vaultwarden using Rust v1.84.0 or newer. The two lints specifically allowed are part of the `rust_2024_compatibility` list. These two lint checks seem to have no impact on our code as far as i could tell. Also building and running both 2021 edition and 2024 edition binary works fine.
Closes #5370
=> Allow building with Rust v1.84.0 or newer

Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml
allows to merge #5260
see also: https://github.com/dani-garcia/vaultwarden/pull/5260#issuecomment-2526376903
=> build: raise msrv (1.83.0) rust toolchain (1.84.0)

src/api/core/accounts.rs, src/api/notifications.rs, src/api/push.rs
During the refactoring done in #5320 there has a buggy slipped through which changed a uuid. This commit fixes this, and also made some vars pass by reference.
Fixes #5377
=> Fix an issue with login with device

.github/workflows/release.yml
This commit will add attestation actions to sign the containers and binaries which can be verified via the gh cli. https://cli.github.com/manual/gh_attestation_verify
The binaries from both Alpine and Debian based images are extracted and attested so that you can verify the binaries of all the containers.
=> Add Attestations for containers and artifacts

.github/workflows/release.yml
Because of some changes in the bake action the version was not able to be extracted.
Fixes #5381
=> Fix version detection on bake

src/api/admin.rs, src/api/core/organizations.rs, src/api/core/public.rs, src/auth.rs, src/mail.rs
As pointed out by @Timshel the `OrganizationId` guard  and especially the `MembershipId` guard is unhappy with the `_` we use when inviting via the `/admin` panel.
By introducing a fake UUID `"00000000-0000-0000-0000-000000000000"` the guards will not fail and we can also check the claim and exit early.
=> improve admin invite

src/config.rs
#5438 seems to break setups by always requiring `smtp_from` to be a valid email, even if mail is disabled
reverted part of the change to fix #5441
=> only validate SMTP_FROM if necessary

src/auth.rs, src/db/models/organization.rs
`OrgMemberHeaders` should be available for invited members too. I've refactored the `OrgHeaders` to also get non-revoked `MembershipStatus` (Invited, Accepted, Confirmed) in order to not lower security too much.
This should allow invited members to get enrolled with automatic account recovery policy again, i.e. fix #5459
=> let invited members access OrgMemberHeaders

src/db/models/cipher.rs
The `passwordRevisionDate` format was not converted to a valid format understand by the mobile clients. Fixed this by checking if it's not `null` and then convert the timestamp to a valid format.
=> Fix passwordRevisionDate format

src/api/admin.rs, src/api/core/accounts.rs, src/api/core/events.rs, src/api/core/organizations.rs, src/db/models/event.rs
It seems like the web-vault has [some additional event types](https://github.com/bitwarden/clients/blob/web-v2025.1.1/libs/common/src/enums/event-type.enum.ts), so I've updated our list accordingly. Most of them are added only for reference  (and it seems like the web-vault does not even have support to [display all of them correctly](https://github.com/bitwarden/clients/blob/web-v2025.1.1/apps/web/src/app/core/event.service.ts) at the moment).
I've used the new ones for auth requests and to differentiate between a member leaving an organization
and getting the whole account deleted by an admin (<del>possibly this should also be when it's deleted by yourself?</del>).
Lastly I also changed it so that the membership info is also stored in the `log_user_event` for the found organizations, so …
=> add and use new event types

src/api/core/two_factor/duo.rs, src/config.rs
Looks like the web client expects different fields for duo integration.
The changes were introduced in the following commit:
https://github.com/bitwarden/clients/commit/41e1d9155850581be85d11e4b74088aa022f8381#diff-2be3b52c1ad01eac329688bca2644e0aa1f819167ed8a9d52ed57f72e18b8aa8L4
https://github.com/bitwarden/clients/commit/41e1d9155850581be85d11e4b74088aa022f8381#diff-8813d04cfcaad734e34e034e8a85eeb4a528d55aeb52b5c88e6bcbfced9fc260L13
Web client sends different fields to the API (and also receives wrong ones):
`clientSecret` instead of `secretKey` and `clientId` instead of `integrationKey`
I believe, this PR can address this.
When saving:
When loading (Client Id and Client Secret is empty):
=> Fix Duo Field Names for Web Client

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml, src/api/core/accounts.rs, src/crypto.rs
- also update the crates
- add necessary modifications for `rand` upgrade
- `small_rng` is enabled by default now
=> Update Rust to 1.84.1

src/api/icons.rs, src/util.rs
We also need to exclude the header in case we do an external_icon call.
Fixes #5535
=> Fix icon redirect not working on desktop

src/db/models/organization.rs
Because we were using the `has_full_access()` function we did not returned assigned collections for an owner/admin even if the did not have the `access_all` flag set. This commit will change that to use the `access_all` flag instead, and return assigned collections too.
While saving a member and having it assigned collections would still save those rights, and it was also visible in the collection management, it wasn't at the member it self. So, it did work, but was not visible.
Fixes #5554
Fixes #5555
=> Show assigned collections on member edit

Cargo.lock, Cargo.toml, src/db/models/collection.rs, src/db/models/event.rs, src/db/models/group.rs, src/db/models/organization.rs
Some tables were lacking an option to convert Option<> to NULL. This commit will fix that.
Also updated the crates to the latest version available.
=> Fix db issues with Option<> values and upd crates

src/api/core/sends.rs, src/db/models/device.rs
due to a bug in the CLI the filename in the form-data is not complete if the encrypted filename happens to contain a `/`
this should fix #5614
=> allow CLI to upload send files with truncated filenames

.env.template, src/config.rs
Hello!
I use split-horizon DNS to access Vaultwarden. When a client is on my home network, it talks to vaultwarden directly. When not on my home network, connections are routed through Cloudflare tunnels, which enforces a mutual TLS/client cert requirement. As such, this means that outside my home network, Bitwarden is unable to sync with Vaultwarden on Android.
Changes have been made on the Android client side to support mTLS, which were added in the 2025.2.0 release ([ref](https://github.com/bitwarden/android/releases/tag/v2025.2.0)). Namely:
- https://github.com/bitwarden/android/pull/4606
- https://github.com/bitwarden/android/pull/4701
- https://github.com/bitwarden/android/pull/4486
A server-side change was merged as well
- https://github.com/bitwarden/server/pull/5335
This PR adds …
=> Add support for mutual-tls feature flag

.env.template, src/config.rs
This adds the feature flags for bitwarden/android/pull/4711 and bitwarden/android/pull/4715. These only apply to Android at the moment unfortunately, but hopefully will come to iOS soon.
=> Add AnonAddy/SimpleLogin self host feature flag

.env.template, src/api/core/accounts.rs, src/config.rs
My suggestions for your open pull request #5215 which should be backwards compatible with the old registration flow as well as make it possible to enforce email 2fa for all users regardless of any organization policy as discussed here https://github.com/dani-garcia/vaultwarden/discussions/5662#discussioncomment-12398665.
=> fix invitation logic for new registration flow

src/api/identity.rs
Perform the user check only if verification email is used.
It was blocking the registration of invited user when email was disabled.
Edit: I wonder if it would not make sense to just always send the email ? 
It does create an unintuitive flow if the user already exists since it will fail later on, but currently it means that if the user has deleted the email he has no way to verify his email anymore.
=> Fix invited user registration without SMTP

Cargo.lock, Cargo.toml, docker/Dockerfile.debian, docker/Dockerfile.j2, docker/docker-bake.hcl
In previous attempts to get mysqlclient-sys to build and work I added some extra build variables. These are not needed if you configure pkg-config correctly. The same goes for OpenSSL btw.
This PR configures the pkg-config in the right way and allows the crates to build using the right lib paths automatically. Because of this change also the lib/include paths were not needed anymore for some architectures, except for i386.
Also updated crates again.
Fixes #5751
=> Fix debian docker building

.github/CODEOWNERS, .github/workflows/release.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, macros/Cargo.toml, macros/src/lib.rs, src/api/notifications.rs
Updated all the crates to the latest version.
We can unpin mimalloc, since the musl issues have been fixed
Also fix a RUSTSEC https://osv.dev/vulnerability/RUSTSEC-2025-0023 for tokio
Fixed some clippy lints reported by nightly.
Ensure lints and are also run on the macro crate.
This resulted in some lints being triggered, which I fixed.
Updated some GHA uses.
=> Updates and general fixes

src/api/core/organizations.rs
With client `bw_web_v2025.1.1` the `access_all` field is not sent anymore.
As such when selecting `Owner` or `Admin` the user end-up with no permissions.
=> On member invite and edit access_all is not sent anymore

src/api/web.rs
While testing the toggle for https://github.com/dani-garcia/vaultwarden/pull/5832
Realized that with the current logic Yubico is considered enabled when both client and secret are not set.
The provider is then visible but trying to enable it will result in the failure:
Cf: [yubikey.rs#L69](https://github.com/dani-garcia/vaultwarden/blob/2697fe8aba9b082aca02b48990bc65e9fc526aa4/src/api/core/two_factor/yubikey.rs#L69)
=> Fix Yubico toggle

.env.template
This is very minor, but I just noticed I made a typo in the minimum Android client versions for the AnonAddy/Addy.io and SimpleLogin self hosted feature flags from #5694.
They require a minimum of [2025.3.0](https://github.com/bitwarden/android/releases/tag/untagged-4731eaadac73f3dfbbb8), not 2025.2.0!
=> Fix minimum Android version for self-host email alias feature flags

src/static/templates/scss/vaultwarden.scss.hbs
I believe those rules are unnecessary since https://github.com/bitwarden/clients/commit/b914260705901ff32783e3eebb5ac8dab4e93a92
Last client with the `businessName` field appears to be [web-v2024.4.1](https://github.com/bitwarden/clients/blob/web-v2024.4.1/apps/web/src/app/admin-console/organizations/settings/account.component.html#L24)
=> Remove Hide Business scss rules

src/static/templates/scss/vaultwarden.scss.hbs
Starting with `web-vault` release `v2025.4.0` it will become possible to toggle the 2fa providers using a class. 
Cf https://github.com/vaultwarden/vw_web_builds/pull/15
Without this change the selector will start breaking with  `v2025.4.1` since the element switched to `bit-item` (cf [166cb75](https://github.com/vaultwarden/vw_web_builds/commit/166cb75401f4578a8d809186df3ca9e1134c0113)).
=> Toggle providers using class

src/api/identity.rs
With version `v2025.5.0` it appears that the web client is now calling the endpoint `api/two-factor/send-email-login` when an email 2FA is necessary. 
This result in sending two emails with verification codes (the first one becoming immediately invalid).
Alternative could be to check the client version, but I have not check if future extension or mobile app will have the same logic.
=> web-client now request email 2fa

src/static/templates/scss/vaultwarden.scss.hbs
by making the selector more specific to the login page the logout button on the locked screen should be visible again
cf. https://github.com/dani-garcia/vaultwarden/pull/5890#issuecomment-2916665937 for more context
=> fix css for locked screen

src/api/identity.rs
invited users (e.g. via /admin panel or org invite) should be able to register if email is disabled.
fixes #5956
=> allow signup for invited users

src/api/core/two_factor/yubikey.rs
When adding or updating yubico otp keys there were some issues with the validation. Looks like the web-vault sends all keys, not only filled-in keys, which triggered a check on empty keys. Also, we should only return filled-in keys, not the empty ones too.
Fixes #5986
=> Fix an issue with yubico keys not validating

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, macros/Cargo.toml, rust-toolchain.toml, src/api/icons.rs, src/util.rs
- Switched to rustls instead of native-tls Some dependency were already using rustls by default or without option. By removing native-tls we also have just one way of working here.
Updated favicon fetching which now is able to fetch more icons.
- Use rustls instead of native-tls This seems to work better, probably because of tls sniffing
- Use different user-agent and added several other headers
- Added SVG support. SVG Images will be sanitized first before stored or presented. Also, a special CSP for images will be sent to prevent scripts etc.. from SVG images.
=> Misc Updates and favicon fixes

src/api/core/mod.rs, src/config.rs
The recent version 2025.6.0 of the mobile application contain some helpful error reporting improvements that we can probably benefit from, but they're behind feature flags:
- `mobile-error-reporting`: When an error happens, the `An error occurred` dialog now has a `Share error log` button. This will open a system share sheet so you can send the error logs through email/github/etc.
- `enable-pm-flight-recorder`: This will allow a user to enable and share temporary event logging in the application, might be helpful to debug strange behaviors. The official help page has more info: https://bitwarden.com/help/flight-recorder/
Important to mention that both actions need to be user triggered, and they don't send the data to any server (neither Bitwarden nor Vaultwardens). The user is expected to …
=> Update flags version and enable manual error reporting

Cargo.lock, Cargo.toml, src/config.rs, src/http_client.rs
This removes a lot of duplicate client dependency bloat for roughly equivalent functionality.
Based on suggestion by @BlackDex in https://github.com/dani-garcia/vaultwarden/pull/5626#issuecomment-2926701148.
=> Use existing reqwest client for AWS S3 requests

Cargo.lock, Cargo.toml, src/db/models/cipher.rs
The new v2025.6.1 clients need the new `permissions` key/value to support deleting. By using the same flag as the current `edit` key/value we can fix this.
More fine-grained control is something we should still code, so for not this should solve those issues
Fixes #6003
Fixes #5996
=> Fix v2025.6.x clients and newer to delete items

Cargo.lock, Cargo.toml
Update crates to trigger rebuild for mysql/mariadb issue
This should trigger a new release build using the new rust-musl build images which have reverted to MariaDB Connector/C v3.4.5.
Indirectly fixes #6110 
Indirectly fixes #5959
=> Update crates to trigger rebuild for mysql issue

src/api/core/mod.rs, src/api/web.rs, src/config.rs
The registration link should be hidden if signup is not allowed and whitelist is empty unless mail is disabled and invitations are allowed
fixes #6109
=> fix hiding of signup link

src/api/core/ciphers.rs, src/api/notifications.rs
This issue mostly arises when push is enabled, but it also overloaded websocket connections. We would send a notification on every deleted cipher, which could be up-to 500 items. If push is enabled, it could overload the Push servers, and it would return a 429 error.
This PR fixes this by not sending out a message on every single cipher during a multi delete actions. It will send a single push message to sync the vault once finished.
The only caveat here is that there seems to be a bug with the mobile clients which ignores these global sync notifications. But, preventing a 429, which could cause a long term block of the sending server by the push servers, this is probably the best way, and, it is the same as Bitwarden it self does.
Fixes #4693
=> Fix multi delete slowdown

src/api/core/two_factor/email.rs
Encountered this when trying to set up the Android app (2025.7.2): 
```
[vaultwarden::api::core::two_factor::email::_][WARN] Data guard `Json < SendEmailLoginData >` failed: Parse("{\"DeviceIdentifier\":info_here\"\",\"Email\":\"\",\"MasterPasswordHash\":\""}", Error("missing field `deviceIdentifier`", line: 1, column: 163)).
```
=> Fix Email 2FA for mobile apps

src/api/core/ciphers.rs, src/db/models/auth_request.rs, src/db/models/cipher.rs
There were some more items which would still overload the push endpoint. This PR fixes the remaining items (I hope).
I also encountered a missing endpoint for restoring multiple ciphers from the trash via the admin console.
Overall, we could improve a lot of these items in a different way. Like bundle all SQL Queries etc... But that takes more time, and this fixes overloading the Bitwarden push servers, and speeds up these specific actions.
=> Fix several more multi select push issues

Cargo.lock, Cargo.toml
Update all the crates or in 2 cases downgrade because of being yanked.
Also replace `string_to_string` lint with `implicit_clone`, since it will not be supported in newer versions of Rust.
=> Update crates, fixes some yanked crates

playwright/README.md, playwright/compose/warden/Dockerfile, playwright/compose/warden/build.sh, playwright/playwright.config.ts, playwright/test.env, playwright/tests/setups/sso.ts, playwright/tests/sso_login.spec.ts, playwright/tests/sso_organization.spec.ts
The switch to `trixie` was not made for the intermediate docker image for the Playwright tests.
The intermediate image allow running tests against an unreleased `web-vault`.
Fixed the build script and added commented variable (I'll mention that `v2025.7.2` is not visible in https://github.com/dani-garcia/bw_web_builds/releases).
Fixed some errors with the tests:
- Increased the tests Timeout since the 10s timeout was generating flakiness around account creation.
- Remove the `override` parameter`, this is an unused leftover
- Fix the `email` field selection, it appears the duplication of the field with one hidden cause issues when trying to fill the second one :(
- Fix the toggle fields tests, they were not up-to-date with latest `web-vault` release.
=> Fix Playwright

.github/workflows/release.yml
- prevents container builds from running on forks
=> Re-add `if` check to release workflow

Cargo.toml, src/api/core/two_factor/webauthn.rs
- Applied SecurityKey to Passkey fixes from @zUnixorn
Because the webauthn-rs v0.3 crate did not know or store new flags currently used in v0.5, some verifications failed.
This mainly failed because of a check if a key was backuped or not, and if it was allowed to do so.
Most hardware keys like YubiKey's do not have this flag enabled and can't be duplicated or faked via software.
Since the rise of Passkey's, like Bitwarden's own implementation, and other platforms like Android, and Apple use Software keys which are shared between devices, they set these backup flags to true. This broke the login attempts, because the default during the migration was `false`, and cause an error during validation.
This PR checks for the flags during the response/verification step, and if these flags are …
=> Fix Webauthn/Passkey 2FA migration/validation issues

src/api/core/two_factor/webauthn.rs, src/api/identity.rs, src/api/web.rs, src/config.rs, src/main.rs, src/static/templates/scss/vaultwarden.scss.hbs
I don't think that we need initialize webauthn on startup (which currently fails if you set `DOMAIN` to an IP address because [webauthn requires a domain name as `rp_id`](https://www.w3.org/TR/webauthn-2/#relying-party-identifier)). I've also hidden it as an option if you have setup the [domain](https://docs.rs/url/2.5.4/url/struct.Url.html#method.domain) to be an IP address.
This won't touch on the other issues that were reported but I do think that it's important that Vaultwarden can start with something like `DOMAIN=http://127.0.0.1:8000`.
=> make webauthn more optional
