src/api/core/ciphers.rs, src/api/core/mod.rs
This adds support for `Move Selected` and `Delete Selected` in the Vault. It works, but there's a bit of code repetition in there which I'm not happy about, not sure how to do it nicer. It might require refactoring the current functions, I'll better leave that for another PR.
=> Add bulk move and bulk delete

src/api/core/mod.rs, src/api/core/organizations.rs, src/db/models/collection.rs, src/db/models/mod.rs, src/db/models/user.rs
Hi, this adds some extra functionality around organizations. Mostly stuff around managing collections and some organization-related functionality:
I didn't expect you to work on this after you told you don't have time, so I ended up with quite massive merge wall today, so please apologies if the code is a bit hairy. :smile:
=> Adding some oganization features - mostly collections

src/api/core/ciphers.rs
Just a quick fix to save cipher name on save
=> Save the name when updating the cipher data

migrations/2018-05-08-161616_create_collection_cipher_map/down.sql, migrations/2018-05-08-161616_create_collection_cipher_map/up.sql, src/api/core/ciphers.rs, src/api/core/mod.rs, src/db/models/cipher.rs, src/db/models/collection.rs, src/db/models/mod.rs, src/db/schema.rs
This adds new table that maps ciphers into collections. Also implemented some parts of the API to assign cipher to collections.
=> Implement Collection-Cipher mapping

src/api/core/mod.rs, src/api/core/organizations.rs, src/db/models/collection.rs, src/db/models/mod.rs, src/db/models/organization.rs
This adds functionality for deleting `Collection`. I've also renamed `CollectionUsers` to `CollectionUser` while implementing the functionality to follow the naming convention for other similar structs.
=> Implement deleting collections

src/api/core/organizations.rs, src/db/models/cipher.rs, src/db/models/collection.rs, src/db/models/organization.rs
This implements API needed to delete Organization. As part of these changes I moved deleting CollectionUser directly into UserOrganization::delete() where it's used wen user is removed but also when organization is deleted.
=> Implement deleting Organization

src/db/models/collection.rs
This fixes the find_by_uuid_and_user to also return collection if user has access_all or he's Admin/Owner of a group.
=> Let find_by_uuid_and_user return indirect collection (#26)

src/api/core/organizations.rs, src/db/models/collection.rs
This fixes three issues:
1. On invitation `accessAll` is optional and sometimes not sent
2. On `CollectionUser::save()` in invitation handler we were incorrectly using `headers.user.uuid` changing the Collection - User mapping for current user rather than the invited one.
3. The `CollectionUser::save()` was unnecessary in `post_organization_collections()` as the user making the POST request is already verified as Organization Admin or Owner and these have access to Collection anyways.
When updating collections for users we now also check if collection is in the Organization we're updating for.
As a side work I've also fixed the `CollectionUser::save()` for #6
=> Fix user invitation

src/api/core/organizations.rs, src/auth.rs
This implements `OrgHeaders`, `AdminHeaders` and `OwnerHeaders`, which are drop-in replacements for `Headers`, that also check appropriate `Organization` access level. 
I've updated all appropriate organization `GET` handlers with the above to show the usage. The other handlers should be updated as well, but  these will require removing some unnecessary check code and I wanted to keep this PR as minimal as possible, so I'd rather leave that for another, separate PR.
This should resolve #33
=> Implement request guards for organization

src/api/core/organizations.rs
This removes some unnecessary checks and replaces them with request guards.
=> Clean up organizations.rs with new request guards

Cargo.lock, Cargo.toml
Update dependency so it builds in the latest nightly.
=> Update rocket to 0.3.12

Dockerfile
Bump up the Vault version, this should contain fix for #21
=> Update Vault to 1.27.0

src/api/core/ciphers.rs, src/api/core/mod.rs
=> Implement delete-admin call

src/api/core/ciphers.rs, src/api/core/mod.rs, src/api/identity.rs
We probably shouldn't log these by default as the logs can leak some potentially sensitive data and it looks like they aren't really of any value anyway.
=> Remove some extra debug prints

BUILD.md, README.md
Hi, as per our discussion at #62 this is a PR to merge in the README changes. I think most of the information should be preserved, some of it is moved into separate BUILD.md file.
As for the docker hub side of things, if you're interested, create an account there and let me know, I can add you as collaborator, this should hopefully make things easier in the future. If you're not interested having yet another account in your bitwarden Valut, that's fine, but we need to figure out how can we get in touch to set up build trigger so that the whole thing is automated. (email me at miroslav@prasil.info perhaps?)
=> Update readme for docker hub

README.md
New backup information for users
=> updated README to include backup information

Dockerfile
And allow users to specify ROCKET_ENV when starting container, remove default exposing of port 80.
=> Enable user to change ROCKET_ENV for container

Dockerfile
=> Move the ROCKET_ENV to the runtime image

Dockerfile
Change the branch name to the stable release tag.
I suggested to merge this to beta branch for now before #97, #98, #99 and #100 are fixed.
=> Use stable release of v2.0.0

Dockerfile
2.1.1 has just been released. There were some interesting improvements in 2.1.0, we need to test this.
=> Update vault to latest version

docker/set-vault-baseurl.patch
Vault 2.1.1 no longer worked with previous patch file, here's updated version.
=> Fix patch file for v2.1.1

src/api/core/organizations.rs
When adding/editing user and giving access to all collections, the collection list is now set to _null_ and causes deserialization failure. This change deserializes this back to empty Vec.
=> Deserialize "null" to empty Vec for Collections

docker/set-vault-baseurl.patch
=> Remove analytics from Vault

README.md
Just moved the quote so it doesn't look weird and removed irrelevant volume mapping.
=> Cleaned up HTTPS example

src/api/identity.rs
Resolves #119
I added the IP and Username of the failed login attempt to the error message describing the attempt, as request in issue #119.
=> Add ip and username to failed login attempts

src/api/core/ciphers.rs
This fixes an issue that was probably introduced in #159.
=> Fix editing shared cipher (fixes #164)

src/api/core/ciphers.rs, src/api/notifications.rs, src/db/models/cipher.rs
This I think covers all the update cipher options (not create/delete)
EDIT: Now includes create and delete updates for ciphers
=> Add support for cipher update notifications

README.md
Add a documentation to cover #153 and some other issues when running over HTTP.
=> Add info on running over HTTP (documentation for #153)

.env, Cargo.toml, src/api/core/accounts.rs, src/mail.rs, src/main.rs
=> SMTP implementation, along with password HINT email 

Dockerfile.armv7
This adds armv7 Dockerfile that builds image suitable for Raspberry Pi
=> Add Dockerfile for Raspberry Pi

README.md
Small fix to readme as the current version broke somewhat limited markdown rendering in docker hub.. 
Also removed `sudo` to be consistent with the rest of the examples. (also added shell syntax highlighting)
=> Fixed code block, added some formatting

src/api/core/accounts.rs, src/api/core/mod.rs
=> Add alias for DELETE call on accounts

README.md
This hopefully improves documentation for #187.
=> Update the Invitation workflow documentation

Dockerfile, Dockerfile.alpine, Dockerfile.armv7
The patch seems to apply correctly and it seems to build fine, but I haven't yet tested this extensively, so maybe try to test it first before merging.
=> Update Vault to v2.3.0

src/api/core/ciphers.rs, src/db/models/organization.rs, src/main.rs
I've noticed we didn't return `MaxStorageGb` and `UsersGetPremium` properly in some cases, so I've added those. I've also somewhat simplified the cipher sharing code.
=> Org improvements

src/api/core/organizations.rs, src/db/models/collection.rs, src/db/models/organization.rs
This updates User revision on `Collection::save()` to let the client sync collections properly. Also fixes `Collection::save()` for #6.
=> Collection update updates User revision

src/api/core/ciphers.rs, src/db/models/cipher.rs
=> Cipher::save() should return QueryResult instead of bool

src/api/core/ciphers.rs, src/api/core/organizations.rs, src/db/models/collection.rs
=> CollectionCipher::save() and delete() should return QueryResult instead of bool

src/api/core/accounts.rs, src/api/core/organizations.rs, src/db/models/organization.rs
=> Organization::save() and UserOrganization::save() should return QueryResult instead of bool

src/api/identity.rs, src/db/models/device.rs
=> Device::save() should return QueryResult instead of bool

src/api/core/accounts.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/core/two_factor.rs, src/db/models/user.rs
=> User::save() should return QueryResult instead of bool

src/api/core/ciphers.rs, src/api/core/folders.rs, src/db/models/folder.rs
=> Folder::save() should return QueryResult instead of bool

README.md
as mentioned in https://github.com/dani-garcia/bitwarden_rs/issues/223
=> refine backup instructions

src/api/core/ciphers.rs
=> Don't send Domains if excludeDomains=true on /sync

README.md
As per our discussion, adding the Kubernetes deployment reference as subsection.
Cheers,
Igor
=> Add Kubernetes deployment reference

README.md
I think you meant below instead of bellow.
Definition of bellow (intransitive verb):
1 : to make the loud deep hollow sound characteristic of a bull
2 : to shout in a deep voice
=> Grammar fixes to README.md

README.md
Hopefully it's more visible this way.
=> Improve the admin account warning.

Dockerfile, Dockerfile.aarch64, Dockerfile.alpine, Dockerfile.armv7, src/api/core/ciphers.rs, src/api/core/organizations.rs, src/auth.rs, src/db/models/organization.rs, src/db/models/user.rs
I've bumped Vault to 2.5.0 but didn't have a time to extensively test. There were some new features added, so it's possible some things might be broken.
=> Bump vault version to 2.5.0 [wip]

README.md
I added a few lines to help people using docker commands if they are not using docker-compose.
=> Add line for people using docker commands instead of docker-compose

BUILD.md
As there were multiple people having problems with the build I thought that maybe adding a note would help.
=> Add memory usage note to the vault build documentation

Dockerfile, Dockerfile.aarch64, Dockerfile.alpine, Dockerfile.armv7
Haven't really fully tested yet, but it looks like the core functionality should be OK.
=> Update vault to 2.7.1

README.md
as mentioned in issue #255 from [this comment](https://github.com/dani-garcia/bitwarden_rs/issues/255#issuecomment-447383930) onwards.
=> updated fail2ban setup to match changes in logformat for 1.5.0

.env, src/api/icons.rs, src/main.rs
For previous discussion, see also #299.
=> implement TTLs for icon cache

src/db/models/collection.rs
As suggested in #313, I've rewrote the function to avoid duplicates by using just one query.
=> Rewrite find_by_user_uuid to use one query

Dockerfile, Dockerfile.aarch64, Dockerfile.alpine, Dockerfile.armv7
Update the Dockerfiles once Vault builds are ready
=> Update Vault to 2.8.0

src/api/core/organizations.rs, src/db/models/organization.rs
This addresses the display issues noted on https://github.com/dani-garcia/bitwarden_rs/issues/364
=> Fix the list of users with access to a collection to display correctly.

Cargo.lock, Cargo.toml, src/api/icons.rs, src/error.rs, src/main.rs
Changed the favicon downloader to use the main html page with `<link rel="*icon*">` selection.
=> Added better favicon downloader.

src/api/icons.rs
- Using url from reqwest to fix href, this fixes:
+ "//domain.com/icon.png"
+ "relative/path/to/icon.png"
+ "/absolute/path/to/icon.png"
- Removed fix_href function
- Some variable changes
=> Changed the way to fix the href

src/api/icons.rs
- Created a separate function for parsing the sizes attribute
- Parsing sizes now with regex
- Should work with any non-digit separator
=> Fixed issue #380

src/api/icons.rs
Loop for a maximum of 5 times through the iconlist or until a
successful download of an icon.
=> Loop through the iconlist until an icon is found

src/db/models/collection.rs
We don't properly update the revision for deleted collections, so affected users still see them in their interface until they sync for some other reason. This should fix this.
=> Update revision of affected users when deleting Collection

.dockerignore
This should fix version not appearing in docker images like reported in #400.
=> Include git repo in build so we get version

src/api/core/ciphers.rs
Fixes #458.
The new logic checks for the `organizationId` query parameter.
If there is none, it assumes the users wants to purge their own vault.
If there is, it only purges the vault of the organization if the user is an owner of the organization.
=> Fixed purging organization vault

README.md
I've already updated (hopefully) all wiki references to it. This updates the Readme
=> Point to the new docker hub image location

src/api/admin.rs, src/db/mod.rs, src/static/templates/admin/page.hbs
Added create backup functionality to the admin panel
=> Create Backup funcitonality

src/config.rs
Changed it from Chache to Cache on Line 207
=> Corrected Spelling

.hadolint.yaml, .travis.yml, docker/aarch64/mysql/Dockerfile, docker/aarch64/sqlite/Dockerfile, docker/amd64/mysql/Dockerfile, docker/amd64/mysql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/mysql/Dockerfile, docker/armv6/sqlite/Dockerfile, docker/armv7/mysql/Dockerfile, docker/armv7/sqlite/Dockerfile
- add hadolint to travisfile
fixes https://github.com/dani-garcia/bitwarden_rs/issues/522
=> use hadolint for linting Dockerfiles

src/api/identity.rs, src/config.rs, src/mail.rs, src/static/templates/email/new_device_logged_in.hbs, src/static/templates/email/new_device_logged_in.html.hbs
- Added both templates for the New Device Logged In From email.
- Added `send_new_device_logged_in` email function.
- Moved logic of retrieving or creating device to `get_device` function (Is that ok?). When the device is new an email is sent.
=> Add "New Device Logged In From" email

src/api/icons.rs
As requested in issue #570 i added system proxy support.
I have tested this it it works via the proxy by setting the environment variable.
Maybe we can create something to have this set in the environment, but i think that is up to docker it self.
=> Added reqwest proxy support

src/main.rs, src/util.rs
Added a Fairing to send Cors headers back for preflight requests.
Fixes #595
=> Add Cors headers

docker/aarch64/mysql/Dockerfile, docker/aarch64/sqlite/Dockerfile, docker/amd64/mysql/Dockerfile, docker/amd64/mysql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile, docker/amd64/sqlite/Dockerfile.alpine, docker/armv6/mysql/Dockerfile, docker/armv6/sqlite/Dockerfile, docker/armv7/mysql/Dockerfile, docker/armv7/sqlite/Dockerfile, docker/healthcheck.sh
As of https://github.com/dani-garcia/bitwarden_rs/issues/246#issuecomment-524299620
a basic healthcheck for the container is implemented with this commit.
When everything is okay the same healthcheck will be applied to the other dockerfiles.
=> Adds Healthcheck for default docker container

src/api/icons.rs
Issue fixed by omitting the cookie header when cookie_str is empty
=> Fixed issue #565

.env.template
Forgot to add this configuration option to the .env template.
=> Added missing .env configuration option.

README.md
Minor fix for some basic grammar in the "get in touch" section
=> Simple grammar update

src/api/core/two_factor/authenticator.rs
During the 2fa activation there is no twofactor record yet.
Changed the layout a bit so that it will generate a new twofactor record
when it does not exists yet. Else it will just update the already
existing record.
=> Fixed issue #663.

src/config.rs
=> Move 2FA email config to after SMTP config

src/api/notifications.rs
See https://github.com/dani-garcia/bitwarden_rs/pull/670
=> Remove unneeded WS logging

src/api/core/accounts.rs
This fixes #691 - respond in less specific way to not leak the
fact that user is already registered on the server.
=> Stop leaking usernames when SIGNUPS_ALLOWED=false

Cargo.lock, Cargo.toml, src/db/mod.rs
- Using an older commit from rocket repo
=> Trying to fix issue #687

src/api/core/ciphers.rs, src/api/core/mod.rs
Fixes #681
Please excuse my rusty rust.
=> Don't include excluded global equivalent domains during sync

.env.template
Super minor change to get correct syntax highlighting
=> Add vim modeline for GitHub Linguist

src/static/global_domains.json
Added netcup.de netcup.eu and the customercontrolpanel to the global domains list.
=> Added netcup domains to global domains

.github/workflows/rust-linux.yml, .github/workflows/rust-mac.yml, .github/workflows/rust-win.yml
Sometimes It's nice to have a binary to download
=> Add Github build Action

src/config.rs
=> Fix change email when no whitelist is configured

src/api/admin.rs, src/config.rs, src/mail.rs, src/static/templates/admin/page.hbs, src/static/templates/email/smtp_test.hbs, src/static/templates/email/smtp_test.html.hbs
- Added a test button for checking the e-mail settings.
- Fixed a bug with the _post JavaScript function:
A function was overwriten with a variable and errors were not handled
correctly like a 500 for example.
=> Added SMTP test button in the admin gui

src/static/templates/admin/page.hbs
- Moved smtp test option to within the "SMTP Email" Settings block.
- Added optional option to prevent full page reload.
- SMTP Test and Backup do not reload the admin interface any more.
=> Relocated SMTP test input+button.

src/static/global_domains.json
Added domains from official vault.bitwarden.com
=> Updated domains with new values vualt

Cargo.lock, Cargo.toml, src/api/core/mod.rs, src/api/core/two_factor/duo.rs, src/api/icons.rs
- Use the blocking client (no async).
- Disabled gzip.
- use_sys_proxy is now default.
=> Updated reqwest to the latest version.

docker/healthcheck.sh
=> Update healthcheck script to handle alternate base dir

src/api/notifications.rs
Ignore a missing `id` query param; it's unclear what this ID represents,
but it wasn't being used in the existing bitwarden_rs code, and no longer
seems to be sent in the latest versions of the official clients.
Fixes #929.
=> Fix WebSocket notifications

docker/amd64/mysql/Dockerfile.alpine, docker/amd64/postgresql/Dockerfile.alpine, docker/amd64/sqlite/Dockerfile.alpine
Picks up a couple of missed changes from b837348b and ccf6ee79.
=> Rebuild Dockerfiles to match latest Dockerfile.j2 template

src/api/core/two_factor/duo.rs
=> Fix Duo auth failure with non-lowercased email addresses

src/api/core/ciphers.rs, src/api/core/two_factor/authenticator.rs, src/config.rs, src/db/models/device.rs, src/db/models/organization.rs, src/static/global_domains.json
Updates the global equivalent domain values from bitwarden.  It also fixes some whitespace inconsistencies that I noticed.
=> GlobalEquivalentDomains updates from upstream bitwarden

src/api/core/accounts.rs, src/api/core/organizations.rs, src/config.rs
=> Allow email changes for existing accounts even when signups are disabled

src/static/scripts/bootstrap-native-v4.js, src/static/scripts/bootstrap.css, src/static/templates/admin/base.hbs, src/static/templates/admin/users.hbs
- Updated bootstrap js and css to the latest version
- Fixed issue with small-screens where the menu overlaps the token input
- The menu now collapses to a hamburger menu
- Menu's only accessable when logedin are hidden when you are not
- Changed Users Overview to use a table to prevent small-screen issues.
=> Updated js/css libraries and fixed smallscreen err

src/db/models/collection.rs
=> Fix error in PostgreSQL build

hooks/push
=> Push an extra `latest-arm32v6` tag

Cargo.lock, Cargo.toml, src/crypto.rs
=> Generate tokens more simply and uniformly

src/config.rs
=> Add more docs on the `email_token_size` setting

README.md
Maybe prevents #1113 and similar issues from popping up again in the future.
As always, please advise on the wording, I don't really know what was meant with "Single user functionality" in the first place.
=> Clarify multiuser capabilities

src/db/models/organization.rs
Also move `UserOrgType::from_str()` closer to the definition of `UserOrgType`
since it references specific enum values.
=> Simplify implementation of `UserOrgType::cmp()`

src/api/core/organizations.rs
- The new web-vault needs a new api endpoint.
- Added this new endpoint.
Fixes #1139
=> Fixed creating a new organization

.env.template, src/config.rs
Made some small changes to the description of the config options for
SMTP. Some were a bit cryptic and missing some extra descriptions.
Also made it more clear which type of secured smtp connection is going
to used.
=> Updated the config options descriptions.

src/api/web.rs, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/scripts/jquery-3.5.1.slim.js, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
As requested here: https://bitwardenrs.discourse.group/t/searchable-user-list-on-admin-panel/299
- Changed the table layout a bit.
- Added functions to the tables:
+ Search
+ Sort
+ Paginate
=> Enhanced user and orgs tables in admin view.

src/db/models/attachment.rs, src/db/models/cipher.rs, src/db/models/collection.rs, src/db/models/folder.rs, src/db/models/org_policy.rs, src/db/models/organization.rs, src/db/models/two_factor.rs, src/db/models/user.rs
When using MariaDB v10.5+ Foreign-Key errors were popping up because of
some changes in that version. To mitigate this on MariaDB and other
MySQL forks those errors are now catched, and instead of a replace_into
an update will happen. I have tested this as thorough as possible with
MariaDB 10.5, 10.4, 10.3 and the default MySQL on Ubuntu Focal. And
tested it again using sqlite, all seems to be ok on all tables.
resolves #1081. resolves #1065, resolves #1050, resolves #1159
=> Fixed foreign-key (mariadb) errors.

docker/Dockerfile.j2, docker/arm32v7/Dockerfile.alpine, hooks/arches.sh
also adds catatonit for sigterm handling and strips the binary
=> alpine arm dockerfile

.env.template
Several values were missing from the .env.template file.
Updated this with all the values which were missing.
=> Updated .env.template with missing config values.

.github/ISSUE_TEMPLATE/bug_report.md
Added a note about updating first to the latest version before reporting an issue.
=> Updated bug-report to note to update first

src/api/core/accounts.rs
Corrected the verify_email error message for correct message in log file.
=> Correction of verify_email error message

src/api/core/ciphers.rs
This fixes the inability to bulk-delete ciphers from org vault views.
=> Add missing admin endpoints for deleting ciphers

src/config.rs
Some issue people report are because of misconfiguration or bad .env
files. To mittigate this i added error handling for this.
- Panic/Quit on a LineParse error, which indicates bad .env file format.
- Emits a info message when there is no .env file found.
- Emits a warning message when there is a .env file, but not no permissions.
- Emits a warning on every other message not specifically catched.
This partially fixes #1196 by reporting the line regarding spaces.
Solving that ticket by allowing spaces would be difficult from within
bitwarden_rs it self.
=> Added error handling during dotenv loading

src/api/core/ciphers.rs
Prevent clients from updating a cipher if the local copy is stale.
Validation is only performed when the client provides its last known
revision date; this date isn't provided when using older clients,
or when the operation doesn't involve updating an existing cipher.
Fixes #780.
=> Validate cipher updates with revision date

hooks/build, hooks/pre_build
=> Add `org.opencontainers` labels to Docker images

src/api/core/ciphers.rs, src/api/core/organizations.rs, src/db/models/org_policy.rs, src/db/models/organization.rs
Upstream refs:
* https://github.com/bitwarden/server/pull/1013
* https://bitwarden.com/help/article/policies/#personal-ownership
Fixes #1319
Depends on dani-garcia/bw_web_builds#22
=> Add support for the Personal Ownership policy

src/api/core/ciphers.rs
This matches changes in the upstream Bitwarden server and clients.
Upstream PR: https://github.com/bitwarden/server/pull/1072
=> Add cipher response to restore operations

src/mail.rs
Removes unnecessary clones or allocations from the mail module.
=> Remove unnecessary allocations

src/util.rs
* The Safari extension apparently now uses the origin `file://` and expects
that to be returned (see bitwarden/browser#1311, bitwarden/server#800).
* The `Access-Control-Allow-Origin` header was reflecting the value of the
`Origin` header without checking whether the origin was actually allowed.
This effectively allows any origin to interact with the server, which
defeats the purpose of CORS.
=> CORS fixes

src/api/core/ciphers.rs, src/api/core/sends.rs, src/db/models/org_policy.rs
Upstream refs:
* https://github.com/bitwarden/server/pull/1130
* https://bitwarden.com/help/article/policies/#disable-send
=> Add support for the Disable Send policy

src/static/global_domains.json
Sync global_domains.json to bitwarden/server@455e4b2 (ProtonMail/ProtonVPN)
=> Sync global_domains.json

src/api/core/sends.rs
This should help avoid leaking information about (non)existence of Send
and be more in line with what official server returns.
=> Return generic message when Send not available

src/api/admin.rs, src/db/mod.rs, src/static/templates/admin/diagnostics.hbs
- Added reverse proxy check
- Better deffinition of internet proxy
- Added SQL Server version detection
=> Updated diagnostics page

.github/workflows/build.yml, src/api/admin.rs, src/api/core/accounts.rs, src/api/core/ciphers.rs, src/api/core/folders.rs, src/api/core/mod.rs, src/api/core/organizations.rs, src/api/core/two_factor/mod.rs, src/api/core/two_factor/u2f.rs, src/api/icons.rs, src/api/notifications.rs, src/auth.rs, src/db/models/cipher.rs, src/db/models/device.rs, src/db/models/organization.rs, src/error.rs, src/main.rs, src/util.rs
Run `clippy` over the codebase, and fix the issues
https://github.com/rust-lang/rust-clippy
The diff is large, but the code is now nice and rust-y, and fixes some `unwrap`s, unnecessary code and cleaner conditionals.
I intend to also do a PR for `cargo fmt`, but best get this one in first so it's easier to review.
=> Run Clippy

.env.template
This was wrong in commit 88c56de97b48bb5b9b8af350d0d0e0d5f080ff0e.
Ref: https://github.com/dani-garcia/bitwarden_rs/blob/fd27759a95bc7f714abacb3a02b8c6f88b1d3cd4/src/config.rs#L377-L379
=> fix(env.template): IP_HEADER defaults to X-Real-IP

.dockerignore, .editorconfig, .github/workflows/build.yml, .github/workflows/hadolint.yml, docker/Dockerfile.j2, docker/amd64/Dockerfile, docker/amd64/Dockerfile.alpine, docker/arm64/Dockerfile, docker/armv6/Dockerfile, docker/armv7/Dockerfile, docker/armv7/Dockerfile.alpine, src/db/mod.rs
Some small changes in general:
- Moved the SQL Version check struct into the function.
- Updated hadolint to 2.0.0
- Fixed hadolint 2.0.0 warnings
- Updated github workflows
- Added .editorconfig for some general shared editor settings.
=> Misc changes.

src/api/icons.rs
- Added image type checking, and prevent downloading non images.
We didn't checked this before, which could in turn could allow someone
to download an arbitrary file.
- This also prevents SVG images from being used, while they work on the
web-vault and desktop client, they didn't on the mobile versions.
- Because of this image type checking we can return a valid file type
instead of only 'x-icon' (which is still used as a fallback).
- Prevent rel values with `icon-mask`, these are not valid favicons.
=> Updated icon fetching.

src/static/templates/admin/settings.hbs
Also add a link to the wiki page on backups.
=> Warn that the SQLite backup feature doesn't produce a complete backup

migrations/mysql/2021-04-30-233251_add_reprompt/up.sql, migrations/postgresql/2021-04-30-233251_add_reprompt/up.sql, migrations/sqlite/2021-04-30-233251_add_reprompt/up.sql, src/api/core/ciphers.rs, src/db/models/cipher.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
Upstream PR: https://github.com/bitwarden/server/pull/1269
=> Add support for password reprompt

Cargo.lock, Cargo.toml, src/api/icons.rs, src/main.rs
- Updated some crates
- Updated icon fetching code:
+ Use a cookie jar and set Max-Age to 2 minutes for all cookies
+ Locate the base href tag to fix some locations
+ Changed User-Agent (Helps on some sites to get HTML instead of JS)
+ Reduced HTML code limit from 512KB to 384KB
+ Allow some large icons higer-up in the sort
+ Allow GIF images
+ Ignore cookie_store and hyper::client debug messages
=> Updated icon fetching and crates.

.env.template
This should have been added as part of #1579.
=> Add `TRASH_AUTO_DELETE_DAYS` to .env.template

.env.template
=> Clarify Rocket env var defaults

.github/workflows/build.yml, .github/workflows/hadolint.yml, src/api/admin.rs, src/api/web.rs, src/config.rs, src/static/scripts/bootstrap-native.js, src/static/scripts/bootstrap.css, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/scripts/jquery-3.6.0.slim.js, src/static/templates/admin/base.hbs, src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/organizations.hbs, src/static/templates/admin/settings.hbs, src/static/templates/admin/users.hbs
Misc:
- Fixed hadolint workflow, new git cli needs some extra arguments.
- Add ignore paths to all specific on triggers.
- Updated hadolint version.
- Made SMTP_DEBUG read-only, since it can't be changed at runtime.
Admin:
- Migrated from Bootstrap v4 to v5
- Updated jquery to v3.6.0
- Updated Datatables
- Made Javascript strict
- Added a way to show which ENV Vars are overridden.
- Changed the way to provide data for handlebars.
- Fixed date/time check.
- Made support string use details and summary feature of markdown/github.
=> Multiple Admin Interface fixes and some others.

src/api/core/two_factor/email.rs
There was some wrong logic regarding the display of which email is
configured to be used for the email MFA. This is now fixed.
Resolves #1878
=> Fix wrong display of MFA email.

src/api/core/ciphers.rs
=> Fix error with adding file attachment from org vault view

src/api/core/ciphers.rs
Upstream PR: https://github.com/bitwarden/server/pull/1565
=> Enforce Personal Ownership policy on imports

src/api/core/organizations.rs
For user management within the organization view you are able to select
multiple users to re-invite, confirm or delete them.
These actions were not working which this PR fixes by adding support for
these endpoints. This will make it easier to confirm and delete multiple
users at once instead of having to do this one-by-one.
=> Add Organization bulk actions support

.pre-commit-config.yaml, src/static/scripts/bootstrap-native.js, src/static/scripts/bootstrap.css, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/admin/settings.hbs
- Updated JS Libraries
- Downgraded bootstrap.css to v5.0.2 which works with Bootstrap-Native.
- Fixed issue with settings being able to open/collapse on some systems.
- Added .js and .css to the exclude list for the end-of-file-fixer pre-commit
=> Update some JS Libraries and fix small issues

src/api/core/organizations.rs
Resolved #2151 by checking the correct header type.
=> Fixed #2151

src/static/templates/admin/login.hbs
Allows quicker login of admin console without having to manually put focus in password field
=> Added autofocus to pw field on admin login page

.github/workflows/build.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/core/accounts.rs, src/config.rs, src/db/models/org_policy.rs, src/static/scripts/bootstrap-native.js, src/static/scripts/bootstrap.css, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/admin/base.hbs, src/static/templates/admin/settings.hbs, src/util.rs
- Updated some Rust dependencies
- Fixed an issue with CSP header, this was not configured correctly
- Prevent sending CSP and Frame headers for the MFA connector.html files.
Else some clients will fail to handle these protocols.
- Add `unsafe-inline` for `script-src` only to the CSP for the Admin Interface
- Updated JavaScript and CSS files for the Admin interface
- Changed the layout for showing overridden settings, better visible now.
- Made the version check cachable to prevent hitting the Github API rate limits
- Hide the `database_url` as if it is a password in the Admin Interface
Else for MariaDB/MySQL or PostgreSQL this was plain text.
- Fixed an issue that pressing enter on the SMTP Test would save the config.
resolves #2542
- Prevent user names larger then 50 characters
resolves …
=> Updated deps and misc fixes and updates

.pre-commit-config.yaml, src/util.rs
This PR is needed for https://github.com/dani-garcia/bw_web_builds/pull/71
Without this the web-vault will refuse to make calls to the FireFox Relay API.
Also fixed a small issue with the pre-commit config.
=> Allow FireFox relay in CSP.

src/static/templates/admin/base.hbs
Fixes #2570
Reverted the `defer` option for these scripts, seems to cause some
issues in some situations.
=> Fix identicons not always working

src/static/templates/admin/diagnostics.hbs
I opened an issue earlier (#2745) regarding this typo and closed that issue now.
=> fix: tooltip typo

src/util.rs
Also, reformat the CSP header for readability.
Upstream PR: https://github.com/bitwarden/clients/pull/3630
=> Update CSP for DuckDuckGo email forwarding

README.md
master branch has been renamed to main.
=> fix link of license badge

docker/healthcheck.sh
=> Take `ROCKET_ADDRESS` into account in the Docker healthcheck

src/static/templates/email/emergency_access_recovery_rejected.html.hbs
This pull request fix a double space. Nothing important, but definitly looks better :)
=> fix: removed a double space

src/auth.rs, src/db/models/collection.rs
This PR should fix the managers and group link.
Although i think there might be a cleaner sollution, there are a lot of other items to fix here which we should do in time.
But for now, with theh group support already merged, this fix should at least help solving issue #2932.
Fixes #2932
I know, it can be nicer, but lets just leave it like this, and fix all the items later :) .
=> Fix managers and groups link

src/config.rs
Fix remaining inline format which will be triggered using 1.67.0 and above.
=> Fix remaining inline format

src/api/web.rs, src/static/scripts/admin.css, src/static/scripts/admin.js, src/static/scripts/admin_diagnostics.js, src/static/scripts/admin_organizations.js, src/static/scripts/admin_settings.js, src/static/scripts/admin_users.js, src/static/scripts/jquery-3.6.3.slim.js, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs
When a non sqlite database is used, loading the admin interface fails
because the backup button is not generated.
This PR is solves it by checking if the elements are valid.
Also made some other js/css changes and fixed some eslint errors.
Showing `_post` errors is better now.
Update jquery to latest version.
Fixes #3166
=> Fix Javascript issue on non sqlite databases

README.md
Added status badge for build workflow in readme.
=> docs: add build status badge in readme

src/api/admin.rs
In my opinion, as an admin, it is nice to be able to find users by email address as well. This makes Vaultwarden more compatible with other systems (e.g. for user management). Currently I use the `get_users_json` route to fetch all users and then filter the result, but this is suboptimal as the number of users grows.
The user model already provides a corresponding function ([here](https://github.com/dani-garcia/vaultwarden/blob/main/src/db/models/user.rs#L362-L371)), I just added a route in the admin controller to call this function.
Just as `/users/overview`, `/users/by-mail/<mail>` should not conflict with `/users/<uuid>`.
=> Add function to fetch user by email address

src/api/core/organizations.rs
In the org vault view, the Bitwarden web vault currently tries to fetch the groups for an org regardless of whether it claims to have group support. If this errors out, no vault items are displayed.
Fixes #3276
=> Fix vault item display in org vault view

src/static/scripts/admin_users.js
Fixes #3282
Adds the email variable as this is required for the buttons to function.
=> Fix confirmation for removing 2FA and deauthing sessions in admin panel

src/api/web.rs
Rocket automatically implements a HEAD route when there's a matching GET route, but relying on this behavior also means a spurious error gets logged due to <https://github.com/SergioBenitez/Rocket/issues/1098>.
Add explicit HEAD routes for `/` and `/alive` to prevent uptime monitoring services from generating error messages like `No matching routes for HEAD /`. With these new routes, `HEAD /` only checks that the server can respond over the network, while `HEAD /alive` also checks that the database connection is alive, similar to `GET /alive`.
=> Add HEAD routes to avoid spurious error messages

src/api/core/accounts.rs
Upstream PR: https://github.com/bitwarden/server/pull/2682
=> Add support for `/api/devices/knowndevice` with HTTP header params

src/api/core/organizations.rs
There was used a wrong macro to produce an error message when mailing
the user his password was reset failed. It was using `error!()` which
does not return an `Err` and aborts the rest of the code.
This resulted in the users password still being resetted, but not being
notified. This PR fixes this by using `err!()`. Also, do not set the
user object as mutable until it really is needed.
Second, when a user was using the new Argon2id KDF with custom values
like memory and parallelism, that would have rendered the password
incorrect. The endpoint which should return all the data did not
returned all the new Argon2id values. (Thanks to @stefan0xC for spotting the specific culprit).
Fixes #3388
=> Fix abort on pw reset mail error

Cargo.lock, Cargo.toml, src/api/notifications.rs
Switched from channels to stream. This is able to use yield, and the code looks a bit nicer this way.
Also updated all the crates.
=> Small update to Rocket WebSockets

.github/workflows/build.yml, Cargo.lock, Cargo.toml
=> Update crates and GH Workflow

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, src/api/icons.rs
- Updated workflow actions
- Set cargo registry to sparse
=> Update crates and workflow

src/api/core/organizations.rs
=> Add group import on invite

migrations/mysql/2023-06-28-133700_add_collection_external_id/up.sql, migrations/postgresql/2023-06-28-133700_add_collection_external_id/up.sql, migrations/sqlite/2023-06-28-133700_add_collection_external_id/up.sql, src/api/core/organizations.rs, src/db/models/collection.rs, src/db/schemas/mysql/schema.rs, src/db/schemas/postgresql/schema.rs, src/db/schemas/sqlite/schema.rs
Hey maintainers!
Here is my 2nd PR, hope this gets merged now.
With incoming support for public api and groups vaultwarden gets ready for enterprise. What about imlementing ExternalId on collections?
It is supported for Groups and Orgs, but not yet for Collections. It's a big requirement for automated API Imports.
Feel Free to Comment and Update.
Kind Regards
Folke
=> Added-External_id for Collections

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml
- Updated GitHub actions
- Fixed an issue with testing MSRV (It didn't)
Prevents an issue reported here #3908
=> Update GitHub Workflow

docker/Dockerfile.j2, docker/arm64/Dockerfile, docker/arm64/Dockerfile.buildkit, docker/armv6/Dockerfile, docker/armv6/Dockerfile.buildkit, docker/armv7/Dockerfile, docker/armv7/Dockerfile.buildkit
Because of some changes in the packages of Debian we need to add an extra package to request it also to install
=> Fix arm builds

src/api/core/ciphers.rs, src/api/core/mod.rs, src/db/models/cipher.rs
Revert changes in #3593 and make them work with Browser plugin 2023.10.1
=> feat: Working passkeys storage

src/api/core/ciphers.rs
When importing Bitwarden JSON exports, these would fail because the last modification date was also imported and caused our out-off-sync check to kick-in. This PR fixes this by checking if we are doing an import, and skip this check.
Fixes #4005
=> Fix importing Bitwarden exports

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
Update web-vault to v2023.12.0
=> Update web-vault to v2023.12.0

Cargo.lock, Cargo.toml, src/config.rs
- Fix icon download issue by removing the deflate feature
- Updated Handlebars code
Fixes #4224
=> Update crates and fix icon issue

.env.template
- Fix some default parameters which not match the config.rs.
- Categorize settings into sevral sections. Mainly followed the config.rs's structure.
- Add a missing setting: AUTH_REQUEST_PURGE_SCHEDULE
=> Update env template file

.github/workflows/release.yml, Cargo.lock, Cargo.toml, src/api/web.rs, src/static/scripts/bootstrap.bundle.js, src/static/scripts/bootstrap.css, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/scripts/jquery-3.7.1.slim.js, src/static/templates/admin/organizations.hbs, src/static/templates/admin/users.hbs, tools/global_domains.py
- Update all crates
- Update GHA
- Update Global Domains script to use main instead of master
Also fixed some Python linting warnings
- Updated Admin JS and CSS libraries
=> Update crates, GHA and a Python script

src/api/web.rs
=> fix: web API call for jquery 3.7.1

Cargo.lock, Cargo.toml, src/api/core/accounts.rs, src/api/core/emergency_access.rs, src/api/core/public.rs, src/api/core/sends.rs, src/api/core/two_factor/email.rs, src/api/core/two_factor/mod.rs, src/api/core/two_factor/protected_actions.rs, src/api/notifications.rs, src/auth.rs, src/db/models/auth_request.rs, src/db/models/cipher.rs, src/db/models/device.rs, src/db/models/event.rs, src/db/models/user.rs, src/util.rs
- Updated sqlite crate
- Updated chrono crate
The latter needed a lot of changes done, mostly `Duration` to `TimeDelta`. And some changes on how to use Naive.
=> Update chrono and sqlite

src/api/core/two_factor/yubikey.rs
While looking through the crates that we have that use reqwest 0.11, I discovered that the yubico crate can do async verification, so we can avoid the spawn_blocking. I've also changed the error handling a bit to properly log any returned errors.
I've tried it with my yubikeys and seems to work fine.
=> Use async verify for Yubikey

Cargo.lock, Cargo.toml, src/api/admin.rs, src/api/core/organizations.rs, src/api/notifications.rs, src/auth.rs, src/db/models/cipher.rs, src/db/models/emergency_access.rs, src/util.rs
- Updated all crates including reqwest
- Fixed some clippy lints reported by nightly Rust
Closes #4471
Closes #4477
Fixes #4476
=> Update crates and some Clippy fixes

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml
- Updated all crates
- Updated Rust to the latest patch version
- Updated GitHub Actions
=> Update Crate and Rust

src/api/core/ciphers.rs, src/api/identity.rs, src/db/models/organization.rs, src/db/models/user.rs, src/main.rs
The new mobile apps are going to send some values slightly differently and will expect some other values to be there, while we previously weren't sending them. This should fix those issues, at least for Android.
Note that we will still need to go through with #4386 for the apps to work correctly.
=> Some fixes for the new mobile apps

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml
- Updated Rust to v1.78.0
- Update web-vault to v2024.5.0
=> Update Rust, crates and web-vault

.env.template
=> Improve Commentary Aesthetics

src/db/models/organization.rs
=> also delete organization_api_key when deleting organizations

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
Seems to have been missed in https://github.com/dani-garcia/vaultwarden/pull/4558
=> Fix web-vault version in Docker(files/Settings)

docker/DockerSettings.yaml, docker/Dockerfile.alpine
- needed to add double quotes, otherwise it was parsed as 3.2 instead of 3.20
=> Update Alpine to version 3.20

src/api/core/accounts.rs
I believe the migration to the endpoint was merged on March 7 2023 in the clients (github.com/bitwarden/clients/pull/4710).
So it probably makes sense to remove it.
=> Remove old knowndevice route

src/api/core/organizations.rs
=> allow re-invitations of existing users

.github/workflows/release.yml, .github/workflows/trivy.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
- Update Rust to v1.80.0
- Updated GitHub Actions
=> Update Rust, Crates and GHA

src/api/core/sends.rs
Currently there are no checks done during the actual upload of the file of a send item.
This PR adds several checks to make sure it only accepts the correct uploads.
=> Secure send file uploads

src/api/core/two_factor/mod.rs
- fixes https://github.com/dani-garcia/vaultwarden/issues/4528
=> Fix mail::send_incomplete_2fa_login panic issue

src/api/core/accounts.rs, src/db/models/device.rs
Fixed an issue with login with device for the new Bitwrden Beta clients. They seem to not support ISO8601 milli date/time, only micro.
Also updated the device display names to match Upstream and added the CLI devices which were missing.
=> Fix Login with device

src/api/core/mod.rs
=> Remove `version` from server config info

SECURITY.md
Update the security readme with a new GPG security key and some small other changes.
=> Updated security readme

.github/workflows/release.yml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
- Updated the web-vault to fix an issue with personal export.
Thanks to @stefan0xC for patching this.
Fixes #4875
- Updated crates to there latest version
- Updated the GitHub Actions
- Updated the xx image to the latest version
=> Update web-vault, crates and gha

src/mail.rs
=> fix invitation link via /admin

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml
- raise MSRV to 1.80.0
- also update the crates
=> Update Rust to 1.82.0

src/config.rs
- in case people want to try out the new extension design
More info:
https://www.reddit.com/r/Bitwarden/comments/1g6ipmp/bitwarden_browser_extension_ui_design_refresh/
https://bitwarden.com/blog/bringing-intuitive-workflows-and-visual-updates-to-the-bitwarden-browser/
=> Add `extension-refresh` feature flag

Cargo.lock, Cargo.toml
Including in this update is an update from lettre, which solves an issue with some specific SMTP mail providers.
=> Update crates and fix Mail issue

src/api/core/accounts.rs, src/api/core/mod.rs
- fix hibp username encoding
- fix password hint check
=> fix hibp username encoding and pw hint check

src/api/admin.rs, src/static/scripts/admin.css, src/static/scripts/admin_diagnostics.js, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/admin/diagnostics.hbs, src/static/templates/admin/users.hbs, src/util.rs
- Updated datatables
- Added a `X-Robots-Tags` header to prevent indexing
- Modified some layout settings
- Added Websocket check to diagnostics
- Added Security Header checks to diagnostics
- Added Error page response checks to diagnostics
- Modifed support string layout a bit
=> Some Backend Admin fixes and updates

src/api/core/two_factor/authenticator.rs
I built a `web-vault` based on the `v2024.12.1` version, and it appears that disabling a TOTP authenticator now rely on a dedicated endpoint.
Did not change the existing endpoint to keep compatibility with old clients.
=> Add TOTP delete endpoint

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
- Updated the web-vault to use v2025.1.0 (pre-release)
=> Update crates and web-vault to v2025.1.0

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, src/api/core/accounts.rs, src/db/models/auth_request.rs, src/db/models/device.rs
For new Devices tab in Account settings -> Security:
=> update web-vault to v2025.1.1 and add /api/devices

src/db/models/auth_request.rs
only show pending requests to fix #5465
=> hide already approved (or declined) auth_requests

src/util.rs
=> Make sure the icons are displayed correctly in desktop clients

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/releasecache-cleanup.yml, .github/workflows/trivy.yml
This commit updates the workflow files and also fixes some security issues which were reported by using zizmor https://github.com/woodruffw/zizmor
=> Update workflows and enhance security

src/api/core/organizations.rs
=> add bulk-access endpoint for collections

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml
- raise MSRV to 1.84.0
- also update the crates
=> Update Rust to 1.85.0

Cargo.lock, Cargo.toml, build.rs, src/api/admin.rs, src/config.rs, src/db/mod.rs, src/db/models/org_policy.rs, src/db/models/user.rs
- Added a new org policy
- Some new lint fixes
- Crate updates Switched to `pastey`, since `paste` is unmaintained.
=> Some fixes for the new web-vault and updates

.github/workflows/build.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, rust-toolchain.toml, src/http_client.rs, src/static/scripts/datatables.css, src/static/scripts/datatables.js
- Updated Rust to v1.85.1
- Updated crates and fixed breaking changes
- Updated datatables js
- Updated GitHub Actions
=> Update Rust, Crates and other deps

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, src/static/scripts/bootstrap.bundle.js, src/static/scripts/bootstrap.css, src/static/templates/scss/vaultwarden.scss.hbs
- Updated crates Pinned mimalloc, since it has issues with musl
- Updated web-vault to v2025.3.1
- Updated bootstrap
=> Update deps and web-vault

docker/Dockerfile.debian
=> Really fix building

src/api/core/ciphers.rs
this should fix #5816 (which was moved to #5817)
Before:
https://github.com/user-attachments/assets/f4206b53-21a2-4547-8948-cde5087c30be
After:
https://github.com/user-attachments/assets/3ad0cd62-ba72-448a-ad74-a74dcef17449
=> respond with cipher json when deleting attachments

.env.template, src/config.rs
/ref https://github.com/dani-garcia/bw_web_builds/pull/193#issuecomment-2816745793
=> feat: add feature flag export-attachments

src/api/core/two_factor/email.rs, src/api/identity.rs
I have kept the commits from PR #5719 so that the author is credited. The PRs are squashed at merge time anyway.
closes #5719
=> feat: add ip address in logs when email 2fa token is invalid or not available

.env.template, src/config.rs
This PR enables the ability to autofill TOTP codes via the inline menu
=> Add totp menu feature flag

src/api/core/organizations.rs
While adding the version check for email 2fa found this old check which is probably not needed anymore.
=> Remove old client version check

src/api/admin.rs
Better handle semver issues.
Fixes #5882
Fixes #5883
Fixes #5885
=> Fix admin diagnostics crash

Cargo.lock, Cargo.toml, src/api/admin.rs, src/static/scripts/admin.css, src/static/scripts/admin_diagnostics.js, src/static/templates/admin/diagnostics.hbs
- Some tweaks on the diagnostics layout
- Always show the latest web-vault version also when running in a container
Users can override the web-vault folder and forget
- Also updated to the latest crates.
Kinda fixes #5908
=> Some small admin updates

src/static/templates/scss/vaultwarden.scss.hbs
Starting with v2025.5.1 the login page will have custom classes so the fields to be disabled can be targeted specifically without risking side-effects
Cf. https://github.com/dani-garcia/bw_web_builds/pull/201
=> make css for login-page position independent

Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian
- Updated web-vault to v2025.6.0
=> Update crates and web-vault

src/api/icons.rs
remove redundant words in comment
=> chore: fix some minor issues in the comments

docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, src/static/scripts/bootstrap.bundle.js, src/static/scripts/bootstrap.css, src/static/scripts/datatables.css, src/static/scripts/datatables.js, src/static/templates/scss/vaultwarden.scss.hbs
- Updated web-vault to v2025.7.0
- Updated admin JS and CSS files
=> Update web-vault and admin resources

README.md
to alleviate the [unresolved tension](https://xkcd.com/859/).
fixes https://github.com/dani-garcia/vaultwarden/pull/6041#issuecomment-3054174362
=> close unmatched left parenthesis in the README

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/build.yml, .github/workflows/check-templates.yml, .github/workflows/hadolint.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, .github/workflows/zizmor.yml, Cargo.lock, Cargo.toml
- Updated all the crates, which probably fixes #5959
- Updated all the workflows and tested it with zizmor Also added zizmor as a workflow it self.
- Updated the issue template to better mention to search first.
=> Update crates, workflow and issue template

src/static/templates/scss/vaultwarden.scss.hbs
Hide the added fields from https://github.com/vaultwarden/vw_web_builds/pull/10
=> Hide login form custom fields

.github/ISSUE_TEMPLATE/bug_report.yml
Adjust issue template to hopefully show better to search for closed and open issues
=> Adjust issue template

src/api/core/accounts.rs
At the moment it does not work because the endpoint for the key rotation has been moved to `/accounts/key-management/rotate-user-account-keys` for a while now. This should fix account key rotation so it works again.
=> fix account key rotation

src/api/core/two_factor/webauthn.rs
The check if the token used was a known valid token also checked if it needed to be updated. This check caused always caused an issue with tokens which do not need or want to be updated.
Since the cred_ids are already checked and deemed valid we only need to check if there is an updated needed. Their already is a function for this `update_credential`, which returns `Some(true)` if this was the case. So, only update the records if that is the case, else do not update anything.
Also, used constant time compare to check and validate the cred_id's.
P.S. I tested this with macOS where the key was created, and iOS which synced the key.
Same for Bitwarden, used the Firefox Extension to register and my Android to authenticate.
The YubiKey5c still works too, both USB or NFC.
Fixes #6154
=> Fix WebauthN issue with Software Keys

playwright/.env.template, playwright/package-lock.json, playwright/package.json, playwright/test.env
Upgraded `maildev` and other dependencies, cf https://github.com/Timshel/maildev/issues/6
=> Fix Playwright test conf and update deps

.github/workflows/release.yml, .github/workflows/trivy.yml, .github/workflows/zizmor.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, docker/DockerSettings.yaml, docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.j2, macros/Cargo.toml
- Updated web-vault to v2025.7.2
- Updated Debian to v13 a.k.a. Trixie
- Adjusted Debian build where needed
- Updated several crates
- Updated workflows
- Updated pre-commit
=> Misc updates

.env.template, src/config.rs
This change is a follow up to #6166
- add new options to `.env.template`
- add validation for new config option values
=> refactor(config): update template, add validation
